// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  forceChangePassword,
  deleteLdapUser,
  getLdapUsers,
  createLdapUser,
  validateCredentials,
  logout,
  deleteManagedUser,
  getManagedUsers,
  updateManagedUser,
  createManagedUser,
  setUserTeams,
  deleteOidcUser,
  getOidcUsers,
  createOidcUser,
  validateOidcAccessToken,
  getSelf1,
  updateSelf,
  getSelfPermissions,
} from "../../../dist/methods/user/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  forceChangePassword: {
    route: "forceChangePassword",
    mediaType: "application/x-www-form-urlencoded",
    invoke: (bag) =>
      forceChangePassword(config, {
        confirmPassword: bag.__body?.["confirmPassword"],
        newPassword: bag.__body?.["newPassword"],
        password: bag.__body?.["password"],
        username: bag.__body?.["username"],
      }),
  },
  deleteLdapUser: {
    route: "deleteLdapUser",
    mediaType: "application/json",
    invoke: (bag) => deleteLdapUser(config, { username: bag.__body?.["username"] }),
  },
  getLdapUsers: { route: "getLdapUsers", mediaType: null, invoke: () => getLdapUsers(config, {}) },
  createLdapUser: {
    route: "createLdapUser",
    mediaType: "application/json",
    invoke: (bag) =>
      createLdapUser(config, {
        username: bag.__body?.["username"],
        dn: bag.__body?.["dn"],
        email: bag.__body?.["email"],
        permissions: bag.__body?.["permissions"],
        teams: bag.__body?.["teams"],
      }),
  },
  validateCredentials: {
    route: "validateCredentials",
    mediaType: "application/x-www-form-urlencoded",
    invoke: (bag) =>
      validateCredentials(config, {
        password: bag.__body?.["password"],
        username: bag.__body?.["username"],
      }),
  },
  logout: {
    route: "logout",
    mediaType: null,
    invoke: (bag) => logout(config, { authorization: bag["Authorization"] }),
  },
  deleteManagedUser: {
    route: "deleteManagedUser",
    mediaType: "application/json",
    invoke: (bag) => deleteManagedUser(config, { username: bag.__body?.["username"] }),
  },
  getManagedUsers: {
    route: "getManagedUsers",
    mediaType: null,
    invoke: () => getManagedUsers(config, {}),
  },
  updateManagedUser: {
    route: "updateManagedUser",
    mediaType: "application/json",
    invoke: (bag) =>
      updateManagedUser(config, {
        lastPasswordChange: bag.__body?.["lastPasswordChange"],
        username: bag.__body?.["username"],
        confirmPassword: bag.__body?.["confirmPassword"],
        email: bag.__body?.["email"],
        forcePasswordChange: bag.__body?.["forcePasswordChange"],
        fullname: bag.__body?.["fullname"],
        newPassword: bag.__body?.["newPassword"],
        nonExpiryPassword: bag.__body?.["nonExpiryPassword"],
        permissions: bag.__body?.["permissions"],
        suspended: bag.__body?.["suspended"],
        teams: bag.__body?.["teams"],
      }),
  },
  createManagedUser: {
    route: "createManagedUser",
    mediaType: "application/json",
    invoke: (bag) =>
      createManagedUser(config, {
        lastPasswordChange: bag.__body?.["lastPasswordChange"],
        username: bag.__body?.["username"],
        confirmPassword: bag.__body?.["confirmPassword"],
        email: bag.__body?.["email"],
        forcePasswordChange: bag.__body?.["forcePasswordChange"],
        fullname: bag.__body?.["fullname"],
        newPassword: bag.__body?.["newPassword"],
        nonExpiryPassword: bag.__body?.["nonExpiryPassword"],
        permissions: bag.__body?.["permissions"],
        suspended: bag.__body?.["suspended"],
        teams: bag.__body?.["teams"],
      }),
  },
  setUserTeams: {
    route: "setUserTeams",
    mediaType: "application/json",
    invoke: (bag) =>
      setUserTeams(config, { teams: bag.__body?.["teams"], username: bag.__body?.["username"] }),
  },
  deleteOidcUser: {
    route: "deleteOidcUser",
    mediaType: "application/json",
    invoke: (bag) => deleteOidcUser(config, { username: bag.__body?.["username"] }),
  },
  getOidcUsers: { route: "getOidcUsers", mediaType: null, invoke: () => getOidcUsers(config, {}) },
  createOidcUser: {
    route: "createOidcUser",
    mediaType: "application/json",
    invoke: (bag) =>
      createOidcUser(config, {
        username: bag.__body?.["username"],
        email: bag.__body?.["email"],
        permissions: bag.__body?.["permissions"],
        subjectIdentifier: bag.__body?.["subjectIdentifier"],
        teams: bag.__body?.["teams"],
      }),
  },
  validateOidcAccessToken: {
    route: "validateOidcAccessToken",
    mediaType: "application/x-www-form-urlencoded",
    invoke: (bag) =>
      validateOidcAccessToken(config, {
        idToken: bag.__body?.["idToken"],
        accessToken: bag.__body?.["accessToken"],
      }),
  },
  getSelf1: { route: "getSelf_1", mediaType: null, invoke: () => getSelf1(config, {}) },
  updateSelf: {
    route: "updateSelf",
    mediaType: "application/json",
    invoke: (bag) =>
      updateSelf(config, {
        lastPasswordChange: bag.__body?.["lastPasswordChange"],
        username: bag.__body?.["username"],
        confirmPassword: bag.__body?.["confirmPassword"],
        email: bag.__body?.["email"],
        forcePasswordChange: bag.__body?.["forcePasswordChange"],
        fullname: bag.__body?.["fullname"],
        newPassword: bag.__body?.["newPassword"],
        nonExpiryPassword: bag.__body?.["nonExpiryPassword"],
        permissions: bag.__body?.["permissions"],
        suspended: bag.__body?.["suspended"],
        teams: bag.__body?.["teams"],
      }),
  },
  getSelfPermissions: {
    route: "getSelfPermissions",
    mediaType: null,
    invoke: () => getSelfPermissions(config, {}),
  },
};

test("user/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
