// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { AclMappingRequest } from "../types/acl";
import { ListProjectsResponseItem, ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest } from "../client";
import { validatePattern, validateUuid } from "../validation";

export type AddMappingError = ProblemDetails;

export type AddMappingParams = AclMappingRequest;

/**
 * Creates an ACL mapping between a project and a team. Supply `project` and `team` as UUIDs; the authenticated user needs the `ACCESS_MANAGEMENT` permission. Use this operation to grant a team access to a project through an ACL mapping.
 *
 * Requires permission ACCESS_MANAGEMENT
 *
 * @param project - Required `string` value serialized in the `project` wire
 *   field.
 * @param team - Required `string` value serialized in the `team` wire field.
 */
export async function addMapping(
  config: ClientConfig,
  { project, team }: AddMappingParams,
  requestOptions?: RequestOptions,
): Promise<AclMappingRequest> {
  validatePattern(
    "project",
    project,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  validatePattern("team", team, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

  const _resp = await sdkRequest<AclMappingRequest>({
    method: "PUT",
    path: `/v1/acl/mapping`,
    operationId: "addMapping",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      project,
      team,
    },
    config,
  });
  return _resp.data;
}

export type DeleteMappingError = ProblemDetails;

export interface DeleteMappingParams {
  teamUuid: string;
  projectUuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param teamUuid - The UUID of the team to delete the mapping for
 * @param projectUuid - The UUID of the project to delete the mapping for
 */
export async function deleteMapping(
  config: ClientConfig,
  { teamUuid, projectUuid }: DeleteMappingParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("teamUuid", teamUuid);

  validateUuid("projectUuid", projectUuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/acl/mapping/team/${encodePathSegment(teamUuid)}/project/${encodePathSegment(projectUuid)}`,
    operationId: "deleteMapping",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface RetrieveProjectsParams {
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  excludeInactive?: boolean;
  onlyRoot?: boolean;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 *
 * @param uuid - The UUID of the team to retrieve mappings for
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 * @param onlyRoot - Optionally excludes children projects from being returned
 */
export async function retrieveProjects(
  config: ClientConfig,
  {
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    excludeInactive,
    onlyRoot,
  }: RetrieveProjectsParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/acl/team/${encodePathSegment(uuid)}`,
    operationId: "retrieveProjects",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
      onlyRoot: queryValue(onlyRoot, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export class AclNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Creates an ACL mapping between a project and a team. Supply `project` and `team` as UUIDs; the authenticated user needs the `ACCESS_MANAGEMENT` permission. Use this operation to grant a team access to a project through an ACL mapping.
   *
   * Requires permission ACCESS_MANAGEMENT
   */
  addMapping(
    params: AddMappingParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addMapping> {
    return addMapping(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  deleteMapping(
    params: DeleteMappingParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteMapping> {
    return deleteMapping(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  retrieveProjects(
    params: RetrieveProjectsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof retrieveProjects> {
    return retrieveProjects(this._config, params, requestOptions);
  }
}
