// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { AnalysisRequest, AnalysisTrailResponse } from "../types/analysis";
import { ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { queryValue, sdkRequest } from "../client";
import { validatePattern, validateUuid } from "../validation";

export type RetrieveAnalysisError = ProblemDetails;

export interface RetrieveAnalysisParams {
  component: string;
  vulnerability: string;
  project?: string;
}

/**
 * Requires permission VIEW_VULNERABILITY
 *
 * @param component - The UUID of the component
 * @param vulnerability - The UUID of the vulnerability
 * @param project - The UUID of the project
 */
export async function retrieveAnalysis(
  config: ClientConfig,
  { component, vulnerability, project }: RetrieveAnalysisParams,
  requestOptions?: RequestOptions,
): Promise<AnalysisTrailResponse> {
  validateUuid("component", component);

  validateUuid("vulnerability", vulnerability);

  if (project != null) {
    validateUuid("project", project);
  }

  const _resp = await sdkRequest<AnalysisTrailResponse>({
    method: "GET",
    path: `/v1/analysis`,
    operationId: "retrieveAnalysis",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      component: queryValue(component, "form", true),
      vulnerability: queryValue(vulnerability, "form", true),
      project: queryValue(project, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UpdateAnalysisError = ProblemDetails;

export type UpdateAnalysisParams = AnalysisRequest;

/**
 * Records an analysis decision for a vulnerability affecting a component. Supply `component` and `vulnerability`, and add analysis state, justification, response, or comments as needed. The authenticated user needs the `VULNERABILITY_ANALYSIS` or `VULNERABILITY_ANALYSIS_UPDATE` permission.
 *
 * Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_UPDATE
 *
 * @param component - Required `string` value serialized in the `component` wire
 *   field.
 * @param vulnerability - Required `string` value serialized in the
 *   `vulnerability` wire field.
 * @param analysisDetails - Optional `string` value serialized in the
 *   `analysisDetails` wire field.
 * @param analysisJustification - Optional enumerated value serialized in the
 *   `analysisJustification` wire field.
 * @param analysisResponse - Optional enumerated value serialized in the
 *   `analysisResponse` wire field.
 * @param analysisState - Optional enumerated value serialized in the
 *   `analysisState` wire field.
 * @param comment - Optional `string` value serialized in the `comment` wire
 *   field.
 * @param isSuppressed - Optional `boolean` value serialized in the
 *   `isSuppressed` wire field.
 * @param project - Optional `string` value serialized in the `project` wire
 *   field.
 * @param suppressed - Optional `boolean` value serialized in the `suppressed`
 *   wire field.
 */
export async function updateAnalysis(
  config: ClientConfig,
  {
    component,
    vulnerability,
    analysisDetails,
    analysisJustification,
    analysisResponse,
    analysisState,
    comment,
    isSuppressed,
    project,
    suppressed,
  }: UpdateAnalysisParams,
  requestOptions?: RequestOptions,
): Promise<AnalysisTrailResponse> {
  validatePattern(
    "component",
    component,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  validatePattern(
    "vulnerability",
    vulnerability,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  if (project != null) {
    validatePattern(
      "project",
      project,
      "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    );
  }

  const _resp = await sdkRequest<AnalysisTrailResponse>({
    method: "PUT",
    path: `/v1/analysis`,
    operationId: "updateAnalysis",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      component,
      vulnerability,
      analysisDetails,
      analysisJustification,
      analysisResponse,
      analysisState,
      comment,
      isSuppressed,
      project,
      suppressed,
    },
    config,
  });
  return _resp.data;
}

export class AnalysisNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission VIEW_VULNERABILITY
   */
  retrieve(
    params: RetrieveAnalysisParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof retrieveAnalysis> {
    return retrieveAnalysis(this._config, params, requestOptions);
  }
  /**
   * Records an analysis decision for a vulnerability affecting a component. Supply `component` and `vulnerability`, and add analysis state, justification, response, or comments as needed. The authenticated user needs the `VULNERABILITY_ANALYSIS` or `VULNERABILITY_ANALYSIS_UPDATE` permission.
   *
   * Requires permission VULNERABILITY_ANALYSIS or VULNERABILITY_ANALYSIS_UPDATE
   */
  update(
    params: UpdateAnalysisParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateAnalysis> {
    return updateAnalysis(this._config, params, requestOptions);
  }
}
