// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateUuid } from "../validation";

export interface GetProjectPolicyViolationsBadge1Params {
  name: string;
  version: string;
}

/**
 * Retrieves an SVG badge showing current policy violation metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
 *
 * @param name - The name of the project to query on
 * @param version - The version of the project to query on
 */
export async function getProjectPolicyViolationsBadge1(
  config: ClientConfig,
  { name, version }: GetProjectPolicyViolationsBadge1Params,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/v1/badge/violations/project/${encodePathSegment(name)}/${encodePathSegment(version)}`,
    operationId: "getProjectPolicyViolationsBadge1",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GetProjectPolicyViolationsBadgeParams {
  uuid: string;
}

/**
 * Retrieves an SVG badge showing current policy violation metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
 *
 * @param uuid - The UUID of the project to retrieve a badge for
 */
export async function getProjectPolicyViolationsBadge(
  config: ClientConfig,
  { uuid }: GetProjectPolicyViolationsBadgeParams,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/v1/badge/violations/project/${encodePathSegment(uuid)}`,
    operationId: "getProjectPolicyViolationsBadge",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GetProjectVulnerabilitiesBadge1Params {
  name: string;
  version: string;
}

/**
 * Retrieves an SVG badge showing current vulnerability metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
 *
 * @param name - The name of the project to query on
 * @param version - The version of the project to query on
 */
export async function getProjectVulnerabilitiesBadge1(
  config: ClientConfig,
  { name, version }: GetProjectVulnerabilitiesBadge1Params,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/v1/badge/vulns/project/${encodePathSegment(name)}/${encodePathSegment(version)}`,
    operationId: "getProjectVulnerabilitiesBadge1",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GetProjectVulnerabilitiesBadgeParams {
  uuid: string;
}

/**
 * Retrieves an SVG badge showing current vulnerability metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
 *
 * @param uuid - The UUID of the project to retrieve metrics for
 */
export async function getProjectVulnerabilitiesBadge(
  config: ClientConfig,
  { uuid }: GetProjectVulnerabilitiesBadgeParams,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/v1/badge/vulns/project/${encodePathSegment(uuid)}`,
    operationId: "getProjectVulnerabilitiesBadge",
    responseDecoder: "bytes",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class BadgeNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves an SVG badge showing current policy violation metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
   */
  getProjectPolicyViolations1(
    params: GetProjectPolicyViolationsBadge1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectPolicyViolationsBadge1> {
    return getProjectPolicyViolationsBadge1(this._config, params, requestOptions);
  }
  /**
   * Retrieves an SVG badge showing current policy violation metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
   */
  getProjectPolicyViolations(
    params: GetProjectPolicyViolationsBadgeParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectPolicyViolationsBadge> {
    return getProjectPolicyViolationsBadge(this._config, params, requestOptions);
  }
  /**
   * Retrieves an SVG badge showing current vulnerability metrics for a project identified by name and version. Use `name` and `version` to select the project whose badge you want to display. The badge is unavailable when badges are disabled.
   */
  getProjectVulnerabilities1(
    params: GetProjectVulnerabilitiesBadge1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectVulnerabilitiesBadge1> {
    return getProjectVulnerabilitiesBadge1(this._config, params, requestOptions);
  }
  /**
   * Retrieves an SVG badge showing current vulnerability metrics for a project. Supply the project's UUID in `uuid` to select the project. The badge is unavailable when badges are disabled.
   */
  getProjectVulnerabilities(
    params: GetProjectVulnerabilitiesBadgeParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectVulnerabilitiesBadge> {
    return getProjectVulnerabilitiesBadge(this._config, params, requestOptions);
  }
}
