// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { BomUploadResponse, IsTokenBeingProcessedResponse, ProblemDetails } from "../types/shared";
import { BomSubmitRequest } from "../types/bom";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateLength, validatePattern, validateUuid } from "../validation";

export type UploadBomError = ProblemDetails;

export interface UploadBomParams {
  autoCreate?: boolean;
  bom?: Blob | File;
  isActive?: boolean;
  isLatest?: boolean;
  parentName?: string;
  parentUuid?: string;
  parentVersion?: string;
  project?: string;
  projectName?: string;
  projectTags?: string;
  projectVersion?: string;
}

/**
 * Uploads a CycloneDX bill of materials (BOM) and starts processing it for a project. Send the BOM as multipart form data; identify the project with `project`, or supply both `projectName` and `projectVersion`, and use `autoCreate` to create a project when needed. The response includes a token for checking processing progress; BOM uploads require the `BOM_UPLOAD` permission, and creating a project also requires one of the documented project-creation permissions.
 *
 * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM artifact may be supplied uncompressed or compressed. If the BOM is uncompressed, the supported MediaType is 'application/xml' or 'application/json'. If the BOM is compressed, the supported MediaType is 'application/gzip' or 'application/zstd' and must match the actual compression of the data. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. Requires permission BOM_UPLOAD
 */
export async function uploadBom(
  config: ClientConfig,
  {
    autoCreate,
    bom,
    isActive,
    isLatest,
    parentName,
    parentUuid,
    parentVersion,
    project,
    projectName,
    projectTags,
    projectVersion,
  }: UploadBomParams = {},
  requestOptions?: RequestOptions,
): Promise<BomUploadResponse> {
  const _resp = await sdkRequest<BomUploadResponse>({
    method: "POST",
    path: `/v1/bom`,
    operationId: "uploadBom",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      autoCreate,
      bom,
      isActive,
      isLatest,
      parentName,
      parentUUID: parentUuid,
      parentVersion,
      project,
      projectName,
      projectTags,
      projectVersion,
    },
    contentType: "multipart/form-data",
    config,
  });
  return _resp.data;
}

export type UploadBomBase64EncodedError = ProblemDetails;

export type UploadBomBase64EncodedParams = BomSubmitRequest;

/**
 * Uploads a Base64-encoded CycloneDX bill of materials (BOM) and associates it with a project. Supply `project`, `projectName`, and `projectVersion` as required by the schema, and use `autoCreate` to create a project when it does not exist. Processing is asynchronous; use the returned `token` to check progress, and send large BOMs through the POST upload endpoint to avoid the 20,000,000-character limit.
 *
 * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. The maximum allowed length of the bom value is 20'000'000 characters. When uploading large BOMs, the POST endpoint is preferred, as it does not have this limit. Requires permission BOM_UPLOAD
 *
 * @param bom - Base64 encoded BOM
 * @param project - Required `string` value serialized in the `project` wire
 *   field.
 * @param projectName - Required `string` value serialized in the `projectName`
 *   wire field.
 * @param projectVersion - Required `string` value serialized in the
 *   `projectVersion` wire field.
 * @param autoCreate - Optional `boolean` value serialized in the `autoCreate`
 *   wire field.
 * @param isActive - Optional `boolean` value serialized in the `isActive` wire
 *   field.
 * @param isLatest - Optional `boolean` value serialized in the `isLatest` wire
 *   field.
 * @param parentName - Optional `string` value serialized in the `parentName`
 *   wire field.
 * @param parentUuid - Optional `string` value serialized in the `parentUUID`
 *   wire field.
 * @param parentVersion - Optional `string` value serialized in the
 *   `parentVersion` wire field.
 * @param projectTags - Optional array value serialized in the `projectTags` wire
 *   field.
 */
export async function uploadBomBase64Encoded(
  config: ClientConfig,
  {
    bom,
    project,
    projectName,
    projectVersion,
    autoCreate,
    isActive,
    isLatest,
    parentName,
    parentUuid,
    parentVersion,
    projectTags,
  }: UploadBomBase64EncodedParams,
  requestOptions?: RequestOptions,
): Promise<BomUploadResponse> {
  validatePattern("bom", bom, "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$");

  validatePattern(
    "project",
    project,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  validateLength("projectName", projectName, { min: 1 });

  validateLength("projectVersion", projectVersion, { min: 1 });

  if (parentUuid != null) {
    validatePattern(
      "parentUUID",
      parentUuid,
      "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    );
  }

  const _resp = await sdkRequest<BomUploadResponse>({
    method: "PUT",
    path: `/v1/bom`,
    operationId: "uploadBomBase64Encoded",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      bom,
      project,
      projectName,
      projectVersion,
      autoCreate,
      isActive,
      isLatest,
      parentName,
      parentUUID: parentUuid,
      parentVersion,
      projectTags,
    },
    config,
  });
  return _resp.data;
}

export type ExportComponentAsCycloneDxError = ProblemDetails;

export interface ExportComponentAsCycloneDxParams {
  uuid: string;
  format?: string;
  version?: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the component to export
 * @param format - The format to output (defaults to JSON)
 * @param version - The CycloneDX Spec variant exported (defaults to: '1.5')
 */
export async function exportComponentAsCycloneDx(
  config: ClientConfig,
  { uuid, format, version }: ExportComponentAsCycloneDxParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/v1/bom/cyclonedx/component/${encodePathSegment(uuid)}`,
    operationId: "exportComponentAsCycloneDx",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      format: queryValue(format, "form", true),
      version: queryValue(version, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type ExportProjectAsCycloneDxError = ProblemDetails;

export interface ExportProjectAsCycloneDxParams {
  uuid: string;
  format?: string;
  variant?: string;
  download?: boolean;
  version?: string;
}

/**
 * Requires permission VIEW_PORTFOLIO The withVulnerabilities and vdr variants further require any of the following permissions: VIEW_VULNERABILITY VULNERABILITY_ANALYSIS VULNERABILITY_ANALYSIS_READ
 *
 * @param uuid - The UUID of the project to export
 * @param format - The format to output (defaults to JSON)
 * @param variant - Specifies the CycloneDX variant to export. Value options are
 *   'inventory' and 'withVulnerabilities'. (defaults to 'inventory')
 * @param download - Force the resulting BOM to be downloaded as a file (defaults
 *   to 'false')
 * @param version - The CycloneDX Spec variant exported (defaults to: '1.5')
 */
export async function exportProjectAsCycloneDx(
  config: ClientConfig,
  { uuid, format, variant, download, version }: ExportProjectAsCycloneDxParams,
  requestOptions?: RequestOptions,
): Promise<Blob | File> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Blob | File>({
    method: "GET",
    path: `/v1/bom/cyclonedx/project/${encodePathSegment(uuid)}`,
    operationId: "exportProjectAsCycloneDx",
    responseDecoder: "bytes",
    ...requestOptions,
    query: {
      format: queryValue(format, "form", true),
      variant: queryValue(variant, "form", true),
      download: queryValue(download, "form", true),
      version: queryValue(version, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface IsTokenBeingProcessedParams {
  uuid: string;
}

/**
 * This endpoint is intended to be used in conjunction with uploading a supported BOM document. Upon upload, a token will be returned. The token can then be queried using this endpoint to determine if any tasks (such as vulnerability analysis) is being performed on the BOM: A value of true indicates processing is occurring. A value of false indicates that no processing is occurring for the specified token. However, a value of false also does not confirm the token is valid, only that no processing is associated with the specified token. Requires permission BOM_UPLOAD Deprecated . Use /v1/event/token/{uuid} instead.
 *
 * @param uuid - The UUID of the token to query
 * @deprecated This operation is deprecated and may be removed in a future
 *   release.
 */
export async function isTokenBeingProcessed(
  config: ClientConfig,
  { uuid }: IsTokenBeingProcessedParams,
  requestOptions?: RequestOptions,
): Promise<IsTokenBeingProcessedResponse> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<IsTokenBeingProcessedResponse>({
    method: "GET",
    path: `/v1/bom/token/${encodePathSegment(uuid)}`,
    operationId: "isTokenBeingProcessed",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class BomNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Uploads a CycloneDX bill of materials (BOM) and starts processing it for a project. Send the BOM as multipart form data; identify the project with `project`, or supply both `projectName` and `projectVersion`, and use `autoCreate` to create a project when needed. The response includes a token for checking processing progress; BOM uploads require the `BOM_UPLOAD` permission, and creating a project also requires one of the documented project-creation permissions.
   *
   * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM artifact may be supplied uncompressed or compressed. If the BOM is uncompressed, the supported MediaType is 'application/xml' or 'application/json'. If the BOM is compressed, the supported MediaType is 'application/gzip' or 'application/zstd' and must match the actual compression of the data. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. Requires permission BOM_UPLOAD
   */
  upload(
    params: UploadBomParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof uploadBom> {
    return uploadBom(this._config, params, requestOptions);
  }
  /**
   * Uploads a Base64-encoded CycloneDX bill of materials (BOM) and associates it with a project. Supply `project`, `projectName`, and `projectVersion` as required by the schema, and use `autoCreate` to create a project when it does not exist. Processing is asynchronous; use the returned `token` to check progress, and send large BOMs through the POST upload endpoint to avoid the 20,000,000-character limit.
   *
   * Expects CycloneDX and a valid project UUID. If a UUID is not specified, then the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and true and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT , PORTFOLIO_MANAGEMENT_CREATE , or PROJECT_CREATION_UPLOAD permission. The BOM will be validated against the CycloneDX schema. If schema validation fails, a response with problem details in RFC 9457 format will be returned. In this case, the response's content type will be application/problem+json . When creating projects, parentUUID or parentName and parentVersion can place the new project under a parent, projectTags can apply tags, and isLatest can mark it as the latest version. The isActive parameter sets the project's active state whenever it is provided, including when the target project already exists, so clients should send it only when they intend to change that state. The maximum allowed length of the bom value is 20'000'000 characters. When uploading large BOMs, the POST endpoint is preferred, as it does not have this limit. Requires permission BOM_UPLOAD
   */
  uploadBase64Encoded(
    params: UploadBomBase64EncodedParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof uploadBomBase64Encoded> {
    return uploadBomBase64Encoded(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  exportComponentAsCycloneDx(
    params: ExportComponentAsCycloneDxParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof exportComponentAsCycloneDx> {
    return exportComponentAsCycloneDx(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO The withVulnerabilities and vdr variants further require any of the following permissions: VIEW_VULNERABILITY VULNERABILITY_ANALYSIS VULNERABILITY_ANALYSIS_READ
   */
  exportProjectAsCycloneDx(
    params: ExportProjectAsCycloneDxParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof exportProjectAsCycloneDx> {
    return exportProjectAsCycloneDx(this._config, params, requestOptions);
  }
  /**
   * This endpoint is intended to be used in conjunction with uploading a supported BOM document. Upon upload, a token will be returned. The token can then be queried using this endpoint to determine if any tasks (such as vulnerability analysis) is being performed on the BOM: A value of true indicates processing is occurring. A value of false indicates that no processing is occurring for the specified token. However, a value of false also does not confirm the token is valid, only that no processing is associated with the specified token. Requires permission BOM_UPLOAD Deprecated . Use /v1/event/token/{uuid} instead.
   *
   * @deprecated This operation is deprecated and may be removed in a future
   *   release.
   */
  isTokenBeingProcessed(
    params: IsTokenBeingProcessedParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof isTokenBeingProcessed> {
    return isTokenBeingProcessed(this._config, params, requestOptions);
  }
}
