// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { CvssScoreResponse, Score } from "../types/calculator";
import type { ClientConfig, RequestOptions } from "../client";
import { queryValue, sdkRequest } from "../client";

export interface GetCvssScoresParams {
  vector: string;
}

/**
 * Calculates CVSS base, impact, and exploitability scores from a CVSS vector. Supply a valid `vector` using CVSS v2, v3, or v4. The response includes the calculated scores and any applicable temporal or environmental scores.
 *
 * @param vector - A valid CVSSv2, CVSSv3 or CVSSv4 vector
 */
export async function getCvssScores(
  config: ClientConfig,
  { vector }: GetCvssScoresParams,
  requestOptions?: RequestOptions,
): Promise<CvssScoreResponse> {
  const _resp = await sdkRequest<CvssScoreResponse>({
    method: "GET",
    path: `/v1/calculator/cvss`,
    operationId: "getCvssScores",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      vector: queryValue(vector, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetOwaspRrScoresParams {
  vector: string;
}

/**
 * Calculates OWASP Risk Rating likelihood and impact scores from an OWASP Risk Rating vector. Supply a valid `vector` to calculate the likelihood, technical impact, and business impact scores. The response also includes the corresponding HIGH, MEDIUM, or LOW ratings.
 *
 * @param vector - A valid OWASP Risk Rating vector
 */
export async function getOwaspRrScores(
  config: ClientConfig,
  { vector }: GetOwaspRrScoresParams,
  requestOptions?: RequestOptions,
): Promise<Score> {
  const _resp = await sdkRequest<Score>({
    method: "GET",
    path: `/v1/calculator/owasp`,
    operationId: "getOwaspRrScores",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      vector: queryValue(vector, "form", true),
    },
    config,
  });
  return _resp.data;
}

export class CalculatorNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Calculates CVSS base, impact, and exploitability scores from a CVSS vector. Supply a valid `vector` using CVSS v2, v3, or v4. The response includes the calculated scores and any applicable temporal or environmental scores.
   */
  getCvssScores(
    params: GetCvssScoresParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getCvssScores> {
    return getCvssScores(this._config, params, requestOptions);
  }
  /**
   * Calculates OWASP Risk Rating likelihood and impact scores from an OWASP Risk Rating vector. Supply a valid `vector` to calculate the likelihood, technical impact, and business impact scores. The response also includes the corresponding HIGH, MEDIUM, or LOW ratings.
   */
  getOwaspRrScores(
    params: GetOwaspRrScoresParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getOwaspRrScores> {
    return getOwaspRrScores(this._config, params, requestOptions);
  }
}
