// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  ComponentPropertyResponse,
  CreateComponentPropertyRequest,
} from "../types/component-property";
import { ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateLength, validatePattern, validateUuid } from "../validation";

export type GetPropertiesError = ProblemDetails;

export interface GetPropertiesParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the component to retrieve properties for
 */
export async function getProperties(
  config: ClientConfig,
  { uuid }: GetPropertiesParams,
  requestOptions?: RequestOptions,
): Promise<ComponentPropertyResponse[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ComponentPropertyResponse[]>({
    method: "GET",
    path: `/v1/component/${encodePathSegment(uuid)}/property`,
    operationId: "getProperties",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type CreatePropertyError = ProblemDetails;

export type CreatePropertyParams = CreateComponentPropertyRequest & {
  uuid: string;
};

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
 *
 * @param uuid - The UUID of the component to create a property for
 * @param propertyName - Name of the property
 * @param propertyType - Type of the property
 * @param description - Description of the property
 * @param groupName - Group the property belongs to
 * @param propertyValue - Value of the property
 */
export async function createProperty(
  config: ClientConfig,
  { uuid, propertyName, propertyType, description, groupName, propertyValue }: CreatePropertyParams,
  requestOptions?: RequestOptions,
): Promise<ComponentPropertyResponse> {
  validateUuid("uuid", uuid);

  validateLength("propertyName", propertyName, { min: 1, max: 255 });
  validatePattern("propertyName", propertyName, "\\P{Cc}+");

  if (description != null) {
    validateLength("description", description, { min: 0, max: 255 });
    validatePattern("description", description, "\\P{Cc}+");
  }

  if (groupName != null) {
    validateLength("groupName", groupName, { min: 1, max: 255 });
    validatePattern("groupName", groupName, "\\P{Cc}+");
  }

  if (propertyValue != null) {
    validateLength("propertyValue", propertyValue, { min: 0, max: 1024 });
    validatePattern("propertyValue", propertyValue, "\\P{Cc}+");
  }

  const _resp = await sdkRequest<ComponentPropertyResponse>({
    method: "PUT",
    path: `/v1/component/${encodePathSegment(uuid)}/property`,
    operationId: "createProperty",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      propertyName,
      propertyType,
      description,
      groupName,
      propertyValue,
    },
    config,
  });
  return _resp.data;
}

export type DeletePropertyError = ProblemDetails;

export interface DeletePropertyParams {
  uuid: string;
  propertyUuid: string;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the component to delete a property from
 * @param propertyUuid - The UUID of the component property to delete
 */
export async function deleteProperty(
  config: ClientConfig,
  { uuid, propertyUuid }: DeletePropertyParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  validateUuid("propertyUuid", propertyUuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/component/${encodePathSegment(uuid)}/property/${encodePathSegment(propertyUuid)}`,
    operationId: "deleteProperty",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export class ComponentPropertyNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getProperties(
    params: GetPropertiesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProperties> {
    return getProperties(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
   */
  createProperty(
    params: CreatePropertyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createProperty> {
    return createProperty(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
   */
  deleteProperty(
    params: DeletePropertyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteProperty> {
    return deleteProperty(this._config, params, requestOptions);
  }
}
