// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Cwe } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export interface GetCwesParams {
  searchText?: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Lists CWE records, optionally filtered by a case-insensitive substring in the CWE name or CWE ID. Use `pageNumber` with `pageSize`, or `offset` with `limit`, to paginate results; `sortName` and `sortOrder` control ordering.
 *
 * Returns a list of all CWEs
 *
 * @param searchText - Case-insensitive substring filter matched against CWE name
 *   and CWE-ID.
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 */
export async function getCwes(
  config: ClientConfig,
  { searchText, pageNumber, pageSize, offset, limit, sortName, sortOrder }: GetCwesParams = {},
  requestOptions?: RequestOptions,
): Promise<Cwe[]> {
  const _resp = await sdkRequest<Cwe[]>({
    method: "GET",
    path: `/v1/cwe`,
    operationId: "getCwes",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      searchText: queryValue(searchText, "form", true),
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetCweParams {
  cweId: number;
}

/**
 * Retrieves a specific CWE by its identifier. Supply the `cweId` path parameter to select the CWE record.
 *
 * @param cweId - The CWE ID of the CWE to retrieve
 */
export async function getCwe(
  config: ClientConfig,
  { cweId }: GetCweParams,
  requestOptions?: RequestOptions,
): Promise<Cwe> {
  const _resp = await sdkRequest<Cwe>({
    method: "GET",
    path: `/v1/cwe/${encodePathSegment(cweId)}`,
    operationId: "getCwe",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class CweNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists CWE records, optionally filtered by a case-insensitive substring in the CWE name or CWE ID. Use `pageNumber` with `pageSize`, or `offset` with `limit`, to paginate results; `sortName` and `sortOrder` control ordering.
   *
   * Returns a list of all CWEs
   */
  get(params: GetCwesParams = {}, requestOptions?: RequestOptions): ReturnType<typeof getCwes> {
    return getCwes(this._config, params, requestOptions);
  }
  /**
   * Retrieves a specific CWE by its identifier. Supply the `cweId` path parameter to select the CWE record.
   */
  getCwe(params: GetCweParams, requestOptions?: RequestOptions): ReturnType<typeof getCwe> {
    return getCwe(this._config, params, requestOptions);
  }
}
