// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { DependencyGraphResponse } from "../types/dependency-graph";
import { ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateUuid } from "../validation";

export type GetComponentsAndServicesByComponentUuidError = ProblemDetails;

export interface GetComponentsAndServicesByComponentUuidParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the component
 */
export async function getComponentsAndServicesByComponentUuid(
  config: ClientConfig,
  { uuid }: GetComponentsAndServicesByComponentUuidParams,
  requestOptions?: RequestOptions,
): Promise<DependencyGraphResponse[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<DependencyGraphResponse[]>({
    method: "GET",
    path: `/v1/dependencyGraph/component/${encodePathSegment(uuid)}/directDependencies`,
    operationId: "getComponentsAndServicesByComponentUuid",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type GetComponentsAndServicesByProjectUuidError = ProblemDetails;

export interface GetComponentsAndServicesByProjectUuidParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project
 */
export async function getComponentsAndServicesByProjectUuid(
  config: ClientConfig,
  { uuid }: GetComponentsAndServicesByProjectUuidParams,
  requestOptions?: RequestOptions,
): Promise<DependencyGraphResponse[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<DependencyGraphResponse[]>({
    method: "GET",
    path: `/v1/dependencyGraph/project/${encodePathSegment(uuid)}/directDependencies`,
    operationId: "getComponentsAndServicesByProjectUuid",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class DependencyGraphNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getComponentsAndServicesByComponentUuid(
    params: GetComponentsAndServicesByComponentUuidParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getComponentsAndServicesByComponentUuid> {
    return getComponentsAndServicesByComponentUuid(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getComponentsAndServicesByProjectUuid(
    params: GetComponentsAndServicesByProjectUuidParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getComponentsAndServicesByProjectUuid> {
    return getComponentsAndServicesByProjectUuid(this._config, params, requestOptions);
  }
}
