// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { IsTokenBeingProcessedResponse } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateUuid } from "../validation";

export interface IsTokenBeingProcessed1Params {
  uuid: string;
}

/**
 * This endpoint is intended to be used in conjunction with other API calls which return a token for asynchronous tasks. The token can then be queried using this endpoint to determine if the task is complete: A value of true indicates processing is occurring. A value of false indicates that no processing is occurring for the specified token. However, a value of false also does not confirm the token is valid, only that no processing is associated with the specified token.
 *
 * @param uuid - The UUID of the token to query
 */
export async function isTokenBeingProcessed1(
  config: ClientConfig,
  { uuid }: IsTokenBeingProcessed1Params,
  requestOptions?: RequestOptions,
): Promise<IsTokenBeingProcessedResponse> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<IsTokenBeingProcessedResponse>({
    method: "GET",
    path: `/v1/event/token/${encodePathSegment(uuid)}`,
    operationId: "isTokenBeingProcessed1",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class EventNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * This endpoint is intended to be used in conjunction with other API calls which return a token for asynchronous tasks. The token can then be queried using this endpoint to determine if the task is complete: A value of true indicates processing is occurring. A value of false indicates that no processing is occurring for the specified token. However, a value of false also does not confirm the token is valid, only that no processing is associated with the specified token.
   */
  isTokenBeingProcessed1(
    params: IsTokenBeingProcessed1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof isTokenBeingProcessed1> {
    return isTokenBeingProcessed1(this._config, params, requestOptions);
  }
}
