// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { MappedLdapGroupRequest, MappedLdapGroupResponse } from "../types/ldap";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validatePattern, validateUuid } from "../validation";

/**
 * This API performs a pass-through query to the configured LDAP server. Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 */
export async function retrieveLdapGroups(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<string[]> {
  const _resp = await sdkRequest<string[]>({
    method: "GET",
    path: `/v1/ldap/groups`,
    operationId: "retrieveLdapGroups",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type AddMapping1Params = MappedLdapGroupRequest;

/**
 * Creates a mapping between an LDAP group distinguished name and a team. Supply the `dn` and `team` fields in the JSON body; you need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission. A successful response includes the mapping's UUID.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param dn - Required `string` value serialized in the `dn` wire field.
 * @param team - Required `string` value serialized in the `team` wire field.
 */
export async function addMapping1(
  config: ClientConfig,
  { dn, team }: AddMapping1Params,
  requestOptions?: RequestOptions,
): Promise<MappedLdapGroupResponse> {
  validatePattern("team", team, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

  const _resp = await sdkRequest<MappedLdapGroupResponse>({
    method: "PUT",
    path: `/v1/ldap/mapping`,
    operationId: "addMapping1",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      dn,
      team,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteMapping1Params {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the mapping to delete
 */
export async function deleteMapping1(
  config: ClientConfig,
  { uuid }: DeleteMapping1Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/ldap/mapping/${encodePathSegment(uuid)}`,
    operationId: "deleteMapping1",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface RetrieveLdapGroups1Params {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 *
 * @param uuid - The UUID of the team to retrieve mappings for
 */
export async function retrieveLdapGroups1(
  config: ClientConfig,
  { uuid }: RetrieveLdapGroups1Params,
  requestOptions?: RequestOptions,
): Promise<MappedLdapGroupResponse[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<MappedLdapGroupResponse[]>({
    method: "GET",
    path: `/v1/ldap/team/${encodePathSegment(uuid)}`,
    operationId: "retrieveLdapGroups1",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class LdapNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * This API performs a pass-through query to the configured LDAP server. Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  retrieveGroups(requestOptions?: RequestOptions): ReturnType<typeof retrieveLdapGroups> {
    return retrieveLdapGroups(this._config, requestOptions);
  }
  /**
   * Creates a mapping between an LDAP group distinguished name and a team. Supply the `dn` and `team` fields in the JSON body; you need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission. A successful response includes the mapping's UUID.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
   */
  addMapping1(
    params: AddMapping1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addMapping1> {
    return addMapping1(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  deleteMapping1(
    params: DeleteMapping1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteMapping1> {
    return deleteMapping1(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  retrieveGroups1(
    params: RetrieveLdapGroups1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof retrieveLdapGroups1> {
    return retrieveLdapGroups1(this._config, params, requestOptions);
  }
}
