// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateLicenseGroupRequest,
  LicenseGroupResponse,
  UpdateLicenseGroupRequest,
} from "../types/license-group";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateLength, validateUuid } from "../validation";

export interface GetLicenseGroupsParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 */
export async function getLicenseGroups(
  config: ClientConfig,
  { pageNumber, pageSize, offset, limit, sortName, sortOrder }: GetLicenseGroupsParams = {},
  requestOptions?: RequestOptions,
): Promise<LicenseGroupResponse[]> {
  const _resp = await sdkRequest<LicenseGroupResponse[]>({
    method: "GET",
    path: `/v1/licenseGroup`,
    operationId: "getLicenseGroups",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UpdateLicenseGroupParams = UpdateLicenseGroupRequest;

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
 *
 * @param name - New name of the license group
 * @param uuid - UUID of the license group to update
 */
export async function updateLicenseGroup(
  config: ClientConfig,
  { name, uuid }: UpdateLicenseGroupParams,
  requestOptions?: RequestOptions,
): Promise<LicenseGroupResponse> {
  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<LicenseGroupResponse>({
    method: "POST",
    path: `/v1/licenseGroup`,
    operationId: "updateLicenseGroup",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      uuid,
    },
    config,
  });
  return _resp.data;
}

export type CreateLicenseGroupParams = CreateLicenseGroupRequest;

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_CREATE
 *
 * @param name - Name of the license group
 */
export async function createLicenseGroup(
  config: ClientConfig,
  { name }: CreateLicenseGroupParams,
  requestOptions?: RequestOptions,
): Promise<LicenseGroupResponse> {
  validateLength("name", name, { min: 1, max: 255 });

  const _resp = await sdkRequest<LicenseGroupResponse>({
    method: "PUT",
    path: `/v1/licenseGroup`,
    operationId: "createLicenseGroup",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteLicenseGroupParams {
  uuid: string;
}

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the license group to delete
 */
export async function deleteLicenseGroup(
  config: ClientConfig,
  { uuid }: DeleteLicenseGroupParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/licenseGroup/${encodePathSegment(uuid)}`,
    operationId: "deleteLicenseGroup",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface GetLicenseGroupParams {
  uuid: string;
}

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
 *
 * @param uuid - The UUID of the license group to retrieve
 */
export async function getLicenseGroup(
  config: ClientConfig,
  { uuid }: GetLicenseGroupParams,
  requestOptions?: RequestOptions,
): Promise<LicenseGroupResponse> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<LicenseGroupResponse>({
    method: "GET",
    path: `/v1/licenseGroup/${encodePathSegment(uuid)}`,
    operationId: "getLicenseGroup",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface RemoveLicenseFromLicenseGroupParams {
  uuid: string;
  licenseUuid: string;
}

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
 *
 * @param uuid - A valid license group
 * @param licenseUuid - A valid license
 */
export async function removeLicenseFromLicenseGroup(
  config: ClientConfig,
  { uuid, licenseUuid }: RemoveLicenseFromLicenseGroupParams,
  requestOptions?: RequestOptions,
): Promise<LicenseGroupResponse> {
  validateUuid("uuid", uuid);

  validateUuid("licenseUuid", licenseUuid);

  const _resp = await sdkRequest<LicenseGroupResponse>({
    method: "DELETE",
    path: `/v1/licenseGroup/${encodePathSegment(uuid)}/license/${encodePathSegment(licenseUuid)}`,
    operationId: "removeLicenseFromLicenseGroup",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface AddLicenseToLicenseGroupParams {
  uuid: string;
  licenseUuid: string;
}

/**
 * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
 *
 * @param uuid - A valid license group
 * @param licenseUuid - A valid license
 */
export async function addLicenseToLicenseGroup(
  config: ClientConfig,
  { uuid, licenseUuid }: AddLicenseToLicenseGroupParams,
  requestOptions?: RequestOptions,
): Promise<LicenseGroupResponse> {
  validateUuid("uuid", uuid);

  validateUuid("licenseUuid", licenseUuid);

  const _resp = await sdkRequest<LicenseGroupResponse>({
    method: "POST",
    path: `/v1/licenseGroup/${encodePathSegment(uuid)}/license/${encodePathSegment(licenseUuid)}`,
    operationId: "addLicenseToLicenseGroup",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class LicenseGroupNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
   */
  get(
    params: GetLicenseGroupsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getLicenseGroups> {
    return getLicenseGroups(this._config, params, requestOptions);
  }
  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
   */
  update(
    params: UpdateLicenseGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateLicenseGroup> {
    return updateLicenseGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_CREATE
   */
  create(
    params: CreateLicenseGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createLicenseGroup> {
    return createLicenseGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_DELETE
   */
  delete_(
    params: DeleteLicenseGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteLicenseGroup> {
    return deleteLicenseGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_READ
   */
  getLicenseGroup(
    params: GetLicenseGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getLicenseGroup> {
    return getLicenseGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
   */
  removeLicenseFrom(
    params: RemoveLicenseFromLicenseGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof removeLicenseFromLicenseGroup> {
    return removeLicenseFromLicenseGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission POLICY_MANAGEMENT or POLICY_MANAGEMENT_UPDATE
   */
  addLicenseTo(
    params: AddLicenseToLicenseGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addLicenseToLicenseGroup> {
    return addLicenseToLicenseGroup(this._config, params, requestOptions);
  }
}
