// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ConciseLicenseResponse, CreateLicenseRequest, LicenseResponse } from "../types/license";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateLength, validatePattern } from "../validation";

export interface GetLicensesParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Lists licenses with their complete metadata, including license text, identifiers, approval flags, and associated license groups. Use `pageNumber` and `pageSize` or `offset` and `limit` to control which licenses are returned.
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 */
export async function getLicenses(
  config: ClientConfig,
  { pageNumber, pageSize, offset, limit, sortName, sortOrder }: GetLicensesParams = {},
  requestOptions?: RequestOptions,
): Promise<LicenseResponse[]> {
  const _resp = await sdkRequest<LicenseResponse[]>({
    method: "GET",
    path: `/v1/license`,
    operationId: "getLicenses",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type CreateLicenseParams = CreateLicenseRequest;

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
 *
 * @param licenseId - Identifier of the license
 * @param name - Display name of the license
 * @param isDeprecatedLicenseId - Whether the licenseId has been deprecated by
 *   SPDX
 * @param isFsfLibre - Whether the license is FSF libre
 * @param isOsiApproved - Whether the license is approved by the OSI
 * @param licenseComments - Comments about the license
 * @param licenseText - Full license text
 * @param seeAlso - Additional URLs with information about the license
 * @param standardLicenseHeader - Standard license header typically added to the
 *   top of source code
 * @param standardLicenseTemplate - Standard license template used to derive the
 *   license text
 */
export async function createLicense(
  config: ClientConfig,
  {
    licenseId,
    name,
    isDeprecatedLicenseId,
    isFsfLibre,
    isOsiApproved,
    licenseComments,
    licenseText,
    seeAlso,
    standardLicenseHeader,
    standardLicenseTemplate,
  }: CreateLicenseParams,
  requestOptions?: RequestOptions,
): Promise<LicenseResponse> {
  validateLength("licenseId", licenseId, { min: 1, max: 255 });
  validatePattern("licenseId", licenseId, "^[a-zA-Z0-9_.\\-+]*$");

  validateLength("name", name, { min: 1, max: 255 });

  const _resp = await sdkRequest<LicenseResponse>({
    method: "PUT",
    path: `/v1/license`,
    operationId: "createLicense",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      licenseId,
      name,
      isDeprecatedLicenseId,
      isFsfLibre,
      isOsiApproved,
      licenseComments,
      licenseText,
      seeAlso,
      standardLicenseHeader,
      standardLicenseTemplate,
    },
    config,
  });
  return _resp.data;
}

/**
 * Lists concise records for all licenses available through the license catalogue. Use this endpoint when you need license identifiers, display names, and classification flags without retrieving full license text.
 */
export async function getLicenseListing(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<ConciseLicenseResponse[]> {
  const _resp = await sdkRequest<ConciseLicenseResponse[]>({
    method: "GET",
    path: `/v1/license/concise`,
    operationId: "getLicenseListing",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface DeleteLicenseParams {
  licenseId: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
 *
 * @param licenseId - The SPDX License ID of the license to delete
 */
export async function deleteLicense(
  config: ClientConfig,
  { licenseId }: DeleteLicenseParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/license/${encodePathSegment(licenseId)}`,
    operationId: "deleteLicense",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface GetLicenseParams {
  licenseId: string;
}

/**
 * Retrieves the details for a specific license identified by its SPDX License ID. Use `licenseId` to select the license; the response includes license text, comments, related license groups, and reference URLs when available.
 *
 * @param licenseId - The SPDX License ID of the license to retrieve
 */
export async function getLicense(
  config: ClientConfig,
  { licenseId }: GetLicenseParams,
  requestOptions?: RequestOptions,
): Promise<LicenseResponse> {
  const _resp = await sdkRequest<LicenseResponse>({
    method: "GET",
    path: `/v1/license/${encodePathSegment(licenseId)}`,
    operationId: "getLicense",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class LicenseNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists licenses with their complete metadata, including license text, identifiers, approval flags, and associated license groups. Use `pageNumber` and `pageSize` or `offset` and `limit` to control which licenses are returned.
   */
  get(
    params: GetLicensesParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getLicenses> {
    return getLicenses(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
   */
  create(
    params: CreateLicenseParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createLicense> {
    return createLicense(this._config, params, requestOptions);
  }
  /**
   * Lists concise records for all licenses available through the license catalogue. Use this endpoint when you need license identifiers, display names, and classification flags without retrieving full license text.
   */
  getListing(requestOptions?: RequestOptions): ReturnType<typeof getLicenseListing> {
    return getLicenseListing(this._config, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
   */
  delete_(
    params: DeleteLicenseParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteLicense> {
    return deleteLicense(this._config, params, requestOptions);
  }
  /**
   * Retrieves the details for a specific license identified by its SPDX License ID. Use `licenseId` to select the license; the response includes license text, comments, related license groups, and reference URLs when available.
   */
  getLicense(
    params: GetLicenseParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getLicense> {
    return getLicense(this._config, params, requestOptions);
  }
}
