// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { DependencyMetrics, ProblemDetails } from "../types/shared";
import { PortfolioMetrics, VulnerabilityMetrics } from "../types/metrics";
import { ProjectMetrics } from "../types/shared-project";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateRange, validateUuid } from "../validation";

export type GetComponentCurrentMetricsError = ProblemDetails;

export interface GetComponentCurrentMetricsParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the component to retrieve metrics for
 */
export async function getComponentCurrentMetrics(
  config: ClientConfig,
  { uuid }: GetComponentCurrentMetricsParams,
  requestOptions?: RequestOptions,
): Promise<DependencyMetrics> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<DependencyMetrics>({
    method: "GET",
    path: `/v1/metrics/component/${encodePathSegment(uuid)}/current`,
    operationId: "getComponentCurrentMetrics",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type GetComponentMetricsXDaysError = ProblemDetails;

export interface GetComponentMetricsXDaysParams {
  uuid: string;
  days: number;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the component to retrieve metrics for
 * @param days - The number of days back to retrieve metrics for
 */
export async function getComponentMetricsXDays(
  config: ClientConfig,
  { uuid, days }: GetComponentMetricsXDaysParams,
  requestOptions?: RequestOptions,
): Promise<DependencyMetrics[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<DependencyMetrics[]>({
    method: "GET",
    path: `/v1/metrics/component/${encodePathSegment(uuid)}/days/${encodePathSegment(days)}`,
    operationId: "getComponentMetricsXDays",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type RefreshComponentMetricsError = ProblemDetails;

export interface RefreshComponentMetricsParams {
  uuid: string;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param uuid - The UUID of the component to refresh metrics on
 */
export async function refreshComponentMetrics(
  config: ClientConfig,
  { uuid }: RefreshComponentMetricsParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "GET",
    path: `/v1/metrics/component/${encodePathSegment(uuid)}/refresh`,
    operationId: "refreshComponentMetrics",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type GetComponentMetricsSinceError = ProblemDetails;

export interface GetComponentMetricsSinceParams {
  uuid: string;
  date: string;
}

/**
 * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the component to retrieve metrics for
 * @param date - The start date (UTC) to retrieve metrics for
 */
export async function getComponentMetricsSince(
  config: ClientConfig,
  { uuid, date }: GetComponentMetricsSinceParams,
  requestOptions?: RequestOptions,
): Promise<DependencyMetrics[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<DependencyMetrics[]>({
    method: "GET",
    path: `/v1/metrics/component/${encodePathSegment(uuid)}/since/${encodePathSegment(date)}`,
    operationId: "getComponentMetricsSince",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Requires permission VIEW_PORTFOLIO
 */
export async function getPortfolioCurrentMetrics(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<PortfolioMetrics> {
  const _resp = await sdkRequest<PortfolioMetrics>({
    method: "GET",
    path: `/v1/metrics/portfolio/current`,
    operationId: "getPortfolioCurrentMetrics",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 */
export async function refreshPortfolioMetrics(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "GET",
    path: `/v1/metrics/portfolio/refresh`,
    operationId: "refreshPortfolioMetrics",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface GetPortfolioMetricsSinceParams {
  date: string;
}

/**
 * Date format must be YYYYMMDD . The number of days returned is computed against the current UTC date. Requires permission VIEW_PORTFOLIO
 *
 * @param date - The start date to retrieve metrics for
 */
export async function getPortfolioMetricsSince(
  config: ClientConfig,
  { date }: GetPortfolioMetricsSinceParams,
  requestOptions?: RequestOptions,
): Promise<PortfolioMetrics[]> {
  const _resp = await sdkRequest<PortfolioMetrics[]>({
    method: "GET",
    path: `/v1/metrics/portfolio/since/${encodePathSegment(date)}`,
    operationId: "getPortfolioMetricsSince",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GetPortfolioMetricsXDaysParams {
  days: number;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param days - The number of days back to retrieve metrics for
 */
export async function getPortfolioMetricsXDays(
  config: ClientConfig,
  { days }: GetPortfolioMetricsXDaysParams,
  requestOptions?: RequestOptions,
): Promise<PortfolioMetrics[]> {
  validateRange("days", days, { exclusiveMin: 0 });

  const _resp = await sdkRequest<PortfolioMetrics[]>({
    method: "GET",
    path: `/v1/metrics/portfolio/${encodePathSegment(days)}/days`,
    operationId: "getPortfolioMetricsXDays",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type GetProjectCurrentMetricsError = ProblemDetails;

export interface GetProjectCurrentMetricsParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project to retrieve metrics for
 */
export async function getProjectCurrentMetrics(
  config: ClientConfig,
  { uuid }: GetProjectCurrentMetricsParams,
  requestOptions?: RequestOptions,
): Promise<ProjectMetrics> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ProjectMetrics>({
    method: "GET",
    path: `/v1/metrics/project/${encodePathSegment(uuid)}/current`,
    operationId: "getProjectCurrentMetrics",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type GetProjectMetricsXDaysError = ProblemDetails;

export interface GetProjectMetricsXDaysParams {
  uuid: string;
  days: number;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project to retrieve metrics for
 * @param days - The number of days back to retrieve metrics for
 */
export async function getProjectMetricsXDays(
  config: ClientConfig,
  { uuid, days }: GetProjectMetricsXDaysParams,
  requestOptions?: RequestOptions,
): Promise<ProjectMetrics[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ProjectMetrics[]>({
    method: "GET",
    path: `/v1/metrics/project/${encodePathSegment(uuid)}/days/${encodePathSegment(days)}`,
    operationId: "getProjectMetricsXDays",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type RefreshProjectMetricsError = ProblemDetails;

export interface RefreshProjectMetricsParams {
  uuid: string;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param uuid - The UUID of the project to refresh metrics on
 */
export async function refreshProjectMetrics(
  config: ClientConfig,
  { uuid }: RefreshProjectMetricsParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "GET",
    path: `/v1/metrics/project/${encodePathSegment(uuid)}/refresh`,
    operationId: "refreshProjectMetrics",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type GetProjectMetricsSinceError = ProblemDetails;

export interface GetProjectMetricsSinceParams {
  uuid: string;
  date: string;
}

/**
 * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project to retrieve metrics for
 * @param date - The start date (UTC) to retrieve metrics for
 */
export async function getProjectMetricsSince(
  config: ClientConfig,
  { uuid, date }: GetProjectMetricsSinceParams,
  requestOptions?: RequestOptions,
): Promise<ProjectMetrics[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ProjectMetrics[]>({
    method: "GET",
    path: `/v1/metrics/project/${encodePathSegment(uuid)}/since/${encodePathSegment(date)}`,
    operationId: "getProjectMetricsSince",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Requires permission VIEW_PORTFOLIO
 */
export async function getVulnerabilityMetrics(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<VulnerabilityMetrics[]> {
  const _resp = await sdkRequest<VulnerabilityMetrics[]>({
    method: "GET",
    path: `/v1/metrics/vulnerability`,
    operationId: "getVulnerabilityMetrics",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class MetricsNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getComponentCurrent(
    params: GetComponentCurrentMetricsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getComponentCurrentMetrics> {
    return getComponentCurrentMetrics(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getComponentXDays(
    params: GetComponentMetricsXDaysParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getComponentMetricsXDays> {
    return getComponentMetricsXDays(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  refreshComponent(
    params: RefreshComponentMetricsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof refreshComponentMetrics> {
    return refreshComponentMetrics(this._config, params, requestOptions);
  }
  /**
   * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
   */
  getComponentSince(
    params: GetComponentMetricsSinceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getComponentMetricsSince> {
    return getComponentMetricsSince(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getPortfolioCurrent(
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getPortfolioCurrentMetrics> {
    return getPortfolioCurrentMetrics(this._config, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  refreshPortfolio(requestOptions?: RequestOptions): ReturnType<typeof refreshPortfolioMetrics> {
    return refreshPortfolioMetrics(this._config, requestOptions);
  }
  /**
   * Date format must be YYYYMMDD . The number of days returned is computed against the current UTC date. Requires permission VIEW_PORTFOLIO
   */
  getPortfolioSince(
    params: GetPortfolioMetricsSinceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getPortfolioMetricsSince> {
    return getPortfolioMetricsSince(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getPortfolioXDays(
    params: GetPortfolioMetricsXDaysParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getPortfolioMetricsXDays> {
    return getPortfolioMetricsXDays(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getProjectCurrent(
    params: GetProjectCurrentMetricsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectCurrentMetrics> {
    return getProjectCurrentMetrics(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getProjectXDays(
    params: GetProjectMetricsXDaysParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectMetricsXDays> {
    return getProjectMetricsXDays(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  refreshProject(
    params: RefreshProjectMetricsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof refreshProjectMetrics> {
    return refreshProjectMetrics(this._config, params, requestOptions);
  }
  /**
   * Date format must be YYYYMMDD . The date is interpreted as UTC midnight. Requires permission VIEW_PORTFOLIO
   */
  getProjectSince(
    params: GetProjectMetricsSinceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectMetricsSince> {
    return getProjectMetricsSince(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getVulnerability(requestOptions?: RequestOptions): ReturnType<typeof getVulnerabilityMetrics> {
    return getVulnerabilityMetrics(this._config, requestOptions);
  }
}
