// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateNotificationPublisherRequest,
  CreateNotificationRuleRequest,
  CreateScheduledNotificationRuleRequest,
  DeleteNotificationRuleRequest,
  InvalidNotificationFilterExpressionProblemDetails,
  NotificationPublisherResponse,
  NotificationRule,
  UpdateNotificationPublisherRequest,
  UpdateNotificationRuleRequest,
} from "../types/notification";
import { ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest } from "../client";
import { validateLength, validateUuid } from "../validation";

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
 */
export async function getAllNotificationPublishers(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<NotificationPublisherResponse[]> {
  const _resp = await sdkRequest<NotificationPublisherResponse[]>({
    method: "GET",
    path: `/v1/notification/publisher`,
    operationId: "getAllNotificationPublishers",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateNotificationPublisherParams = UpdateNotificationPublisherRequest;

/**
 * Updates an existing notification publisher, including its extension, name, description, and notification template. Supply `extensionName`, `name`, and `uuid`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission. A 200 response returns the updated notification publisher.
 *
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
 *
 * @param extensionName - Required `string` value serialized in the
 *   `extensionName` wire field.
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param template - Optional `string` value serialized in the `template` wire
 *   field.
 * @param templateMimeType - Optional `string` value serialized in the
 *   `templateMimeType` wire field.
 */
export async function updateNotificationPublisher(
  config: ClientConfig,
  {
    extensionName,
    name,
    uuid,
    description,
    template,
    templateMimeType,
  }: UpdateNotificationPublisherParams,
  requestOptions?: RequestOptions,
): Promise<NotificationPublisherResponse> {
  validateLength("extensionName", extensionName, { min: 1 });

  validateLength("name", name, { min: 1 });

  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<NotificationPublisherResponse>({
    method: "POST",
    path: `/v1/notification/publisher`,
    operationId: "updateNotificationPublisher",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      extensionName,
      name,
      uuid,
      description,
      template,
      templateMimeType,
    },
    config,
  });
  return _resp.data;
}

export type CreateNotificationPublisherParams = CreateNotificationPublisherRequest;

/**
 * Creates a new notification publisher with its extension, name, and optional template details. Supply `extensionName` and `name`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission. A 201 response returns the created notification publisher with its generated UUID.
 *
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
 *
 * @param extensionName - Required `string` value serialized in the
 *   `extensionName` wire field.
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param template - Optional `string` value serialized in the `template` wire
 *   field.
 * @param templateMimeType - Optional `string` value serialized in the
 *   `templateMimeType` wire field.
 */
export async function createNotificationPublisher(
  config: ClientConfig,
  {
    extensionName,
    name,
    description,
    template,
    templateMimeType,
  }: CreateNotificationPublisherParams,
  requestOptions?: RequestOptions,
): Promise<NotificationPublisherResponse> {
  validateLength("extensionName", extensionName, { min: 1 });

  validateLength("name", name, { min: 1 });

  const _resp = await sdkRequest<NotificationPublisherResponse>({
    method: "PUT",
    path: `/v1/notification/publisher`,
    operationId: "createNotificationPublisher",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      extensionName,
      name,
      description,
      template,
      templateMimeType,
    },
    config,
  });
  return _resp.data;
}

export interface TestNotificationRuleParams {
  uuid: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION
 *
 * @param uuid - The UUID of the rule to test
 */
export async function testNotificationRule(
  config: ClientConfig,
  { uuid }: TestNotificationRuleParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/v1/notification/publisher/test/${encodePathSegment(uuid)}`,
    operationId: "testNotificationRule",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface DeleteNotificationPublisherParams {
  notificationPublisherUuid: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
 *
 * @param notificationPublisherUuid - The UUID of the notification publisher to
 *   delete
 */
export async function deleteNotificationPublisher(
  config: ClientConfig,
  { notificationPublisherUuid }: DeleteNotificationPublisherParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("notificationPublisherUuid", notificationPublisherUuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/notification/publisher/${encodePathSegment(notificationPublisherUuid)}`,
    operationId: "deleteNotificationPublisher",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface GetNotificationPublisherConfigSchemaParams {
  uuid: string;
}

/**
 * Retrieves the configuration schema for a notification publisher. Use this operation to determine the configuration fields supported by the publisher; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_READ` permission.
 *
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
 */
export async function getNotificationPublisherConfigSchema(
  config: ClientConfig,
  { uuid }: GetNotificationPublisherConfigSchemaParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<string>({
    method: "GET",
    path: `/v1/notification/publisher/${encodePathSegment(uuid)}/configSchema`,
    operationId: "getNotificationPublisherConfigSchema",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type DeleteNotificationRuleParams = DeleteNotificationRuleRequest;

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
 *
 * @param uuid - UUID of the notification rule to delete
 */
export async function deleteNotificationRule(
  config: ClientConfig,
  { uuid }: DeleteNotificationRuleParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/notification/rule`,
    operationId: "deleteNotificationRule",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      uuid,
    },
    config,
  });
  void _resp.data;
  return;
}

export interface GetAllNotificationRulesParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  triggerType?: "EVENT" | "SCHEDULE" | (string & {});
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param triggerType - The notification trigger type to filter on
 */
export async function getAllNotificationRules(
  config: ClientConfig,
  {
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    triggerType,
  }: GetAllNotificationRulesParams = {},
  requestOptions?: RequestOptions,
): Promise<NotificationRule[]> {
  const _resp = await sdkRequest<NotificationRule[]>({
    method: "GET",
    path: `/v1/notification/rule`,
    operationId: "getAllNotificationRules",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      triggerType: queryValue(triggerType, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule[];
}

export type UpdateNotificationRuleError = InvalidNotificationFilterExpressionProblemDetails;

export type UpdateNotificationRuleParams = UpdateNotificationRuleRequest;

/**
 * Updates an existing notification rule using its UUID. Supply `uuid`, `name`, `level`, and `scope`, and include optional notification, filtering, publisher, or scheduling settings as needed. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission.
 *
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
 *
 * @param level - Required enumerated value serialized in the `level` wire field.
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param scope - Required enumerated value serialized in the `scope` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param enabled - Optional `boolean` value serialized in the `enabled` wire
 *   field.
 * @param filterExpression - Optional `string` value serialized in the
 *   `filterExpression` wire field.
 * @param logSuccessfulPublish - Optional `boolean` value serialized in the
 *   `logSuccessfulPublish` wire field.
 * @param notifyChildren - Optional `boolean` value serialized in the
 *   `notifyChildren` wire field.
 * @param notifyOn - Optional array value serialized in the `notifyOn` wire
 *   field.
 * @param publisherConfig - Optional `string` value serialized in the
 *   `publisherConfig` wire field.
 * @param scheduleCron - Optional `string` value serialized in the `scheduleCron`
 *   wire field.
 * @param scheduleSkipUnchanged - Optional `boolean` value serialized in the
 *   `scheduleSkipUnchanged` wire field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 */
export async function updateNotificationRule(
  config: ClientConfig,
  {
    level,
    name,
    scope,
    uuid,
    enabled,
    filterExpression,
    logSuccessfulPublish,
    notifyChildren,
    notifyOn,
    publisherConfig,
    scheduleCron,
    scheduleSkipUnchanged,
    tags,
  }: UpdateNotificationRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateLength("name", name, { min: 1 });

  validateUuid("uuid", uuid);

  if (filterExpression != null) {
    validateLength("filterExpression", filterExpression, { min: 0, max: 2048 });
  }

  const _resp = await sdkRequest<NotificationRule>({
    method: "POST",
    path: `/v1/notification/rule`,
    operationId: "updateNotificationRule",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      level,
      name,
      scope,
      uuid,
      enabled,
      filterExpression,
      logSuccessfulPublish,
      notifyChildren,
      notifyOn,
      publisherConfig,
      scheduleCron,
      scheduleSkipUnchanged,
      tags,
    },
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export type CreateNotificationRuleParams = CreateNotificationRuleRequest;

/**
 * Creates a new notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
 *
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
 *
 * @param level - Required enumerated value serialized in the `level` wire field.
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param publisher - Required object value serialized in the `publisher` wire
 *   field.
 * @param scope - Required enumerated value serialized in the `scope` wire field.
 */
export async function createNotificationRule(
  config: ClientConfig,
  { level, name, publisher, scope }: CreateNotificationRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateLength("name", name, { min: 1 });

  const _resp = await sdkRequest<NotificationRule>({
    method: "PUT",
    path: `/v1/notification/rule`,
    operationId: "createNotificationRule",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      level,
      name,
      publisher,
      scope,
    },
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export type CreateScheduledNotificationRuleParams = CreateScheduledNotificationRuleRequest;

/**
 * Creates a new scheduled notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID; `name` must contain 1 to 255 characters matching the allowed character pattern. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
 *
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
 *
 * @param level - Required enumerated value serialized in the `level` wire field.
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param publisher - Required object value serialized in the `publisher` wire
 *   field.
 * @param scope - Required enumerated value serialized in the `scope` wire field.
 */
export async function createScheduledNotificationRule(
  config: ClientConfig,
  { level, name, publisher, scope }: CreateScheduledNotificationRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateLength("name", name, { min: 1, max: 255 });

  const _resp = await sdkRequest<NotificationRule>({
    method: "PUT",
    path: `/v1/notification/rule/scheduled`,
    operationId: "createScheduledNotificationRule",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      level,
      name,
      publisher,
      scope,
    },
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export type RemoveProjectFromRuleError = ProblemDetails;

export interface RemoveProjectFromRuleParams {
  ruleUuid: string;
  projectUuid: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
 *
 * @param ruleUuid - The UUID of the rule to remove the project from
 * @param projectUuid - The UUID of the project to remove from the rule
 */
export async function removeProjectFromRule(
  config: ClientConfig,
  { ruleUuid, projectUuid }: RemoveProjectFromRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateUuid("ruleUuid", ruleUuid);

  validateUuid("projectUuid", projectUuid);

  const _resp = await sdkRequest<NotificationRule>({
    method: "DELETE",
    path: `/v1/notification/rule/${encodePathSegment(ruleUuid)}/project/${encodePathSegment(projectUuid)}`,
    operationId: "removeProjectFromRule",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export type AddProjectToRuleError = ProblemDetails;

export interface AddProjectToRuleParams {
  ruleUuid: string;
  projectUuid: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
 *
 * @param ruleUuid - The UUID of the rule to add a project to
 * @param projectUuid - The UUID of the project to add to the rule
 */
export async function addProjectToRule(
  config: ClientConfig,
  { ruleUuid, projectUuid }: AddProjectToRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateUuid("ruleUuid", ruleUuid);

  validateUuid("projectUuid", projectUuid);

  const _resp = await sdkRequest<NotificationRule>({
    method: "POST",
    path: `/v1/notification/rule/${encodePathSegment(ruleUuid)}/project/${encodePathSegment(projectUuid)}`,
    operationId: "addProjectToRule",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export interface RemoveTeamFromRuleParams {
  ruleUuid: string;
  teamUuid: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
 *
 * @param ruleUuid - The UUID of the rule to remove the project from
 * @param teamUuid - The UUID of the project to remove from the rule
 */
export async function removeTeamFromRule(
  config: ClientConfig,
  { ruleUuid, teamUuid }: RemoveTeamFromRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateUuid("ruleUuid", ruleUuid);

  validateUuid("teamUuid", teamUuid);

  const _resp = await sdkRequest<NotificationRule>({
    method: "DELETE",
    path: `/v1/notification/rule/${encodePathSegment(ruleUuid)}/team/${encodePathSegment(teamUuid)}`,
    operationId: "removeTeamFromRule",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export interface AddTeamToRuleParams {
  ruleUuid: string;
  teamUuid: string;
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
 *
 * @param ruleUuid - The UUID of the rule to add a team to
 * @param teamUuid - The UUID of the team to add to the rule
 */
export async function addTeamToRule(
  config: ClientConfig,
  { ruleUuid, teamUuid }: AddTeamToRuleParams,
  requestOptions?: RequestOptions,
): Promise<NotificationRule> {
  validateUuid("ruleUuid", ruleUuid);

  validateUuid("teamUuid", teamUuid);

  const _resp = await sdkRequest<NotificationRule>({
    method: "POST",
    path: `/v1/notification/rule/${encodePathSegment(ruleUuid)}/team/${encodePathSegment(teamUuid)}`,
    operationId: "addTeamToRule",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "NotificationRule") as NotificationRule;
}

export class NotificationNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
   */
  getAllPublishers(
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getAllNotificationPublishers> {
    return getAllNotificationPublishers(this._config, requestOptions);
  }
  /**
   * Updates an existing notification publisher, including its extension, name, description, and notification template. Supply `extensionName`, `name`, and `uuid`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission. A 200 response returns the updated notification publisher.
   *
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
   */
  updatePublisher(
    params: UpdateNotificationPublisherParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateNotificationPublisher> {
    return updateNotificationPublisher(this._config, params, requestOptions);
  }
  /**
   * Creates a new notification publisher with its extension, name, and optional template details. Supply `extensionName` and `name`; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission. A 201 response returns the created notification publisher with its generated UUID.
   *
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
   */
  createPublisher(
    params: CreateNotificationPublisherParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createNotificationPublisher> {
    return createNotificationPublisher(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION
   */
  testRule(
    params: TestNotificationRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof testNotificationRule> {
    return testNotificationRule(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
   */
  deletePublisher(
    params: DeleteNotificationPublisherParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteNotificationPublisher> {
    return deleteNotificationPublisher(this._config, params, requestOptions);
  }
  /**
   * Retrieves the configuration schema for a notification publisher. Use this operation to determine the configuration fields supported by the publisher; the authenticated user needs `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_READ` permission.
   *
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
   */
  getPublisherConfigSchema(
    params: GetNotificationPublisherConfigSchemaParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getNotificationPublisherConfigSchema> {
    return getNotificationPublisherConfigSchema(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
   */
  deleteRule(
    params: DeleteNotificationRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteNotificationRule> {
    return deleteNotificationRule(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
   */
  getAllRules(
    params: GetAllNotificationRulesParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getAllNotificationRules> {
    return getAllNotificationRules(this._config, params, requestOptions);
  }
  /**
   * Updates an existing notification rule using its UUID. Supply `uuid`, `name`, `level`, and `scope`, and include optional notification, filtering, publisher, or scheduling settings as needed. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_UPDATE` permission.
   *
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
   */
  updateRule(
    params: UpdateNotificationRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateNotificationRule> {
    return updateNotificationRule(this._config, params, requestOptions);
  }
  /**
   * Creates a new notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
   *
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
   */
  createRule(
    params: CreateNotificationRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createNotificationRule> {
    return createNotificationRule(this._config, params, requestOptions);
  }
  /**
   * Creates a new scheduled notification rule. Supply `level`, `name`, `publisher`, and `scope`, with the publisher identified by its UUID; `name` must contain 1 to 255 characters matching the allowed character pattern. You need `SYSTEM_CONFIGURATION` or `SYSTEM_CONFIGURATION_CREATE` permission.
   *
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_CREATE
   */
  createScheduledRule(
    params: CreateScheduledNotificationRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createScheduledNotificationRule> {
    return createScheduledNotificationRule(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
   */
  removeProjectFromRule(
    params: RemoveProjectFromRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof removeProjectFromRule> {
    return removeProjectFromRule(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
   */
  addProjectToRule(
    params: AddProjectToRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addProjectToRule> {
    return addProjectToRule(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_DELETE
   */
  removeTeamFromRule(
    params: RemoveTeamFromRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof removeTeamFromRule> {
    return removeTeamFromRule(this._config, params, requestOptions);
  }
  /**
   * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_UPDATE
   */
  addTeamToRule(
    params: AddTeamToRuleParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addTeamToRule> {
    return addTeamToRule(this._config, params, requestOptions);
  }
}
