// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateOidcGroupRequest,
  MappedOidcGroupRequest,
  MappedOidcGroupResponse,
  OidcGroupResponse,
  UpdateOidcGroupRequest,
} from "../types/oidc";
import { Team } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateLength, validatePattern, validateUuid } from "../validation";

/**
 * Reports whether OpenID Connect is available for the application. Use the boolean result to determine whether OpenID Connect is available before relying on it.
 */
export async function isAvailable(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<boolean> {
  const _resp = await sdkRequest<boolean>({
    method: "GET",
    path: `/v1/oidc/available`,
    operationId: "isAvailable",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 */
export async function retrieveGroups(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<OidcGroupResponse[]> {
  const _resp = await sdkRequest<OidcGroupResponse[]>({
    method: "GET",
    path: `/v1/oidc/group`,
    operationId: "retrieveGroups",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateGroupParams = UpdateOidcGroupRequest;

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param name - New name of the group
 * @param uuid - UUID of the group to update
 */
export async function updateGroup(
  config: ClientConfig,
  { name, uuid }: UpdateGroupParams,
  requestOptions?: RequestOptions,
): Promise<OidcGroupResponse> {
  validateLength("name", name, { min: 1, max: 255 });
  validatePattern("name", name, "[\\P{Cc}]+");

  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<OidcGroupResponse>({
    method: "POST",
    path: `/v1/oidc/group`,
    operationId: "updateGroup",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      uuid,
    },
    config,
  });
  return _resp.data;
}

export type CreateGroupParams = CreateOidcGroupRequest;

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param name - Name of the group to create
 */
export async function createGroup(
  config: ClientConfig,
  { name }: CreateGroupParams,
  requestOptions?: RequestOptions,
): Promise<OidcGroupResponse> {
  validateLength("name", name, { min: 1, max: 255 });
  validatePattern("name", name, "[\\P{Cc}]+");

  const _resp = await sdkRequest<OidcGroupResponse>({
    method: "PUT",
    path: `/v1/oidc/group`,
    operationId: "createGroup",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteMapping2Params {
  groupUuid: string;
  teamUuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param groupUuid - The UUID of the group to delete a mapping for
 * @param teamUuid - The UUID of the team to delete a mapping for
 */
export async function deleteMapping2(
  config: ClientConfig,
  { groupUuid, teamUuid }: DeleteMapping2Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("groupUuid", groupUuid);

  validateUuid("teamUuid", teamUuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/oidc/group/${encodePathSegment(groupUuid)}/team/${encodePathSegment(teamUuid)}/mapping`,
    operationId: "deleteMapping2",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface DeleteGroupParams {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the group to delete
 */
export async function deleteGroup(
  config: ClientConfig,
  { uuid }: DeleteGroupParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/oidc/group/${encodePathSegment(uuid)}`,
    operationId: "deleteGroup",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface RetrieveTeamsMappedToGroupParams {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 *
 * @param uuid - The UUID of the mapping to retrieve the team for
 */
export async function retrieveTeamsMappedToGroup(
  config: ClientConfig,
  { uuid }: RetrieveTeamsMappedToGroupParams,
  requestOptions?: RequestOptions,
): Promise<Team[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Team[]>({
    method: "GET",
    path: `/v1/oidc/group/${encodePathSegment(uuid)}/team`,
    operationId: "retrieveTeamsMappedToGroup",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type AddMapping2Params = MappedOidcGroupRequest;

/**
 * Creates a mapping between an OIDC group and a team. Supply `group` and `team` as UUID-formatted values to associate them. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param group - Required `string` value serialized in the `group` wire field.
 * @param team - Required `string` value serialized in the `team` wire field.
 */
export async function addMapping2(
  config: ClientConfig,
  { group, team }: AddMapping2Params,
  requestOptions?: RequestOptions,
): Promise<MappedOidcGroupResponse> {
  validatePattern("group", group, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

  validatePattern("team", team, "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");

  const _resp = await sdkRequest<MappedOidcGroupResponse>({
    method: "PUT",
    path: `/v1/oidc/mapping`,
    operationId: "addMapping2",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      group,
      team,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteMappingByUuidParams {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the mapping to delete
 */
export async function deleteMappingByUuid(
  config: ClientConfig,
  { uuid }: DeleteMappingByUuidParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/oidc/mapping/${encodePathSegment(uuid)}`,
    operationId: "deleteMappingByUuid",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export class OidcNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Reports whether OpenID Connect is available for the application. Use the boolean result to determine whether OpenID Connect is available before relying on it.
   */
  isAvailable(requestOptions?: RequestOptions): ReturnType<typeof isAvailable> {
    return isAvailable(this._config, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  retrieveGroups(requestOptions?: RequestOptions): ReturnType<typeof retrieveGroups> {
    return retrieveGroups(this._config, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  updateGroup(
    params: UpdateGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateGroup> {
    return updateGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
   */
  createGroup(
    params: CreateGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createGroup> {
    return createGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  deleteMapping2(
    params: DeleteMapping2Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteMapping2> {
    return deleteMapping2(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  deleteGroup(
    params: DeleteGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteGroup> {
    return deleteGroup(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  retrieveTeamsMappedToGroup(
    params: RetrieveTeamsMappedToGroupParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof retrieveTeamsMappedToGroup> {
    return retrieveTeamsMappedToGroup(this._config, params, requestOptions);
  }
  /**
   * Creates a mapping between an OIDC group and a team. Supply `group` and `team` as UUID-formatted values to associate them. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
   */
  addMapping2(
    params: AddMapping2Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addMapping2> {
    return addMapping2(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  deleteMappingByUuid(
    params: DeleteMappingByUuidParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteMappingByUuid> {
    return deleteMappingByUuid(this._config, params, requestOptions);
  }
}
