// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { TeamPermissionsSetRequest, UserPermissionsSetRequest } from "../types/permission";
import { Team, User } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateLength, validateUuid } from "../validation";

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 */
export async function getAllPermissions(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<
  | "BOM_UPLOAD"
  | "VIEW_PORTFOLIO"
  | "PORTFOLIO_ACCESS_CONTROL_BYPASS"
  | "PORTFOLIO_MANAGEMENT"
  | "PORTFOLIO_MANAGEMENT_CREATE"
  | "PORTFOLIO_MANAGEMENT_READ"
  | "PORTFOLIO_MANAGEMENT_UPDATE"
  | "PORTFOLIO_MANAGEMENT_DELETE"
  | "VIEW_VULNERABILITY"
  | "VULNERABILITY_ANALYSIS"
  | "VULNERABILITY_ANALYSIS_CREATE"
  | "VULNERABILITY_ANALYSIS_READ"
  | "VULNERABILITY_ANALYSIS_UPDATE"
  | "VIEW_POLICY_VIOLATION"
  | "VULNERABILITY_MANAGEMENT"
  | "VULNERABILITY_MANAGEMENT_CREATE"
  | "VULNERABILITY_MANAGEMENT_READ"
  | "VULNERABILITY_MANAGEMENT_UPDATE"
  | "VULNERABILITY_MANAGEMENT_DELETE"
  | "POLICY_VIOLATION_ANALYSIS"
  | "ACCESS_MANAGEMENT"
  | "ACCESS_MANAGEMENT_CREATE"
  | "ACCESS_MANAGEMENT_READ"
  | "ACCESS_MANAGEMENT_UPDATE"
  | "ACCESS_MANAGEMENT_DELETE"
  | "SECRET_MANAGEMENT"
  | "SECRET_MANAGEMENT_CREATE"
  | "SECRET_MANAGEMENT_UPDATE"
  | "SECRET_MANAGEMENT_DELETE"
  | "SYSTEM_CONFIGURATION"
  | "SYSTEM_CONFIGURATION_CREATE"
  | "SYSTEM_CONFIGURATION_READ"
  | "SYSTEM_CONFIGURATION_UPDATE"
  | "SYSTEM_CONFIGURATION_DELETE"
  | "PROJECT_CREATION_UPLOAD"
  | "POLICY_MANAGEMENT"
  | "POLICY_MANAGEMENT_CREATE"
  | "POLICY_MANAGEMENT_READ"
  | "POLICY_MANAGEMENT_UPDATE"
  | "POLICY_MANAGEMENT_DELETE"
  | "TAG_MANAGEMENT"
  | "TAG_MANAGEMENT_DELETE"
  | (string & {})
> {
  const _resp = await sdkRequest<
    | "BOM_UPLOAD"
    | "VIEW_PORTFOLIO"
    | "PORTFOLIO_ACCESS_CONTROL_BYPASS"
    | "PORTFOLIO_MANAGEMENT"
    | "PORTFOLIO_MANAGEMENT_CREATE"
    | "PORTFOLIO_MANAGEMENT_READ"
    | "PORTFOLIO_MANAGEMENT_UPDATE"
    | "PORTFOLIO_MANAGEMENT_DELETE"
    | "VIEW_VULNERABILITY"
    | "VULNERABILITY_ANALYSIS"
    | "VULNERABILITY_ANALYSIS_CREATE"
    | "VULNERABILITY_ANALYSIS_READ"
    | "VULNERABILITY_ANALYSIS_UPDATE"
    | "VIEW_POLICY_VIOLATION"
    | "VULNERABILITY_MANAGEMENT"
    | "VULNERABILITY_MANAGEMENT_CREATE"
    | "VULNERABILITY_MANAGEMENT_READ"
    | "VULNERABILITY_MANAGEMENT_UPDATE"
    | "VULNERABILITY_MANAGEMENT_DELETE"
    | "POLICY_VIOLATION_ANALYSIS"
    | "ACCESS_MANAGEMENT"
    | "ACCESS_MANAGEMENT_CREATE"
    | "ACCESS_MANAGEMENT_READ"
    | "ACCESS_MANAGEMENT_UPDATE"
    | "ACCESS_MANAGEMENT_DELETE"
    | "SECRET_MANAGEMENT"
    | "SECRET_MANAGEMENT_CREATE"
    | "SECRET_MANAGEMENT_UPDATE"
    | "SECRET_MANAGEMENT_DELETE"
    | "SYSTEM_CONFIGURATION"
    | "SYSTEM_CONFIGURATION_CREATE"
    | "SYSTEM_CONFIGURATION_READ"
    | "SYSTEM_CONFIGURATION_UPDATE"
    | "SYSTEM_CONFIGURATION_DELETE"
    | "PROJECT_CREATION_UPLOAD"
    | "POLICY_MANAGEMENT"
    | "POLICY_MANAGEMENT_CREATE"
    | "POLICY_MANAGEMENT_READ"
    | "POLICY_MANAGEMENT_UPDATE"
    | "POLICY_MANAGEMENT_DELETE"
    | "TAG_MANAGEMENT"
    | "TAG_MANAGEMENT_DELETE"
    | (string & {})
  >({
    method: "GET",
    path: `/v1/permission`,
    operationId: "getAllPermissions",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SetTeamPermissionsParams = TeamPermissionsSetRequest;

/**
 * Replaces a team's permissions with the supplied list. Provide `team` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param permissions - Required array value serialized in the `permissions` wire
 *   field.
 * @param team - Required `string` value serialized in the `team` wire field.
 */
export async function setTeamPermissions(
  config: ClientConfig,
  { permissions, team }: SetTeamPermissionsParams,
  requestOptions?: RequestOptions,
): Promise<Team> {
  validateLength("team", team, { min: 1 });

  const _resp = await sdkRequest<Team>({
    method: "PUT",
    path: `/v1/permission/team`,
    operationId: "setTeamPermissions",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      permissions,
      team,
    },
    config,
  });
  return _resp.data;
}

export type SetUserPermissionsParams = UserPermissionsSetRequest;

/**
 * Replaces a user's permissions with the supplied list. Provide `username` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param permissions - Required array value serialized in the `permissions` wire
 *   field.
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 */
export async function setUserPermissions(
  config: ClientConfig,
  { permissions, username }: SetUserPermissionsParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  validateLength("username", username, { min: 1 });

  const _resp = await sdkRequest<User>({
    method: "PUT",
    path: `/v1/permission/user`,
    operationId: "setUserPermissions",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      permissions,
      username,
    },
    config,
  });
  return _resp.data;
}

export interface RemovePermissionFromTeamParams {
  uuid: string;
  permission: string;
}

/**
 * Removes a permission from a team. Supply the team UUID in `uuid` and the permission to remove in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_DELETE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param uuid - A valid team uuid
 * @param permission - A valid permission
 */
export async function removePermissionFromTeam(
  config: ClientConfig,
  { uuid, permission }: RemovePermissionFromTeamParams,
  requestOptions?: RequestOptions,
): Promise<Team> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Team>({
    method: "DELETE",
    path: `/v1/permission/${encodePathSegment(permission)}/team/${encodePathSegment(uuid)}`,
    operationId: "removePermissionFromTeam",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface AddPermissionToTeamParams {
  uuid: string;
  permission: string;
}

/**
 * Adds a permission to a team. Supply the team UUID in `uuid` and a valid permission in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param uuid - A valid team uuid
 * @param permission - A valid permission
 */
export async function addPermissionToTeam(
  config: ClientConfig,
  { uuid, permission }: AddPermissionToTeamParams,
  requestOptions?: RequestOptions,
): Promise<Team> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Team>({
    method: "POST",
    path: `/v1/permission/${encodePathSegment(permission)}/team/${encodePathSegment(uuid)}`,
    operationId: "addPermissionToTeam",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface RemovePermissionFromUserParams {
  username: string;
  permission: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param username - A valid username
 * @param permission - A valid permission
 */
export async function removePermissionFromUser(
  config: ClientConfig,
  { username, permission }: RemovePermissionFromUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  const _resp = await sdkRequest<User>({
    method: "DELETE",
    path: `/v1/permission/${encodePathSegment(permission)}/user/${encodePathSegment(username)}`,
    operationId: "removePermissionFromUser",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface AddPermissionToUserParams {
  username: string;
  permission: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param username - A valid username
 * @param permission - A valid permission
 */
export async function addPermissionToUser(
  config: ClientConfig,
  { username, permission }: AddPermissionToUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  const _resp = await sdkRequest<User>({
    method: "POST",
    path: `/v1/permission/${encodePathSegment(permission)}/user/${encodePathSegment(username)}`,
    operationId: "addPermissionToUser",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class PermissionNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  getAll(requestOptions?: RequestOptions): ReturnType<typeof getAllPermissions> {
    return getAllPermissions(this._config, requestOptions);
  }
  /**
   * Replaces a team's permissions with the supplied list. Provide `team` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  setTeam(
    params: SetTeamPermissionsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setTeamPermissions> {
    return setTeamPermissions(this._config, params, requestOptions);
  }
  /**
   * Replaces a user's permissions with the supplied list. Provide `username` and `permissions`, using supported permission names without duplicates. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  setUser(
    params: SetUserPermissionsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setUserPermissions> {
    return setUserPermissions(this._config, params, requestOptions);
  }
  /**
   * Removes a permission from a team. Supply the team UUID in `uuid` and the permission to remove in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_DELETE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  removeFromTeam(
    params: RemovePermissionFromTeamParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof removePermissionFromTeam> {
    return removePermissionFromTeam(this._config, params, requestOptions);
  }
  /**
   * Adds a permission to a team. Supply the team UUID in `uuid` and a valid permission in `permission`. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  addToTeam(
    params: AddPermissionToTeamParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addPermissionToTeam> {
    return addPermissionToTeam(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  removeFromUser(
    params: RemovePermissionFromUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof removePermissionFromUser> {
    return removePermissionFromUser(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  addToUser(
    params: AddPermissionToUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof addPermissionToUser> {
    return addPermissionToUser(this._config, params, requestOptions);
  }
}
