// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateProjectPropertyRequest,
  DeleteProjectPropertyRequest,
  ProjectPropertyResponse,
  UpdateProjectPropertyRequest,
} from "../types/project-property";
import { ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, sdkRequest } from "../client";
import { validateLength, validatePattern, validateUuid } from "../validation";

export type DeleteProperty1Error = ProblemDetails;

export type DeleteProperty1Params = DeleteProjectPropertyRequest & {
  uuid: string;
};

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the project to delete a property from
 * @param groupName - Group the property belongs to
 * @param propertyName - Name of the property
 */
export async function deleteProperty1(
  config: ClientConfig,
  { uuid, groupName, propertyName }: DeleteProperty1Params,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  validateLength("groupName", groupName, { min: 1, max: 255 });
  validatePattern("groupName", groupName, "\\P{Cc}+");

  validateLength("propertyName", propertyName, { min: 1, max: 255 });
  validatePattern("propertyName", propertyName, "\\P{Cc}+");

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/project/${encodePathSegment(uuid)}/property`,
    operationId: "deleteProperty1",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      groupName,
      propertyName,
    },
    config,
  });
  void _resp.data;
  return;
}

export type GetProperties1Error = ProblemDetails;

export interface GetProperties1Params {
  uuid: string;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_READ
 *
 * @param uuid - The UUID of the project to retrieve properties for
 */
export async function getProperties1(
  config: ClientConfig,
  { uuid }: GetProperties1Params,
  requestOptions?: RequestOptions,
): Promise<ProjectPropertyResponse[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ProjectPropertyResponse[]>({
    method: "GET",
    path: `/v1/project/${encodePathSegment(uuid)}/property`,
    operationId: "getProperties1",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdatePropertyError = ProblemDetails;

export type UpdatePropertyParams = UpdateProjectPropertyRequest & {
  uuid: string;
};

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param uuid - The UUID of the project to create a property for
 * @param groupName - Group the property belongs to
 * @param propertyName - Name of the property
 * @param propertyValue - Value of the property
 */
export async function updateProperty(
  config: ClientConfig,
  { uuid, groupName, propertyName, propertyValue }: UpdatePropertyParams,
  requestOptions?: RequestOptions,
): Promise<ProjectPropertyResponse> {
  validateUuid("uuid", uuid);

  validateLength("groupName", groupName, { min: 1, max: 255 });
  validatePattern("groupName", groupName, "\\P{Cc}+");

  validateLength("propertyName", propertyName, { min: 1, max: 255 });
  validatePattern("propertyName", propertyName, "\\P{Cc}+");

  if (propertyValue != null) {
    validateLength("propertyValue", propertyValue, { min: 0, max: 1024 });
    validatePattern("propertyValue", propertyValue, "\\P{Cc}+");
  }

  const _resp = await sdkRequest<ProjectPropertyResponse>({
    method: "POST",
    path: `/v1/project/${encodePathSegment(uuid)}/property`,
    operationId: "updateProperty",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      groupName,
      propertyName,
      propertyValue,
    },
    config,
  });
  return _resp.data;
}

export type CreateProperty1Error = ProblemDetails;

export type CreateProperty1Params = CreateProjectPropertyRequest & {
  uuid: string;
};

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
 *
 * @param uuid - The UUID of the project to create a property for
 * @param groupName - Group the property belongs to
 * @param propertyName - Name of the property
 * @param propertyType - Type of the property
 * @param description - Description of the property
 * @param propertyValue - Value of the property
 */
export async function createProperty1(
  config: ClientConfig,
  {
    uuid,
    groupName,
    propertyName,
    propertyType,
    description,
    propertyValue,
  }: CreateProperty1Params,
  requestOptions?: RequestOptions,
): Promise<ProjectPropertyResponse> {
  validateUuid("uuid", uuid);

  validateLength("groupName", groupName, { min: 1, max: 255 });
  validatePattern("groupName", groupName, "\\P{Cc}+");

  validateLength("propertyName", propertyName, { min: 1, max: 255 });
  validatePattern("propertyName", propertyName, "\\P{Cc}+");

  if (description != null) {
    validateLength("description", description, { min: 0, max: 255 });
    validatePattern("description", description, "\\P{Cc}+");
  }

  if (propertyValue != null) {
    validateLength("propertyValue", propertyValue, { min: 0, max: 1024 });
    validatePattern("propertyValue", propertyValue, "\\P{Cc}+");
  }

  const _resp = await sdkRequest<ProjectPropertyResponse>({
    method: "PUT",
    path: `/v1/project/${encodePathSegment(uuid)}/property`,
    operationId: "createProperty1",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      groupName,
      propertyName,
      propertyType,
      description,
      propertyValue,
    },
    config,
  });
  return _resp.data;
}

export class ProjectPropertyNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
   */
  deleteProperty1(
    params: DeleteProperty1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteProperty1> {
    return deleteProperty1(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_READ
   */
  getProperties1(
    params: GetProperties1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProperties1> {
    return getProperties1(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  updateProperty(
    params: UpdatePropertyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateProperty> {
    return updateProperty(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
   */
  createProperty1(
    params: CreateProperty1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createProperty1> {
    return createProperty1(this._config, params, requestOptions);
  }
}
