// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

export * from "./project/part1";
export * from "./project/part2";
import type { ClientConfig, RequestOptions } from "../client";

import type {
  CloneProjectParams,
  CreateProjectParams,
  GetLatestProjectByNameParams,
  GetProjectChildrenConciseParams,
  GetProjectsByClassifierParams,
  GetProjectsConciseParams,
  GetProjectsParams,
  UpdateProjectParams,
} from "./project/part1";
import {
  cloneProject,
  createProject,
  deleteProjects,
  getLatestProjectByName,
  getProjectChildrenConcise,
  getProjects,
  getProjectsByClassifier,
  getProjectsConcise,
  updateProject,
} from "./project/part1";
import type {
  DeleteProjectParams,
  GetChildrenProjectsByClassifierParams,
  GetChildrenProjectsByTagParams,
  GetChildrenProjectsParams,
  GetProjectByNameAndVersionParams,
  GetProjectParams,
  GetProjectsByTagParams,
  GetProjectsWithoutDescendantsOfParams,
  PatchProjectParams,
} from "./project/part2";
import {
  deleteProject,
  getChildrenProjects,
  getChildrenProjectsByClassifier,
  getChildrenProjectsByTag,
  getProject,
  getProjectByNameAndVersion,
  getProjectsByTag,
  getProjectsWithoutDescendantsOf,
  patchProject,
} from "./project/part2";

export class ProjectNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission VIEW_PORTFOLIO
   */
  get(
    params: GetProjectsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjects> {
    return getProjects(this._config, params, requestOptions);
  }
  /**
   * Updates an existing project, including its metadata, access teams, and parent relationship. Supply `name` and `uuid` in the body; set `parent` to an object containing the new parent’s `uuid`, or omit it or set it to `null` to remove the parent. You need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission.
   *
   * To re-parent the project, set parent to an object containing the new parent's uuid . Omit parent (or set it to null ) to remove the parent. Providing parent without a non-null uuid is rejected with 400. Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  update(
    params: UpdateProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateProject> {
    return updateProject(this._config, params, requestOptions);
  }
  /**
   * Creates a project, optionally under a parent project and with team-based access. Supply `name` and `uuid`; set `parent` to an object containing the parent’s `uuid`, or omit it or set it to `null` to create a top-level project. You need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_CREATE` permission.
   *
   * To create the project under a parent, set parent to an object containing the parent's uuid . To create a top-level project, omit parent or set it to null . Providing parent without a non-null uuid is rejected with 400. When portfolio access control is enabled, one or more teams to grant access to can be provided via accessTeams . Either uuid or name of a team must be specified. Only teams which the authenticated principal is a member of can be assigned. Principals with ACCESS_MANAGEMENT permission can assign any team. Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
   */
  create(
    params: CreateProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createProject> {
    return createProject(this._config, params, requestOptions);
  }
  /**
   * Deletes multiple projects identified by their UUIDs. Pass a unique array of 1–1,000 project UUIDs in the request body; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_DELETE` permission.
   *
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
   */
  delete_(body: string[], requestOptions?: RequestOptions): ReturnType<typeof deleteProjects> {
    return deleteProjects(this._config, body, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getByClassifier(
    params: GetProjectsByClassifierParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectsByClassifier> {
    return getProjectsByClassifier(this._config, params, requestOptions);
  }
  /**
   * Clones an existing project and lets you choose which project data to include. Supply the source project UUID in `project` and a non-empty `version` for the clone; the response provides a token for checking cloning progress. This operation is deprecated; use `/api/v2/projects/{uuid}/clone` instead.
   *
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE Deprecated ! Use /api/v2/projects/{uuid}/clone instead.
   *
   * @deprecated This operation is deprecated and may be removed in a future
   *   release.
   */
  clone(
    params: CloneProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof cloneProject> {
    return cloneProject(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getConcise(
    params: GetProjectsConciseParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectsConcise> {
    return getProjectsConcise(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getChildrenConcise(
    params: GetProjectChildrenConciseParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectChildrenConcise> {
    return getProjectChildrenConcise(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getLatestByName(
    params: GetLatestProjectByNameParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getLatestProjectByName> {
    return getLatestProjectByName(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getByNameAndVersion(
    params: GetProjectByNameAndVersionParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectByNameAndVersion> {
    return getProjectByNameAndVersion(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getByTag(
    params: GetProjectsByTagParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectsByTag> {
    return getProjectsByTag(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getWithoutDescendantsOf(
    params: GetProjectsWithoutDescendantsOfParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProjectsWithoutDescendantsOf> {
    return getProjectsWithoutDescendantsOf(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
   */
  deleteProject(
    params: DeleteProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteProject> {
    return deleteProject(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getProject(
    params: GetProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getProject> {
    return getProject(this._config, params, requestOptions);
  }
  /**
   * Updates selected fields on an existing project, including its name, status, metadata, and parent. Supply the project fields you want to change; to re-parent the project, set `parent` to an object containing the new parent’s `uuid`, or omit `parent` or set it to `null` to leave the parent unchanged. You need the `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission.
   *
   * To re-parent the project, set parent to an object containing the new parent's uuid . Omit parent (or set it to null ) to leave the parent unchanged. Providing parent without a non-null uuid is rejected with 400. Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  patch(
    params: PatchProjectParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof patchProject> {
    return patchProject(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getChildren(
    params: GetChildrenProjectsParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getChildrenProjects> {
    return getChildrenProjects(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getChildrenByClassifier(
    params: GetChildrenProjectsByClassifierParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getChildrenProjectsByClassifier> {
    return getChildrenProjectsByClassifier(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getChildrenByTag(
    params: GetChildrenProjectsByTagParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getChildrenProjectsByTag> {
    return getChildrenProjectsByTag(this._config, params, requestOptions);
  }
}
