// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ProblemDetails, ServiceComponent } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest, toWire } from "../client";
import { validateLength, validateUuid } from "../validation";

export type UpdateServiceError = ProblemDetails;

export type UpdateServiceParams = ServiceComponent;

/**
 * Updates an existing service record with its metadata, data flows, references, and related project and provider information. Supply the service object with `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission. A successful response returns the updated service object.
 *
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param project - Required object value serialized in the `project` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param authenticated - Optional `boolean` value serialized in the
 *   `authenticated` wire field.
 * @param bomRef - Optional `string` value serialized in the `bomRef` wire field.
 * @param children - Optional array value serialized in the `children` wire
 *   field.
 * @param crossesTrustBoundary - Optional `boolean` value serialized in the
 *   `crossesTrustBoundary` wire field.
 * @param data - Optional array value serialized in the `data` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param endpoints - Optional array value serialized in the `endpoints` wire
 *   field.
 * @param externalReferences - Optional array value serialized in the
 *   `externalReferences` wire field.
 * @param group - Optional `string` value serialized in the `group` wire field.
 * @param lastInheritedRiskScore - Optional `double`-formatted value serialized
 *   in the `lastInheritedRiskScore` wire field.
 * @param notes - Optional `string` value serialized in the `notes` wire field.
 * @param parent - Optional object value serialized in the `parent` wire field.
 * @param provider - Optional object value serialized in the `provider` wire
 *   field.
 * @param version - Optional `string` value serialized in the `version` wire
 *   field.
 * @param vulnerabilities - Optional array value serialized in the
 *   `vulnerabilities` wire field.
 */
export async function updateService(
  config: ClientConfig,
  {
    name,
    project,
    uuid,
    authenticated,
    bomRef,
    children,
    crossesTrustBoundary,
    data,
    description,
    endpoints,
    externalReferences,
    group,
    lastInheritedRiskScore,
    notes,
    parent,
    provider,
    version,
    vulnerabilities,
  }: UpdateServiceParams,
  requestOptions?: RequestOptions,
): Promise<ServiceComponent> {
  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid);

  if (description != null) {
    validateLength("description", description, { min: 0, max: 1024 });
  }

  if (group != null) {
    validateLength("group", group, { min: 0, max: 255 });
  }

  if (version != null) {
    validateLength("version", version, { min: 0, max: 255 });
  }

  const _resp = await sdkRequest<ServiceComponent>({
    method: "POST",
    path: `/v1/service`,
    operationId: "updateService",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      project: toWire(project, "Project"),
      uuid,
      authenticated,
      bomRef,
      children: toWire(children, "ServiceComponent"),
      crossesTrustBoundary,
      data,
      description,
      endpoints,
      externalReferences,
      group,
      lastInheritedRiskScore,
      notes,
      parent: toWire(parent, "ServiceComponent"),
      provider,
      version,
      vulnerabilities: toWire(vulnerabilities, "Vulnerability"),
    },
    config,
  });
  return fromWire(_resp.data, "ServiceComponent") as ServiceComponent;
}

export type GetAllServicesError = ProblemDetails;

export interface GetAllServicesParams {
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 */
export async function getAllServices(
  config: ClientConfig,
  { uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder }: GetAllServicesParams,
  requestOptions?: RequestOptions,
): Promise<ServiceComponent[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ServiceComponent[]>({
    method: "GET",
    path: `/v1/service/project/${encodePathSegment(uuid)}`,
    operationId: "getAllServices",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ServiceComponent") as ServiceComponent[];
}

export type CreateServiceError = ProblemDetails;

export type CreateServiceParams = ServiceComponent & {
  uuid: string;
};

/**
 * Creates a new service for the project identified by `uuid`. When you provide a service object, include `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_CREATE` permission. A successful response returns the created service object.
 *
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
 *
 * @param uuid - The UUID of the project
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param project - Required object value serialized in the `project` wire field.
 * @param uuid_2 - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param authenticated - Optional `boolean` value serialized in the
 *   `authenticated` wire field.
 * @param bomRef - Optional `string` value serialized in the `bomRef` wire field.
 * @param children - Optional array value serialized in the `children` wire
 *   field.
 * @param crossesTrustBoundary - Optional `boolean` value serialized in the
 *   `crossesTrustBoundary` wire field.
 * @param data - Optional array value serialized in the `data` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param endpoints - Optional array value serialized in the `endpoints` wire
 *   field.
 * @param externalReferences - Optional array value serialized in the
 *   `externalReferences` wire field.
 * @param group - Optional `string` value serialized in the `group` wire field.
 * @param lastInheritedRiskScore - Optional `double`-formatted value serialized
 *   in the `lastInheritedRiskScore` wire field.
 * @param notes - Optional `string` value serialized in the `notes` wire field.
 * @param parent - Optional object value serialized in the `parent` wire field.
 * @param provider - Optional object value serialized in the `provider` wire
 *   field.
 * @param version - Optional `string` value serialized in the `version` wire
 *   field.
 * @param vulnerabilities - Optional array value serialized in the
 *   `vulnerabilities` wire field.
 */
export async function createService(
  config: ClientConfig,
  {
    uuid,
    name,
    project,
    uuid: uuid_2,
    authenticated,
    bomRef,
    children,
    crossesTrustBoundary,
    data,
    description,
    endpoints,
    externalReferences,
    group,
    lastInheritedRiskScore,
    notes,
    parent,
    provider,
    version,
    vulnerabilities,
  }: CreateServiceParams,
  requestOptions?: RequestOptions,
): Promise<ServiceComponent> {
  validateUuid("uuid", uuid);

  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid_2);

  if (description != null) {
    validateLength("description", description, { min: 0, max: 1024 });
  }

  if (group != null) {
    validateLength("group", group, { min: 0, max: 255 });
  }

  if (version != null) {
    validateLength("version", version, { min: 0, max: 255 });
  }

  const _resp = await sdkRequest<ServiceComponent>({
    method: "PUT",
    path: `/v1/service/project/${encodePathSegment(uuid)}`,
    operationId: "createService",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      project: toWire(project, "Project"),
      uuid: uuid_2,
      authenticated,
      bomRef,
      children: toWire(children, "ServiceComponent"),
      crossesTrustBoundary,
      data,
      description,
      endpoints,
      externalReferences,
      group,
      lastInheritedRiskScore,
      notes,
      parent: toWire(parent, "ServiceComponent"),
      provider,
      version,
      vulnerabilities: toWire(vulnerabilities, "Vulnerability"),
    },
    config,
  });
  return fromWire(_resp.data, "ServiceComponent") as ServiceComponent;
}

export type DeleteServiceError = ProblemDetails;

export interface DeleteServiceParams {
  uuid: string;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the service to delete
 */
export async function deleteService(
  config: ClientConfig,
  { uuid }: DeleteServiceParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/service/${encodePathSegment(uuid)}`,
    operationId: "deleteService",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type GetServiceByUuidError = ProblemDetails;

export interface GetServiceByUuidParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the service to retrieve
 */
export async function getServiceByUuid(
  config: ClientConfig,
  { uuid }: GetServiceByUuidParams,
  requestOptions?: RequestOptions,
): Promise<ServiceComponent> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ServiceComponent>({
    method: "GET",
    path: `/v1/service/${encodePathSegment(uuid)}`,
    operationId: "getServiceByUuid",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "ServiceComponent") as ServiceComponent;
}

export class ServiceNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Updates an existing service record with its metadata, data flows, references, and related project and provider information. Supply the service object with `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission. A successful response returns the updated service object.
   *
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
   */
  update(
    params: UpdateServiceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateService> {
    return updateService(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getAll(
    params: GetAllServicesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getAllServices> {
    return getAllServices(this._config, params, requestOptions);
  }
  /**
   * Creates a new service for the project identified by `uuid`. When you provide a service object, include `name`, `project`, and `uuid`; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_CREATE` permission. A successful response returns the created service object.
   *
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
   */
  create(
    params: CreateServiceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createService> {
    return createService(this._config, params, requestOptions);
  }
  /**
   * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
   */
  delete_(
    params: DeleteServiceParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteService> {
    return deleteService(this._config, params, requestOptions);
  }
  /**
   * Requires permission VIEW_PORTFOLIO
   */
  getByUuid(
    params: GetServiceByUuidParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof getServiceByUuid> {
    return getServiceByUuid(this._config, params, requestOptions);
  }
}
