// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  DeleteTeamRequest,
  TeamAlreadyExistsProblemDetails,
  TeamSelfResponse,
  VisibleTeams,
} from "../types/team";
import { ApiKey, Team } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateLength, validatePattern, validateUuid } from "../validation";

export type DeleteTeamParams = DeleteTeamRequest;

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param uuid - UUID of the team to delete
 */
export async function deleteTeam(
  config: ClientConfig,
  { uuid }: DeleteTeamParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/team`,
    operationId: "deleteTeam",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      uuid,
    },
    config,
  });
  void _resp.data;
  return;
}

export interface GetTeamsParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 */
export async function getTeams(
  config: ClientConfig,
  { pageNumber, pageSize, offset, limit, sortName, sortOrder }: GetTeamsParams = {},
  requestOptions?: RequestOptions,
): Promise<Team[]> {
  const _resp = await sdkRequest<Team[]>({
    method: "GET",
    path: `/v1/team`,
    operationId: "getTeams",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UpdateTeamParams = Team;

/**
 * Updates fields on an existing team, including its name, users, permissions, API keys, and identity-provider mappings. Send the team values you want to update; `name` must be 1 to 255 characters and contain no control characters. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param apiKeys - Optional array value serialized in the `apiKeys` wire field.
 * @param ldapUsers - Optional array value serialized in the `ldapUsers` wire
 *   field.
 * @param managedUsers - Optional array value serialized in the `managedUsers`
 *   wire field.
 * @param mappedLdapGroups - Optional array value serialized in the
 *   `mappedLdapGroups` wire field.
 * @param mappedOidcGroups - Optional array value serialized in the
 *   `mappedOidcGroups` wire field.
 * @param oidcUsers - Optional array value serialized in the `oidcUsers` wire
 *   field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param serviceAccounts - Optional array value serialized in the
 *   `serviceAccounts` wire field.
 */
export async function updateTeam(
  config: ClientConfig,
  {
    name,
    uuid,
    apiKeys,
    ldapUsers,
    managedUsers,
    mappedLdapGroups,
    mappedOidcGroups,
    oidcUsers,
    permissions,
    serviceAccounts,
  }: UpdateTeamParams,
  requestOptions?: RequestOptions,
): Promise<Team> {
  validateLength("name", name, { min: 1, max: 255 });
  validatePattern("name", name, "[\\P{Cc}]+");

  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Team>({
    method: "POST",
    path: `/v1/team`,
    operationId: "updateTeam",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      uuid,
      apiKeys,
      ldapUsers,
      managedUsers,
      mappedLdapGroups,
      mappedOidcGroups,
      oidcUsers,
      permissions,
      serviceAccounts,
    },
    config,
  });
  return _resp.data;
}

export type CreateTeamError = TeamAlreadyExistsProblemDetails;

export type CreateTeamParams = Team;

/**
 * Creates a new team with its name and any supplied users, permissions, API keys, service accounts, and identity-provider mappings. Send the team fields to include; `name` must be 1 to 255 characters and contain no control characters. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param apiKeys - Optional array value serialized in the `apiKeys` wire field.
 * @param ldapUsers - Optional array value serialized in the `ldapUsers` wire
 *   field.
 * @param managedUsers - Optional array value serialized in the `managedUsers`
 *   wire field.
 * @param mappedLdapGroups - Optional array value serialized in the
 *   `mappedLdapGroups` wire field.
 * @param mappedOidcGroups - Optional array value serialized in the
 *   `mappedOidcGroups` wire field.
 * @param oidcUsers - Optional array value serialized in the `oidcUsers` wire
 *   field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param serviceAccounts - Optional array value serialized in the
 *   `serviceAccounts` wire field.
 */
export async function createTeam(
  config: ClientConfig,
  {
    name,
    uuid,
    apiKeys,
    ldapUsers,
    managedUsers,
    mappedLdapGroups,
    mappedOidcGroups,
    oidcUsers,
    permissions,
    serviceAccounts,
  }: CreateTeamParams,
  requestOptions?: RequestOptions,
): Promise<Team> {
  validateLength("name", name, { min: 1, max: 255 });
  validatePattern("name", name, "[\\P{Cc}]+");

  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Team>({
    method: "PUT",
    path: `/v1/team`,
    operationId: "createTeam",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      name,
      uuid,
      apiKeys,
      ldapUsers,
      managedUsers,
      mappedLdapGroups,
      mappedOidcGroups,
      oidcUsers,
      permissions,
      serviceAccounts,
    },
    config,
  });
  return _resp.data;
}

export interface DeleteApiKeyParams {
  publicIdOrKey: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param publicIdOrKey - The public ID for the API key or for Legacy the full
 *   Key to delete
 */
export async function deleteApiKey(
  config: ClientConfig,
  { publicIdOrKey }: DeleteApiKeyParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/team/key/${encodePathSegment(publicIdOrKey)}`,
    operationId: "deleteApiKey",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export interface RegenerateApiKeyParams {
  publicIdOrKey: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param publicIdOrKey - The public ID for the API key or for Legacy the
 *   complete Key to regenerate
 */
export async function regenerateApiKey(
  config: ClientConfig,
  { publicIdOrKey }: RegenerateApiKeyParams,
  requestOptions?: RequestOptions,
): Promise<ApiKey> {
  const _resp = await sdkRequest<ApiKey>({
    method: "POST",
    path: `/v1/team/key/${encodePathSegment(publicIdOrKey)}`,
    operationId: "regenerateApiKey",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface UpdateApiKeyCommentParams {
  publicIdOrKey: string;
  body?: string;
}

/**
 * Updates the comment on an API key identified by its public ID or, for a legacy key, its complete key value. Send the comment as a plain-text request body; the authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission. A successful response returns the updated API key.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param publicIdOrKey - The public ID for the API key or for Legacy the
 *   complete Key to comment on
 */
export async function updateApiKeyComment(
  config: ClientConfig,
  { publicIdOrKey, body }: UpdateApiKeyCommentParams,
  requestOptions?: RequestOptions,
): Promise<ApiKey> {
  const _resp = await sdkRequest<ApiKey>({
    method: "POST",
    path: `/v1/team/key/${encodePathSegment(publicIdOrKey)}/comment`,
    operationId: "updateApiKeyComment",
    responseDecoder: "json",
    ...requestOptions,
    body,
    contentType: "text/plain",
    config,
  });
  return _resp.data;
}

/**
 * Retrieves the team associated with the authenticated user's API key. Use this endpoint to inspect the team's name, UUID, permissions, and associated users.
 */
export async function getSelf(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<TeamSelfResponse> {
  const _resp = await sdkRequest<TeamSelfResponse>({
    method: "GET",
    path: `/v1/team/self`,
    operationId: "getSelf",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface AvailableTeamsParams {
  searchText?: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Optional query parameter searchText . The search is case insensitive and matches team names.
 *
 * @param searchText - Optional case-insensitive substring match on team name.
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 */
export async function availableTeams(
  config: ClientConfig,
  {
    searchText,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
  }: AvailableTeamsParams = {},
  requestOptions?: RequestOptions,
): Promise<VisibleTeams[]> {
  const _resp = await sdkRequest<VisibleTeams[]>({
    method: "GET",
    path: `/v1/team/visible`,
    operationId: "availableTeams",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      searchText: queryValue(searchText, "form", true),
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetTeamParams {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 *
 * @param uuid - The UUID of the team to retrieve
 */
export async function getTeam(
  config: ClientConfig,
  { uuid }: GetTeamParams,
  requestOptions?: RequestOptions,
): Promise<Team> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Team>({
    method: "GET",
    path: `/v1/team/${encodePathSegment(uuid)}`,
    operationId: "getTeam",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export interface GenerateApiKeyParams {
  uuid: string;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param uuid - The UUID of the team to generate a key for
 */
export async function generateApiKey(
  config: ClientConfig,
  { uuid }: GenerateApiKeyParams,
  requestOptions?: RequestOptions,
): Promise<ApiKey> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ApiKey>({
    method: "PUT",
    path: `/v1/team/${encodePathSegment(uuid)}/key`,
    operationId: "generateApiKey",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class TeamNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  delete_(
    params: DeleteTeamParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteTeam> {
    return deleteTeam(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  get(params: GetTeamsParams = {}, requestOptions?: RequestOptions): ReturnType<typeof getTeams> {
    return getTeams(this._config, params, requestOptions);
  }
  /**
   * Updates fields on an existing team, including its name, users, permissions, API keys, and identity-provider mappings. Send the team values you want to update; `name` must be 1 to 255 characters and contain no control characters. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  update(params: UpdateTeamParams, requestOptions?: RequestOptions): ReturnType<typeof updateTeam> {
    return updateTeam(this._config, params, requestOptions);
  }
  /**
   * Creates a new team with its name and any supplied users, permissions, API keys, service accounts, and identity-provider mappings. Send the team fields to include; `name` must be 1 to 255 characters and contain no control characters. The authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
   */
  create(params: CreateTeamParams, requestOptions?: RequestOptions): ReturnType<typeof createTeam> {
    return createTeam(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
   */
  deleteApiKey(
    params: DeleteApiKeyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteApiKey> {
    return deleteApiKey(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
   */
  regenerateApiKey(
    params: RegenerateApiKeyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof regenerateApiKey> {
    return regenerateApiKey(this._config, params, requestOptions);
  }
  /**
   * Updates the comment on an API key identified by its public ID or, for a legacy key, its complete key value. Send the comment as a plain-text request body; the authenticated user must have `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission. A successful response returns the updated API key.
   *
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
   */
  updateApiKeyComment(
    params: UpdateApiKeyCommentParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateApiKeyComment> {
    return updateApiKeyComment(this._config, params, requestOptions);
  }
  /**
   * Retrieves the team associated with the authenticated user's API key. Use this endpoint to inspect the team's name, UUID, permissions, and associated users.
   */
  getSelf(requestOptions?: RequestOptions): ReturnType<typeof getSelf> {
    return getSelf(this._config, requestOptions);
  }
  /**
   * Optional query parameter searchText . The search is case insensitive and matches team names.
   */
  available(
    params: AvailableTeamsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof availableTeams> {
    return availableTeams(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
   */
  getTeam(params: GetTeamParams, requestOptions?: RequestOptions): ReturnType<typeof getTeam> {
    return getTeam(this._config, params, requestOptions);
  }
  /**
   * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
   */
  generateApiKey(
    params: GenerateApiKeyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof generateApiKey> {
    return generateApiKey(this._config, params, requestOptions);
  }
}
