// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { About } from "../types/version";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

/**
 * Returns a simple json object containing the name of the application and the version
 */
export async function getVersion(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<About> {
  const _resp = await sdkRequest<About>({
    method: "GET",
    path: `/version`,
    operationId: "getVersion",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class VersionNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Returns a simple json object containing the name of the application and the version
   */
  get(requestOptions?: RequestOptions): ReturnType<typeof getVersion> {
    return getVersion(this._config, requestOptions);
  }
}
