// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ViolationAnalysisRequest, ViolationAnalysisResponse } from "../types/violationanalysis";
import { ProblemDetails } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { queryValue, sdkRequest } from "../client";
import { validatePattern, validateUuid } from "../validation";

export type RetrieveAnalysis1Error = ProblemDetails;

export interface RetrieveAnalysis1Params {
  component: string;
  policyViolation: string;
}

/**
 * Requires permission VIEW_POLICY_VIOLATION
 *
 * @param component - The UUID of the component
 * @param policyViolation - The UUID of the policy violation
 */
export async function retrieveAnalysis1(
  config: ClientConfig,
  { component, policyViolation }: RetrieveAnalysis1Params,
  requestOptions?: RequestOptions,
): Promise<ViolationAnalysisResponse> {
  validateUuid("component", component);

  validateUuid("policyViolation", policyViolation);

  const _resp = await sdkRequest<ViolationAnalysisResponse>({
    method: "GET",
    path: `/v1/violation/analysis`,
    operationId: "retrieveAnalysis1",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      component: queryValue(component, "form", true),
      policyViolation: queryValue(policyViolation, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type UpdateAnalysis1Error = ProblemDetails;

export type UpdateAnalysis1Params = ViolationAnalysisRequest;

/**
 * Records an analysis decision for a policy violation affecting a component. Provide the `component` and `policyViolation` UUIDs, and optionally set `analysisState`, add a `comment`, or update suppression status. The authenticated user needs `POLICY_VIOLATION_ANALYSIS` permission.
 *
 * Requires permission POLICY_VIOLATION_ANALYSIS
 *
 * @param component - Required `string` value serialized in the `component` wire
 *   field.
 * @param policyViolation - Required `string` value serialized in the
 *   `policyViolation` wire field.
 * @param analysisState - Optional enumerated value serialized in the
 *   `analysisState` wire field.
 * @param comment - Optional `string` value serialized in the `comment` wire
 *   field.
 * @param isSuppressed - Optional `boolean` value serialized in the
 *   `isSuppressed` wire field.
 * @param suppressed - Optional `boolean` value serialized in the `suppressed`
 *   wire field.
 */
export async function updateAnalysis1(
  config: ClientConfig,
  {
    component,
    policyViolation,
    analysisState,
    comment,
    isSuppressed,
    suppressed,
  }: UpdateAnalysis1Params,
  requestOptions?: RequestOptions,
): Promise<ViolationAnalysisResponse> {
  validatePattern(
    "component",
    component,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  validatePattern(
    "policyViolation",
    policyViolation,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  const _resp = await sdkRequest<ViolationAnalysisResponse>({
    method: "PUT",
    path: `/v1/violation/analysis`,
    operationId: "updateAnalysis1",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      component,
      policyViolation,
      analysisState,
      comment,
      isSuppressed,
      suppressed,
    },
    config,
  });
  return _resp.data;
}

export class ViolationanalysisNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Requires permission VIEW_POLICY_VIOLATION
   */
  retrieveAnalysis1(
    params: RetrieveAnalysis1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof retrieveAnalysis1> {
    return retrieveAnalysis1(this._config, params, requestOptions);
  }
  /**
   * Records an analysis decision for a policy violation affecting a component. Provide the `component` and `policyViolation` UUIDs, and optionally set `analysisState`, add a `comment`, or update suppression status. The authenticated user needs `POLICY_VIOLATION_ANALYSIS` permission.
   *
   * Requires permission POLICY_VIOLATION_ANALYSIS
   */
  updateAnalysis1(
    params: UpdateAnalysis1Params,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof updateAnalysis1> {
    return updateAnalysis1(this._config, params, requestOptions);
  }
}
