// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  updateComponent,
  getComponentByHash,
  getComponentByIdentity,
  identifyInternalComponents,
  getDependencyGraphForComponent,
  getAllComponents,
} from "../../../dist/methods/component/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  updateComponent: {
    route: "updateComponent",
    mediaType: "application/json",
    invoke: (bag) =>
      updateComponent(config, {
        classifier: bag.__body?.["classifier"],
        name: bag.__body?.["name"],
        project: bag.__body?.["project"],
        uuid: bag.__body?.["uuid"],
        author: bag.__body?.["author"],
        authors: bag.__body?.["authors"],
        blake2b256: bag.__body?.["blake2b_256"],
        blake2b384: bag.__body?.["blake2b_384"],
        blake2b512: bag.__body?.["blake2b_512"],
        blake3: bag.__body?.["blake3"],
        children: bag.__body?.["children"],
        copyright: bag.__body?.["copyright"],
        cpe: bag.__body?.["cpe"],
        dependencyGraph: bag.__body?.["dependencyGraph"],
        description: bag.__body?.["description"],
        directDependencies: bag.__body?.["directDependencies"],
        expandDependencyGraph: bag.__body?.["expandDependencyGraph"],
        extension: bag.__body?.["extension"],
        externalReferences: bag.__body?.["externalReferences"],
        filename: bag.__body?.["filename"],
        group: bag.__body?.["group"],
        isInternal: bag.__body?.["isInternal"],
        lastInheritedRiskScore: bag.__body?.["lastInheritedRiskScore"],
        license: bag.__body?.["license"],
        licenseExpression: bag.__body?.["licenseExpression"],
        licenseUrl: bag.__body?.["licenseUrl"],
        md5: bag.__body?.["md5"],
        metrics: bag.__body?.["metrics"],
        notes: bag.__body?.["notes"],
        occurrenceCount: bag.__body?.["occurrenceCount"],
        parent: bag.__body?.["parent"],
        properties: bag.__body?.["properties"],
        publisher: bag.__body?.["publisher"],
        purl: bag.__body?.["purl"],
        purlCoordinates: bag.__body?.["purlCoordinates"],
        repositoryMeta: bag.__body?.["repositoryMeta"],
        resolvedLicense: bag.__body?.["resolvedLicense"],
        scope: bag.__body?.["scope"],
        sha1: bag.__body?.["sha1"],
        sha256: bag.__body?.["sha256"],
        sha384: bag.__body?.["sha384"],
        sha3256: bag.__body?.["sha3_256"],
        sha3384: bag.__body?.["sha3_384"],
        sha3512: bag.__body?.["sha3_512"],
        sha512: bag.__body?.["sha512"],
        streebog256: bag.__body?.["streebog_256"],
        streebog512: bag.__body?.["streebog_512"],
        supplier: bag.__body?.["supplier"],
        swidTagId: bag.__body?.["swidTagId"],
        version: bag.__body?.["version"],
        vulnerabilities: bag.__body?.["vulnerabilities"],
      }),
  },
  getComponentByHash: {
    route: "getComponentByHash",
    mediaType: null,
    invoke: (bag) =>
      getComponentByHash(config, {
        hash: bag["hash"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  getComponentByIdentity: {
    route: "getComponentByIdentity",
    mediaType: null,
    invoke: (bag) =>
      getComponentByIdentity(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        group: bag["group"],
        name: bag["name"],
        version: bag["version"],
        purl: bag["purl"],
        cpe: bag["cpe"],
        swidTagId: bag["swidTagId"],
        project: bag["project"],
        excludeInactiveProjects: bag["excludeInactiveProjects"],
        onlyLatestProjectVersions: bag["onlyLatestProjectVersions"],
      }),
  },
  identifyInternalComponents: {
    route: "identifyInternalComponents",
    mediaType: null,
    invoke: () => identifyInternalComponents(config, {}),
  },
  getDependencyGraphForComponent: {
    route: "getDependencyGraphForComponent",
    mediaType: null,
    invoke: (bag) =>
      getDependencyGraphForComponent(config, {
        projectUuid: bag["projectUuid"],
        componentUuids: bag["componentUuids"],
      }),
  },
  getAllComponents: {
    route: "getAllComponents",
    mediaType: null,
    invoke: (bag) =>
      getAllComponents(config, {
        uuid: bag["uuid"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        onlyOutdated: bag["onlyOutdated"],
        onlyDirect: bag["onlyDirect"],
      }),
  },
};

test("component/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
