// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { User } from "../../types/shared";
import { IdentifiableObject } from "../../types/user";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, sdkRequest } from "../../client";

export type RemoveTeamFromUserParams = IdentifiableObject & {
  username: string;
};

/**
 * Removes the specified user from a team. Provide the user's `username` and the team's `uuid` in the request. The authenticated user needs `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_DELETE` permission to make this change.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param username - A valid username
 * @param uuid - Optional `string` value serialized in the `uuid` wire field.
 */
export async function removeTeamFromUser(
  config: ClientConfig,
  { username, uuid }: RemoveTeamFromUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  const _resp = await sdkRequest<User>({
    method: "DELETE",
    path: `/v1/user/${encodePathSegment(username)}/membership`,
    operationId: "removeTeamFromUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      uuid,
    },
    config,
  });
  return _resp.data;
}

export type AddTeamToUserParams = IdentifiableObject & {
  username: string;
};

/**
 * Adds the specified user to a team. Provide the user's `username` and the team's `uuid` in the request. The authenticated user needs `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission to make this change.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param username - A valid username
 * @param uuid - Optional `string` value serialized in the `uuid` wire field.
 */
export async function addTeamToUser(
  config: ClientConfig,
  { username, uuid }: AddTeamToUserParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  const _resp = await sdkRequest<User>({
    method: "POST",
    path: `/v1/user/${encodePathSegment(username)}/membership`,
    operationId: "addTeamToUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      uuid,
    },
    config,
  });
  return _resp.data;
}
