// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { DeleteUserRequest, TeamsSetRequest } from "../../types/user";
import { LdapUser, ManagedUser, OidcUser, ProblemDetails, User } from "../../types/shared";
import type { ClientConfig, RequestOptions } from "../../client";
import { sdkRequest, serializeHeaders } from "../../client";
import { validateLength, validatePattern } from "../../validation";

export interface ForceChangePasswordParams {
  confirmPassword?: string;
  newPassword?: string;
  password?: string;
  username?: string;
}

/**
 * Updates a user's password after validating the supplied login credentials. Send `username`, `password`, `newPassword`, and `confirmPassword` as form-encoded fields, with matching new and confirmation passwords.
 *
 * Upon a successful login, a bearer token will be returned in the response body.
 */
export async function forceChangePassword(
  config: ClientConfig,
  { confirmPassword, newPassword, password, username }: ForceChangePasswordParams = {},
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/v1/user/forceChangePassword`,
    operationId: "forceChangePassword",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      confirmPassword,
      newPassword,
      password,
      username,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  void _resp.data;
  return;
}

export type DeleteLdapUserParams = DeleteUserRequest;

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param username - Username of the user to delete
 */
export async function deleteLdapUser(
  config: ClientConfig,
  { username }: DeleteLdapUserParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateLength("username", username, { min: 1 });

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/user/ldap`,
    operationId: "deleteLdapUser",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      username,
    },
    config,
  });
  void _resp.data;
  return;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 */
export async function getLdapUsers(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<LdapUser[]> {
  const _resp = await sdkRequest<LdapUser[]>({
    method: "GET",
    path: `/v1/user/ldap`,
    operationId: "getLdapUsers",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type CreateLdapUserParams = LdapUser;

/**
 * Creates an LDAP-backed user that references an existing LDAP object. Supply the required `username` and the LDAP `dn`; the authenticated user needs `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 * @param dn - Optional `string` value serialized in the `dn` wire field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param teams - Optional array value serialized in the `teams` wire field.
 */
export async function createLdapUser(
  config: ClientConfig,
  { username, dn, email, permissions, teams }: CreateLdapUserParams,
  requestOptions?: RequestOptions,
): Promise<LdapUser> {
  validateLength("username", username, { min: 1, max: 255 });
  validatePattern("username", username, "[\\P{Cc}]+");

  if (dn != null) {
    validateLength("dn", dn, { min: 1, max: 255 });
    validatePattern("dn", dn, "[\\P{Cc}]+");
  }

  if (email != null) {
    validateLength("email", email, { min: 0, max: 255 });
    validatePattern("email", email, "[\\P{Cc}]+");
  }

  const _resp = await sdkRequest<LdapUser>({
    method: "PUT",
    path: `/v1/user/ldap`,
    operationId: "createLdapUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      username,
      dn,
      email,
      permissions,
      teams,
    },
    config,
  });
  return _resp.data;
}

export interface ValidateCredentialsParams {
  password?: string;
  username?: string;
}

/**
 * Authenticates a user by validating `username` and `password` credentials. Send the credentials as `application/x-www-form-urlencoded`; a successful response contains a bearer token for REST API authentication.
 *
 * Upon a successful login, a bearer token will be returned in the response body.
 */
export async function validateCredentials(
  config: ClientConfig,
  { password, username }: ValidateCredentialsParams = {},
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "POST",
    path: `/v1/user/login`,
    operationId: "validateCredentials",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      password,
      username,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

export interface LogoutParams {
  authorization?: string;
}

/**
 * Invalidates the authenticated user's current session. Logout is a no-op when you authenticate with an API key; send the optional `Authorization` header to identify the session to invalidate.
 *
 * Invalidates the current session. No-op when authenticated via API key.
 */
export async function logout(
  config: ClientConfig,
  { authorization }: LogoutParams = {},
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/v1/user/logout`,
    operationId: "logout",
    responseDecoder: "empty",
    ...requestOptions,
    headers: { ...serializeHeaders({ Authorization: authorization }), ...requestOptions?.headers },
    config,
  });
  void _resp.data;
  return;
}

export type DeleteManagedUserParams = DeleteUserRequest;

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param username - Username of the user to delete
 */
export async function deleteManagedUser(
  config: ClientConfig,
  { username }: DeleteManagedUserParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateLength("username", username, { min: 1 });

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/user/managed`,
    operationId: "deleteManagedUser",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      username,
    },
    config,
  });
  void _resp.data;
  return;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 */
export async function getManagedUsers(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<ManagedUser[]> {
  const _resp = await sdkRequest<ManagedUser[]>({
    method: "GET",
    path: `/v1/user/managed`,
    operationId: "getManagedUsers",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateManagedUserParams = ManagedUser;

/**
 * Updates an existing managed user account. Supply `username` and `lastPasswordChange`, then include the account fields you want to update. You need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param lastPasswordChange - UNIX epoch timestamp in milliseconds
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 * @param confirmPassword - Optional `string` value serialized in the
 *   `confirmPassword` wire field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param forcePasswordChange - Optional `boolean` value serialized in the
 *   `forcePasswordChange` wire field.
 * @param fullname - Optional `string` value serialized in the `fullname` wire
 *   field.
 * @param newPassword - Optional `string` value serialized in the `newPassword`
 *   wire field.
 * @param nonExpiryPassword - Optional `boolean` value serialized in the
 *   `nonExpiryPassword` wire field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param suspended - Optional `boolean` value serialized in the `suspended` wire
 *   field.
 * @param teams - Optional array value serialized in the `teams` wire field.
 */
export async function updateManagedUser(
  config: ClientConfig,
  {
    lastPasswordChange,
    username,
    confirmPassword,
    email,
    forcePasswordChange,
    fullname,
    newPassword,
    nonExpiryPassword,
    permissions,
    suspended,
    teams,
  }: UpdateManagedUserParams,
  requestOptions?: RequestOptions,
): Promise<ManagedUser> {
  validateLength("username", username, { min: 1, max: 255 });
  validatePattern("username", username, "[\\P{Cc}]+");

  if (email != null) {
    validateLength("email", email, { min: 0, max: 255 });
    validatePattern("email", email, "[\\P{Cc}]+");
  }

  if (fullname != null) {
    validateLength("fullname", fullname, { min: 0, max: 255 });
    validatePattern("fullname", fullname, "[\\P{Cc}]+");
  }

  const _resp = await sdkRequest<ManagedUser>({
    method: "POST",
    path: `/v1/user/managed`,
    operationId: "updateManagedUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      lastPasswordChange,
      username,
      confirmPassword,
      email,
      forcePasswordChange,
      fullname,
      newPassword,
      nonExpiryPassword,
      permissions,
      suspended,
      teams,
    },
    config,
  });
  return _resp.data;
}

export type CreateManagedUserParams = ManagedUser;

/**
 * Creates a managed user account. Supply `username` and `lastPasswordChange`; include any other account details, permissions, or teams you want to set. You need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param lastPasswordChange - UNIX epoch timestamp in milliseconds
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 * @param confirmPassword - Optional `string` value serialized in the
 *   `confirmPassword` wire field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param forcePasswordChange - Optional `boolean` value serialized in the
 *   `forcePasswordChange` wire field.
 * @param fullname - Optional `string` value serialized in the `fullname` wire
 *   field.
 * @param newPassword - Optional `string` value serialized in the `newPassword`
 *   wire field.
 * @param nonExpiryPassword - Optional `boolean` value serialized in the
 *   `nonExpiryPassword` wire field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param suspended - Optional `boolean` value serialized in the `suspended` wire
 *   field.
 * @param teams - Optional array value serialized in the `teams` wire field.
 */
export async function createManagedUser(
  config: ClientConfig,
  {
    lastPasswordChange,
    username,
    confirmPassword,
    email,
    forcePasswordChange,
    fullname,
    newPassword,
    nonExpiryPassword,
    permissions,
    suspended,
    teams,
  }: CreateManagedUserParams,
  requestOptions?: RequestOptions,
): Promise<ManagedUser> {
  validateLength("username", username, { min: 1, max: 255 });
  validatePattern("username", username, "[\\P{Cc}]+");

  if (email != null) {
    validateLength("email", email, { min: 0, max: 255 });
    validatePattern("email", email, "[\\P{Cc}]+");
  }

  if (fullname != null) {
    validateLength("fullname", fullname, { min: 0, max: 255 });
    validatePattern("fullname", fullname, "[\\P{Cc}]+");
  }

  const _resp = await sdkRequest<ManagedUser>({
    method: "PUT",
    path: `/v1/user/managed`,
    operationId: "createManagedUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      lastPasswordChange,
      username,
      confirmPassword,
      email,
      forcePasswordChange,
      fullname,
      newPassword,
      nonExpiryPassword,
      permissions,
      suspended,
      teams,
    },
    config,
  });
  return _resp.data;
}

export type SetUserTeamsError = ProblemDetails;

export type SetUserTeamsParams = TeamsSetRequest;

/**
 * Sets the teams assigned to a user, replacing the specified team membership set. Supply the user's `username` and an array of team UUIDs; each UUID must be unique. You need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_UPDATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_UPDATE
 *
 * @param teams - Required array value serialized in the `teams` wire field.
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 */
export async function setUserTeams(
  config: ClientConfig,
  { teams, username }: SetUserTeamsParams,
  requestOptions?: RequestOptions,
): Promise<User> {
  validateLength("username", username, { min: 1 });

  const _resp = await sdkRequest<User>({
    method: "PUT",
    path: `/v1/user/membership`,
    operationId: "setUserTeams",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      teams,
      username,
    },
    config,
  });
  return _resp.data;
}

export type DeleteOidcUserParams = DeleteUserRequest;

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_DELETE
 *
 * @param username - Username of the user to delete
 */
export async function deleteOidcUser(
  config: ClientConfig,
  { username }: DeleteOidcUserParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateLength("username", username, { min: 1 });

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/user/oidc`,
    operationId: "deleteOidcUser",
    responseDecoder: "empty",
    ...requestOptions,
    body: {
      username,
    },
    config,
  });
  void _resp.data;
  return;
}

/**
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_READ
 */
export async function getOidcUsers(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "GET",
    path: `/v1/user/oidc`,
    operationId: "getOidcUsers",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type CreateOidcUserParams = OidcUser;

/**
 * Creates a user account that references an existing OpenID Connect user. Supply the required `username` and add the OIDC subject identifier, email, permissions, or teams as needed. You need the `ACCESS_MANAGEMENT` or `ACCESS_MANAGEMENT_CREATE` permission.
 *
 * Requires permission ACCESS_MANAGEMENT or ACCESS_MANAGEMENT_CREATE
 *
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param subjectIdentifier - Optional `string` value serialized in the
 *   `subjectIdentifier` wire field.
 * @param teams - Optional array value serialized in the `teams` wire field.
 */
export async function createOidcUser(
  config: ClientConfig,
  { username, email, permissions, subjectIdentifier, teams }: CreateOidcUserParams,
  requestOptions?: RequestOptions,
): Promise<OidcUser> {
  validateLength("username", username, { min: 1, max: 255 });
  validatePattern("username", username, "[\\P{Cc}]+");

  if (email != null) {
    validateLength("email", email, { min: 0, max: 255 });
    validatePattern("email", email, "[\\P{Cc}]+");
  }

  if (subjectIdentifier != null) {
    validateLength("subjectIdentifier", subjectIdentifier, { min: 1, max: 255 });
    validatePattern("subjectIdentifier", subjectIdentifier, "[\\P{Cc}]+");
  }

  const _resp = await sdkRequest<OidcUser>({
    method: "PUT",
    path: `/v1/user/oidc`,
    operationId: "createOidcUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      username,
      email,
      permissions,
      subjectIdentifier,
      teams,
    },
    config,
  });
  return _resp.data;
}

export interface ValidateOidcAccessTokenParams {
  idToken: string;
  accessToken?: string;
}

/**
 * Authenticates an OpenID Connect user by validating an `idToken`. Send the request as form-encoded data; include `accessToken` if your authentication flow requires it. A successful response provides a bearer token for REST API authentication.
 *
 * Upon a successful login, a bearer token will be returned in the response body.
 *
 * @param idToken - An OAuth2 access token
 */
export async function validateOidcAccessToken(
  config: ClientConfig,
  { idToken, accessToken }: ValidateOidcAccessTokenParams,
  requestOptions?: RequestOptions,
): Promise<string> {
  const _resp = await sdkRequest<string>({
    method: "POST",
    path: `/v1/user/oidc/login`,
    operationId: "validateOidcAccessToken",
    responseDecoder: "text",
    ...requestOptions,
    body: {
      idToken,
      accessToken,
    },
    contentType: "application/x-www-form-urlencoded",
    config,
  });
  return _resp.data;
}

/**
 * Retrieves information about the authenticated user. Use this endpoint to inspect the user's username, email, permissions, and team memberships.
 */
export async function getSelf1(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<User> {
  const _resp = await sdkRequest<User>({
    method: "GET",
    path: `/v1/user/self`,
    operationId: "getSelf1",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type UpdateSelfParams = ManagedUser;

/**
 * Updates the profile information for the authenticated user. Supply `username` and `lastPasswordChange`, and include any other profile fields you want to change. The response contains the updated user object.
 *
 * @param lastPasswordChange - UNIX epoch timestamp in milliseconds
 * @param username - Required `string` value serialized in the `username` wire
 *   field.
 * @param confirmPassword - Optional `string` value serialized in the
 *   `confirmPassword` wire field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param forcePasswordChange - Optional `boolean` value serialized in the
 *   `forcePasswordChange` wire field.
 * @param fullname - Optional `string` value serialized in the `fullname` wire
 *   field.
 * @param newPassword - Optional `string` value serialized in the `newPassword`
 *   wire field.
 * @param nonExpiryPassword - Optional `boolean` value serialized in the
 *   `nonExpiryPassword` wire field.
 * @param permissions - Optional array value serialized in the `permissions` wire
 *   field.
 * @param suspended - Optional `boolean` value serialized in the `suspended` wire
 *   field.
 * @param teams - Optional array value serialized in the `teams` wire field.
 */
export async function updateSelf(
  config: ClientConfig,
  {
    lastPasswordChange,
    username,
    confirmPassword,
    email,
    forcePasswordChange,
    fullname,
    newPassword,
    nonExpiryPassword,
    permissions,
    suspended,
    teams,
  }: UpdateSelfParams,
  requestOptions?: RequestOptions,
): Promise<ManagedUser> {
  validateLength("username", username, { min: 1, max: 255 });
  validatePattern("username", username, "[\\P{Cc}]+");

  if (email != null) {
    validateLength("email", email, { min: 0, max: 255 });
    validatePattern("email", email, "[\\P{Cc}]+");
  }

  if (fullname != null) {
    validateLength("fullname", fullname, { min: 0, max: 255 });
    validatePattern("fullname", fullname, "[\\P{Cc}]+");
  }

  const _resp = await sdkRequest<ManagedUser>({
    method: "POST",
    path: `/v1/user/self`,
    operationId: "updateSelf",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      lastPasswordChange,
      username,
      confirmPassword,
      email,
      forcePasswordChange,
      fullname,
      newPassword,
      nonExpiryPassword,
      permissions,
      suspended,
      teams,
    },
    config,
  });
  return _resp.data;
}

/**
 * Returns all permissions the authenticated user has, including those inherited from teams.
 */
export async function getSelfPermissions(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<string[]> {
  const _resp = await sdkRequest<string[]>({
    method: "GET",
    path: `/v1/user/self/permissions`,
    operationId: "getSelfPermissions",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}
