// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  BomUploadResponse,
  ListProjectsResponseItem,
  ProblemDetails,
  Project,
} from "../../types/shared";
import { CloneProjectRequest, ConciseProject } from "../../types/project";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest, toWire } from "../../client";
import { validateItems, validateLength, validatePattern, validateUuid } from "../../validation";

export interface GetProjectsParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  name?: string;
  excludeInactive?: boolean;
  onlyRoot?: boolean;
  notAssignedToTeamWithUuid?: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param name - The optional name of the project to query on
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 * @param onlyRoot - Optionally excludes children projects from being returned
 * @param notAssignedToTeamWithUuid - The UUID of the team which projects shall
 *   be excluded
 */
export async function getProjects(
  config: ClientConfig,
  {
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    name,
    excludeInactive,
    onlyRoot,
    notAssignedToTeamWithUuid,
  }: GetProjectsParams = {},
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  if (notAssignedToTeamWithUuid != null) {
    validateUuid("notAssignedToTeamWithUuid", notAssignedToTeamWithUuid);
  }

  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project`,
    operationId: "getProjects",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      name: queryValue(name, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
      onlyRoot: queryValue(onlyRoot, "form", true),
      notAssignedToTeamWithUuid: queryValue(notAssignedToTeamWithUuid, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export type UpdateProjectError = ProblemDetails;

export type UpdateProjectParams = Project;

/**
 * Updates an existing project, including its metadata, access teams, and parent relationship. Supply `name` and `uuid` in the body; set `parent` to an object containing the new parent’s `uuid`, or omit it or set it to `null` to remove the parent. You need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission.
 *
 * To re-parent the project, set parent to an object containing the new parent's uuid . Omit parent (or set it to null ) to remove the parent. Providing parent without a non-null uuid is rejected with 400. Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param lastBomImport - UNIX epoch timestamp in milliseconds
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param accessTeams - Optional array value serialized in the `accessTeams` wire
 *   field.
 * @param active - Optional `boolean` value serialized in the `active` wire
 *   field.
 * @param author - Optional `string` value serialized in the `author` wire field.
 * @param authors - Optional array value serialized in the `authors` wire field.
 * @param bomRef - Optional `string` value serialized in the `bomRef` wire field.
 * @param children - Optional array value serialized in the `children` wire
 *   field.
 * @param classifier - Optional enumerated value serialized in the `classifier`
 *   wire field.
 * @param collectionLogic - Optional enumerated value serialized in the
 *   `collectionLogic` wire field.
 * @param collectionTag - Optional object value serialized in the `collectionTag`
 *   wire field.
 * @param cpe - Optional `string` value serialized in the `cpe` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param directDependencies - Optional `string` value serialized in the
 *   `directDependencies` wire field.
 * @param externalReferences - Optional array value serialized in the
 *   `externalReferences` wire field.
 * @param group - Optional `string` value serialized in the `group` wire field.
 * @param inactiveSince - UNIX epoch timestamp in milliseconds
 * @param isLatest - Optional `boolean` value serialized in the `isLatest` wire
 *   field.
 * @param lastBomImportFormat - Optional `string` value serialized in the
 *   `lastBomImportFormat` wire field.
 * @param lastInheritedRiskScore - Optional `double`-formatted value serialized
 *   in the `lastInheritedRiskScore` wire field.
 * @param lastVulnerabilityAnalysis - UNIX epoch timestamp in milliseconds
 * @param manufacturer - Optional object value serialized in the `manufacturer`
 *   wire field.
 * @param metadata - Optional object value serialized in the `metadata` wire
 *   field.
 * @param metrics - Optional object value serialized in the `metrics` wire field.
 * @param parent - Optional object value serialized in the `parent` wire field.
 * @param publisher - Optional `string` value serialized in the `publisher` wire
 *   field.
 * @param purl - Optional `string` value serialized in the `purl` wire field.
 * @param supplier - Optional object value serialized in the `supplier` wire
 *   field.
 * @param swidTagId - Optional `string` value serialized in the `swidTagId` wire
 *   field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param version - Optional `string` value serialized in the `version` wire
 *   field.
 * @param versions - Optional array value serialized in the `versions` wire
 *   field.
 */
export async function updateProject(
  config: ClientConfig,
  {
    lastBomImport,
    name,
    uuid,
    accessTeams,
    active,
    author,
    authors,
    bomRef,
    children,
    classifier,
    collectionLogic,
    collectionTag,
    cpe,
    description,
    directDependencies,
    externalReferences,
    group,
    inactiveSince,
    isLatest,
    lastBomImportFormat,
    lastInheritedRiskScore,
    lastVulnerabilityAnalysis,
    manufacturer,
    metadata,
    metrics,
    parent,
    publisher,
    purl,
    supplier,
    swidTagId,
    tags,
    version,
    versions,
  }: UpdateProjectParams,
  requestOptions?: RequestOptions,
): Promise<Project> {
  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid);

  if (cpe != null) {
    validateLength("cpe", cpe, { min: 0, max: 255 });
    validatePattern(
      "cpe",
      cpe,
      "(cpe:2\\.3:[aho\\*\\-](:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\\*\\-]))(:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6})",
    );
  }

  if (description != null) {
    validateLength("description", description, { min: 0, max: 255 });
  }

  if (group != null) {
    validateLength("group", group, { min: 0, max: 255 });
  }

  if (publisher != null) {
    validateLength("publisher", publisher, { min: 0, max: 255 });
  }

  if (purl != null) {
    validateLength("purl", purl, { min: 0, max: 1024 });
  }

  if (swidTagId != null) {
    validateLength("swidTagId", swidTagId, { min: 0, max: 255 });
  }

  const _resp = await sdkRequest<Project>({
    method: "POST",
    path: `/v1/project`,
    operationId: "updateProject",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      lastBomImport,
      name,
      uuid,
      accessTeams,
      active,
      author,
      authors,
      bomRef,
      children: toWire(children, "Project"),
      classifier,
      collectionLogic,
      collectionTag,
      cpe,
      description,
      directDependencies,
      externalReferences,
      group,
      inactiveSince,
      isLatest,
      lastBomImportFormat,
      lastInheritedRiskScore,
      lastVulnerabilityAnalysis,
      manufacturer,
      metadata: toWire(metadata, "ProjectMetadata"),
      metrics,
      parent: toWire(parent, "Project"),
      publisher,
      purl,
      supplier,
      swidTagId,
      tags,
      version,
      versions,
    },
    config,
  });
  return fromWire(_resp.data, "Project") as Project;
}

export type CreateProjectError = ProblemDetails;

export type CreateProjectParams = Project;

/**
 * Creates a project, optionally under a parent project and with team-based access. Supply `name` and `uuid`; set `parent` to an object containing the parent’s `uuid`, or omit it or set it to `null` to create a top-level project. You need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_CREATE` permission.
 *
 * To create the project under a parent, set parent to an object containing the parent's uuid . To create a top-level project, omit parent or set it to null . Providing parent without a non-null uuid is rejected with 400. When portfolio access control is enabled, one or more teams to grant access to can be provided via accessTeams . Either uuid or name of a team must be specified. Only teams which the authenticated principal is a member of can be assigned. Principals with ACCESS_MANAGEMENT permission can assign any team. Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE
 *
 * @param lastBomImport - UNIX epoch timestamp in milliseconds
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param accessTeams - Optional array value serialized in the `accessTeams` wire
 *   field.
 * @param active - Optional `boolean` value serialized in the `active` wire
 *   field.
 * @param author - Optional `string` value serialized in the `author` wire field.
 * @param authors - Optional array value serialized in the `authors` wire field.
 * @param bomRef - Optional `string` value serialized in the `bomRef` wire field.
 * @param children - Optional array value serialized in the `children` wire
 *   field.
 * @param classifier - Optional enumerated value serialized in the `classifier`
 *   wire field.
 * @param collectionLogic - Optional enumerated value serialized in the
 *   `collectionLogic` wire field.
 * @param collectionTag - Optional object value serialized in the `collectionTag`
 *   wire field.
 * @param cpe - Optional `string` value serialized in the `cpe` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param directDependencies - Optional `string` value serialized in the
 *   `directDependencies` wire field.
 * @param externalReferences - Optional array value serialized in the
 *   `externalReferences` wire field.
 * @param group - Optional `string` value serialized in the `group` wire field.
 * @param inactiveSince - UNIX epoch timestamp in milliseconds
 * @param isLatest - Optional `boolean` value serialized in the `isLatest` wire
 *   field.
 * @param lastBomImportFormat - Optional `string` value serialized in the
 *   `lastBomImportFormat` wire field.
 * @param lastInheritedRiskScore - Optional `double`-formatted value serialized
 *   in the `lastInheritedRiskScore` wire field.
 * @param lastVulnerabilityAnalysis - UNIX epoch timestamp in milliseconds
 * @param manufacturer - Optional object value serialized in the `manufacturer`
 *   wire field.
 * @param metadata - Optional object value serialized in the `metadata` wire
 *   field.
 * @param metrics - Optional object value serialized in the `metrics` wire field.
 * @param parent - Optional object value serialized in the `parent` wire field.
 * @param publisher - Optional `string` value serialized in the `publisher` wire
 *   field.
 * @param purl - Optional `string` value serialized in the `purl` wire field.
 * @param supplier - Optional object value serialized in the `supplier` wire
 *   field.
 * @param swidTagId - Optional `string` value serialized in the `swidTagId` wire
 *   field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param version - Optional `string` value serialized in the `version` wire
 *   field.
 * @param versions - Optional array value serialized in the `versions` wire
 *   field.
 */
export async function createProject(
  config: ClientConfig,
  {
    lastBomImport,
    name,
    uuid,
    accessTeams,
    active,
    author,
    authors,
    bomRef,
    children,
    classifier,
    collectionLogic,
    collectionTag,
    cpe,
    description,
    directDependencies,
    externalReferences,
    group,
    inactiveSince,
    isLatest,
    lastBomImportFormat,
    lastInheritedRiskScore,
    lastVulnerabilityAnalysis,
    manufacturer,
    metadata,
    metrics,
    parent,
    publisher,
    purl,
    supplier,
    swidTagId,
    tags,
    version,
    versions,
  }: CreateProjectParams,
  requestOptions?: RequestOptions,
): Promise<Project> {
  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid);

  if (cpe != null) {
    validateLength("cpe", cpe, { min: 0, max: 255 });
    validatePattern(
      "cpe",
      cpe,
      "(cpe:2\\.3:[aho\\*\\-](:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\\*\\-]))(:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6})",
    );
  }

  if (description != null) {
    validateLength("description", description, { min: 0, max: 255 });
  }

  if (group != null) {
    validateLength("group", group, { min: 0, max: 255 });
  }

  if (publisher != null) {
    validateLength("publisher", publisher, { min: 0, max: 255 });
  }

  if (purl != null) {
    validateLength("purl", purl, { min: 0, max: 1024 });
  }

  if (swidTagId != null) {
    validateLength("swidTagId", swidTagId, { min: 0, max: 255 });
  }

  const _resp = await sdkRequest<Project>({
    method: "PUT",
    path: `/v1/project`,
    operationId: "createProject",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      lastBomImport,
      name,
      uuid,
      accessTeams,
      active,
      author,
      authors,
      bomRef,
      children: toWire(children, "Project"),
      classifier,
      collectionLogic,
      collectionTag,
      cpe,
      description,
      directDependencies,
      externalReferences,
      group,
      inactiveSince,
      isLatest,
      lastBomImportFormat,
      lastInheritedRiskScore,
      lastVulnerabilityAnalysis,
      manufacturer,
      metadata: toWire(metadata, "ProjectMetadata"),
      metrics,
      parent: toWire(parent, "Project"),
      publisher,
      purl,
      supplier,
      swidTagId,
      tags,
      version,
      versions,
    },
    config,
  });
  return fromWire(_resp.data, "Project") as Project;
}

/**
 * Deletes multiple projects identified by their UUIDs. Pass a unique array of 1–1,000 project UUIDs in the request body; you need `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_DELETE` permission.
 *
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
 */
export async function deleteProjects(
  config: ClientConfig,
  body: string[],
  requestOptions?: RequestOptions,
): Promise<void> {
  if (body != null) {
    validateItems("body", body, { min: 1, max: 1000 });
  }

  const _resp = await sdkRequest<void>({
    method: "POST",
    path: `/v1/project/batchDelete`,
    operationId: "deleteProjects",
    responseDecoder: "empty",
    ...requestOptions,
    body,
    config,
  });
  void _resp.data;
  return;
}

export interface GetProjectsByClassifierParams {
  classifier:
    | "APPLICATION"
    | "FRAMEWORK"
    | "LIBRARY"
    | "CONTAINER"
    | "OPERATING_SYSTEM"
    | "DEVICE"
    | "FIRMWARE"
    | "FILE"
    | "PLATFORM"
    | "DEVICE_DRIVER"
    | "MACHINE_LEARNING_MODEL"
    | "DATA"
    | "CRYPTOGRAPHIC_ASSET"
    | (string & {});
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  excludeInactive?: boolean;
  onlyRoot?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param classifier - The classifier to query on
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 * @param onlyRoot - Optionally excludes children projects from being returned
 */
export async function getProjectsByClassifier(
  config: ClientConfig,
  {
    classifier,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    excludeInactive,
    onlyRoot,
  }: GetProjectsByClassifierParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project/classifier/${encodePathSegment(classifier)}`,
    operationId: "getProjectsByClassifier",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
      onlyRoot: queryValue(onlyRoot, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export type CloneProjectError = ProblemDetails;

export type CloneProjectParams = CloneProjectRequest;

/**
 * Clones an existing project and lets you choose which project data to include. Supply the source project UUID in `project` and a non-empty `version` for the clone; the response provides a token for checking cloning progress. This operation is deprecated; use `/api/v2/projects/{uuid}/clone` instead.
 *
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_CREATE Deprecated ! Use /api/v2/projects/{uuid}/clone instead.
 *
 * @param project - Required `string` value serialized in the `project` wire
 *   field.
 * @param version - Required `string` value serialized in the `version` wire
 *   field.
 * @param includeAcl - Optional `boolean` value serialized in the `includeACL`
 *   wire field.
 * @param includeAuditHistory - Optional `boolean` value serialized in the
 *   `includeAuditHistory` wire field.
 * @param includeComponents - Optional `boolean` value serialized in the
 *   `includeComponents` wire field.
 * @param includeDependencies - Optional `boolean` value serialized in the
 *   `includeDependencies` wire field.
 * @param includePolicyViolations - Optional `boolean` value serialized in the
 *   `includePolicyViolations` wire field.
 * @param includeProperties - Optional `boolean` value serialized in the
 *   `includeProperties` wire field.
 * @param includeServices - Optional `boolean` value serialized in the
 *   `includeServices` wire field.
 * @param includeTags - Optional `boolean` value serialized in the `includeTags`
 *   wire field.
 * @param makeCloneLatest - Optional `boolean` value serialized in the
 *   `makeCloneLatest` wire field.
 * @deprecated This operation is deprecated and may be removed in a future
 *   release.
 */
export async function cloneProject(
  config: ClientConfig,
  {
    project,
    version,
    includeAcl,
    includeAuditHistory,
    includeComponents,
    includeDependencies,
    includePolicyViolations,
    includeProperties,
    includeServices,
    includeTags,
    makeCloneLatest,
  }: CloneProjectParams,
  requestOptions?: RequestOptions,
): Promise<BomUploadResponse> {
  validatePattern(
    "project",
    project,
    "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
  );

  validateLength("version", version, { min: 1 });

  const _resp = await sdkRequest<BomUploadResponse>({
    method: "PUT",
    path: `/v1/project/clone`,
    operationId: "cloneProject",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      project,
      version,
      includeACL: includeAcl,
      includeAuditHistory,
      includeComponents,
      includeDependencies,
      includePolicyViolations,
      includeProperties,
      includeServices,
      includeTags,
      makeCloneLatest,
    },
    config,
  });
  return _resp.data;
}

export interface GetProjectsConciseParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  name?: string;
  version?: string;
  classifier?: string;
  tag?: string;
  team?: string;
  active?: boolean;
  onlyRoot?: boolean;
  includeMetrics?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param name - Name to filter on. Must be exact match.
 * @param version - Version to filter on. Must be exact match.
 * @param classifier - Classifier to filter on. Must be exact match.
 * @param tag - Tag to filter on. Must be exact match.
 * @param team - Team to filter on. Must be exact match.
 * @param active - Whether to show only active, or only inactive projects.
 * @param onlyRoot - Whether to show only root projects, i.e. those without a
 *   parent.
 * @param includeMetrics - Whether to include metrics in the response.
 */
export async function getProjectsConcise(
  config: ClientConfig,
  {
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    name,
    version,
    classifier,
    tag,
    team,
    active,
    onlyRoot,
    includeMetrics,
  }: GetProjectsConciseParams = {},
  requestOptions?: RequestOptions,
): Promise<ConciseProject[]> {
  const _resp = await sdkRequest<ConciseProject[]>({
    method: "GET",
    path: `/v1/project/concise`,
    operationId: "getProjectsConcise",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      name: queryValue(name, "form", true),
      version: queryValue(version, "form", true),
      classifier: queryValue(classifier, "form", true),
      tag: queryValue(tag, "form", true),
      team: queryValue(team, "form", true),
      active: queryValue(active, "form", true),
      onlyRoot: queryValue(onlyRoot, "form", true),
      includeMetrics: queryValue(includeMetrics, "form", true),
    },
    config,
  });
  return _resp.data;
}

export interface GetProjectChildrenConciseParams {
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  name?: string;
  version?: string;
  classifier?: string;
  tag?: string;
  team?: string;
  active?: boolean;
  includeMetrics?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - UUID of the project
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param name - Name to filter on. Must be exact match.
 * @param version - Version to filter on. Must be exact match.
 * @param classifier - Classifier to filter on. Must be exact match.
 * @param tag - Tag to filter on. Must be exact match.
 * @param team - Team to filter on. Must be exact match.
 * @param active - Whether to show only active, or only inactive projects.
 *   Omitting the filter will show both.
 * @param includeMetrics - Whether to include metrics in the response.
 */
export async function getProjectChildrenConcise(
  config: ClientConfig,
  {
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    name,
    version,
    classifier,
    tag,
    team,
    active,
    includeMetrics,
  }: GetProjectChildrenConciseParams,
  requestOptions?: RequestOptions,
): Promise<ConciseProject[]> {
  const _resp = await sdkRequest<ConciseProject[]>({
    method: "GET",
    path: `/v1/project/concise/${encodePathSegment(uuid)}/children`,
    operationId: "getProjectChildrenConcise",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      name: queryValue(name, "form", true),
      version: queryValue(version, "form", true),
      classifier: queryValue(classifier, "form", true),
      tag: queryValue(tag, "form", true),
      team: queryValue(team, "form", true),
      active: queryValue(active, "form", true),
      includeMetrics: queryValue(includeMetrics, "form", true),
    },
    config,
  });
  return _resp.data;
}

export type GetLatestProjectByNameError = ProblemDetails;

export interface GetLatestProjectByNameParams {
  name: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param name - The name of the project to retrieve the latest version of
 */
export async function getLatestProjectByName(
  config: ClientConfig,
  { name }: GetLatestProjectByNameParams,
  requestOptions?: RequestOptions,
): Promise<Project> {
  const _resp = await sdkRequest<Project>({
    method: "GET",
    path: `/v1/project/latest/${encodePathSegment(name)}`,
    operationId: "getLatestProjectByName",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "Project") as Project;
}
