// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { ListProjectsResponseItem, ProblemDetails, Project } from "../../types/shared";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest, toWire } from "../../client";
import { validateLength, validatePattern, validateUuid } from "../../validation";

export type GetProjectByNameAndVersionError = ProblemDetails;

export interface GetProjectByNameAndVersionParams {
  name: string;
  version?: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param name - The name of the project to query on
 * @param version - The version of the project to query on
 */
export async function getProjectByNameAndVersion(
  config: ClientConfig,
  { name, version }: GetProjectByNameAndVersionParams,
  requestOptions?: RequestOptions,
): Promise<Project> {
  const _resp = await sdkRequest<Project>({
    method: "GET",
    path: `/v1/project/lookup`,
    operationId: "getProjectByNameAndVersion",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      name: queryValue(name, "form", true),
      version: queryValue(version, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "Project") as Project;
}

export interface GetProjectsByTagParams {
  tag: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  excludeInactive?: boolean;
  onlyRoot?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param tag - The tag to query on
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 * @param onlyRoot - Optionally excludes children projects from being returned
 */
export async function getProjectsByTag(
  config: ClientConfig,
  {
    tag,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    excludeInactive,
    onlyRoot,
  }: GetProjectsByTagParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project/tag/${encodePathSegment(tag)}`,
    operationId: "getProjectsByTag",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
      onlyRoot: queryValue(onlyRoot, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export type GetProjectsWithoutDescendantsOfError = ProblemDetails;

export interface GetProjectsWithoutDescendantsOfParams {
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  name?: string;
  excludeInactive?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project which descendants will be excluded
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param name - The optional name of the project to query on
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 */
export async function getProjectsWithoutDescendantsOf(
  config: ClientConfig,
  {
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    name,
    excludeInactive,
  }: GetProjectsWithoutDescendantsOfParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project/withoutDescendantsOf/${encodePathSegment(uuid)}`,
    operationId: "getProjectsWithoutDescendantsOf",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      name: queryValue(name, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export type DeleteProjectError = ProblemDetails;

export interface DeleteProjectParams {
  uuid: string;
}

/**
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_DELETE
 *
 * @param uuid - The UUID of the project to delete
 */
export async function deleteProject(
  config: ClientConfig,
  { uuid }: DeleteProjectParams,
  requestOptions?: RequestOptions,
): Promise<void> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<void>({
    method: "DELETE",
    path: `/v1/project/${encodePathSegment(uuid)}`,
    operationId: "deleteProject",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type GetProjectError = ProblemDetails;

export interface GetProjectParams {
  uuid: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project to retrieve
 */
export async function getProject(
  config: ClientConfig,
  { uuid }: GetProjectParams,
  requestOptions?: RequestOptions,
): Promise<Project> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Project>({
    method: "GET",
    path: `/v1/project/${encodePathSegment(uuid)}`,
    operationId: "getProject",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return fromWire(_resp.data, "Project") as Project;
}

export type PatchProjectError = ProblemDetails;

export type PatchProjectParams = Project & {
  uuid: string;
};

/**
 * Updates selected fields on an existing project, including its name, status, metadata, and parent. Supply the project fields you want to change; to re-parent the project, set `parent` to an object containing the new parent’s `uuid`, or omit `parent` or set it to `null` to leave the parent unchanged. You need the `PORTFOLIO_MANAGEMENT` or `PORTFOLIO_MANAGEMENT_UPDATE` permission.
 *
 * To re-parent the project, set parent to an object containing the new parent's uuid . Omit parent (or set it to null ) to leave the parent unchanged. Providing parent without a non-null uuid is rejected with 400. Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param uuid - The UUID of the project to modify
 * @param lastBomImport - UNIX epoch timestamp in milliseconds
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param uuid_2 - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param accessTeams - Optional array value serialized in the `accessTeams` wire
 *   field.
 * @param active - Optional `boolean` value serialized in the `active` wire
 *   field.
 * @param author - Optional `string` value serialized in the `author` wire field.
 * @param authors - Optional array value serialized in the `authors` wire field.
 * @param bomRef - Optional `string` value serialized in the `bomRef` wire field.
 * @param children - Optional array value serialized in the `children` wire
 *   field.
 * @param classifier - Optional enumerated value serialized in the `classifier`
 *   wire field.
 * @param collectionLogic - Optional enumerated value serialized in the
 *   `collectionLogic` wire field.
 * @param collectionTag - Optional object value serialized in the `collectionTag`
 *   wire field.
 * @param cpe - Optional `string` value serialized in the `cpe` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param directDependencies - Optional `string` value serialized in the
 *   `directDependencies` wire field.
 * @param externalReferences - Optional array value serialized in the
 *   `externalReferences` wire field.
 * @param group - Optional `string` value serialized in the `group` wire field.
 * @param inactiveSince - UNIX epoch timestamp in milliseconds
 * @param isLatest - Optional `boolean` value serialized in the `isLatest` wire
 *   field.
 * @param lastBomImportFormat - Optional `string` value serialized in the
 *   `lastBomImportFormat` wire field.
 * @param lastInheritedRiskScore - Optional `double`-formatted value serialized
 *   in the `lastInheritedRiskScore` wire field.
 * @param lastVulnerabilityAnalysis - UNIX epoch timestamp in milliseconds
 * @param manufacturer - Optional object value serialized in the `manufacturer`
 *   wire field.
 * @param metadata - Optional object value serialized in the `metadata` wire
 *   field.
 * @param metrics - Optional object value serialized in the `metrics` wire field.
 * @param parent - Optional object value serialized in the `parent` wire field.
 * @param publisher - Optional `string` value serialized in the `publisher` wire
 *   field.
 * @param purl - Optional `string` value serialized in the `purl` wire field.
 * @param supplier - Optional object value serialized in the `supplier` wire
 *   field.
 * @param swidTagId - Optional `string` value serialized in the `swidTagId` wire
 *   field.
 * @param tags - Optional array value serialized in the `tags` wire field.
 * @param version - Optional `string` value serialized in the `version` wire
 *   field.
 * @param versions - Optional array value serialized in the `versions` wire
 *   field.
 */
export async function patchProject(
  config: ClientConfig,
  {
    uuid,
    lastBomImport,
    name,
    uuid: uuid_2,
    accessTeams,
    active,
    author,
    authors,
    bomRef,
    children,
    classifier,
    collectionLogic,
    collectionTag,
    cpe,
    description,
    directDependencies,
    externalReferences,
    group,
    inactiveSince,
    isLatest,
    lastBomImportFormat,
    lastInheritedRiskScore,
    lastVulnerabilityAnalysis,
    manufacturer,
    metadata,
    metrics,
    parent,
    publisher,
    purl,
    supplier,
    swidTagId,
    tags,
    version,
    versions,
  }: PatchProjectParams,
  requestOptions?: RequestOptions,
): Promise<Project> {
  validateUuid("uuid", uuid);

  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid_2);

  if (cpe != null) {
    validateLength("cpe", cpe, { min: 0, max: 255 });
    validatePattern(
      "cpe",
      cpe,
      "(cpe:2\\.3:[aho\\*\\-](:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\\*\\-]))(:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6})",
    );
  }

  if (description != null) {
    validateLength("description", description, { min: 0, max: 255 });
  }

  if (group != null) {
    validateLength("group", group, { min: 0, max: 255 });
  }

  if (publisher != null) {
    validateLength("publisher", publisher, { min: 0, max: 255 });
  }

  if (purl != null) {
    validateLength("purl", purl, { min: 0, max: 1024 });
  }

  if (swidTagId != null) {
    validateLength("swidTagId", swidTagId, { min: 0, max: 255 });
  }

  const _resp = await sdkRequest<Project>({
    method: "PATCH",
    path: `/v1/project/${encodePathSegment(uuid)}`,
    operationId: "patchProject",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      lastBomImport,
      name,
      uuid: uuid_2,
      accessTeams,
      active,
      author,
      authors,
      bomRef,
      children: toWire(children, "Project"),
      classifier,
      collectionLogic,
      collectionTag,
      cpe,
      description,
      directDependencies,
      externalReferences,
      group,
      inactiveSince,
      isLatest,
      lastBomImportFormat,
      lastInheritedRiskScore,
      lastVulnerabilityAnalysis,
      manufacturer,
      metadata: toWire(metadata, "ProjectMetadata"),
      metrics,
      parent: toWire(parent, "Project"),
      publisher,
      purl,
      supplier,
      swidTagId,
      tags,
      version,
      versions,
    },
    config,
  });
  return fromWire(_resp.data, "Project") as Project;
}

export type GetChildrenProjectsError = ProblemDetails;

export interface GetChildrenProjectsParams {
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  excludeInactive?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project to get the children from
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 */
export async function getChildrenProjects(
  config: ClientConfig,
  {
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    excludeInactive,
  }: GetChildrenProjectsParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project/${encodePathSegment(uuid)}/children`,
    operationId: "getChildrenProjects",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export type GetChildrenProjectsByClassifierError = ProblemDetails;

export interface GetChildrenProjectsByClassifierParams {
  classifier:
    | "APPLICATION"
    | "FRAMEWORK"
    | "LIBRARY"
    | "CONTAINER"
    | "OPERATING_SYSTEM"
    | "DEVICE"
    | "FIRMWARE"
    | "FILE"
    | "PLATFORM"
    | "DEVICE_DRIVER"
    | "MACHINE_LEARNING_MODEL"
    | "DATA"
    | "CRYPTOGRAPHIC_ASSET"
    | (string & {});
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  excludeInactive?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param classifier - The classifier to query on
 * @param uuid - The UUID of the project to get the children from
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 */
export async function getChildrenProjectsByClassifier(
  config: ClientConfig,
  {
    classifier,
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    excludeInactive,
  }: GetChildrenProjectsByClassifierParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project/${encodePathSegment(uuid)}/children/classifier/${encodePathSegment(classifier)}`,
    operationId: "getChildrenProjectsByClassifier",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}

export type GetChildrenProjectsByTagError = ProblemDetails;

export interface GetChildrenProjectsByTagParams {
  tag: string;
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  excludeInactive?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param tag - The tag to query on
 * @param uuid - The UUID of the project to get the children from
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param excludeInactive - Optionally excludes inactive projects from being
 *   returned
 */
export async function getChildrenProjectsByTag(
  config: ClientConfig,
  {
    tag,
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    excludeInactive,
  }: GetChildrenProjectsByTagParams,
  requestOptions?: RequestOptions,
): Promise<ListProjectsResponseItem[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<ListProjectsResponseItem[]>({
    method: "GET",
    path: `/v1/project/${encodePathSegment(uuid)}/children/tag/${encodePathSegment(tag)}`,
    operationId: "getChildrenProjectsByTag",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      excludeInactive: queryValue(excludeInactive, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "ListProjectsResponseItem") as ListProjectsResponseItem[];
}
