// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Tag } from "./shared.part002";

/**
 * Typed representation of the `BomSubmitRequest` API schema.
 */
export interface BomSubmitRequest {
  /**
   * Optional `boolean` value serialized in the `autoCreate` wire field.
   */
  autoCreate?: boolean;
  /**
   * Base64 encoded BOM

   * @example "ewogICJib21Gb3JtYXQiOiAiQ3ljbG9uZURYIiwKICAic3BlY1ZlcnNpb24iOiAiMS40IiwKICAiY29tcG9uZW50cyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAibGlicmFyeSIsCiAgICAgICJuYW1lIjogImFjbWUtbGliIiwKICAgICAgInZlcnNpb24iOiAiMS4wLjAiCiAgICB9CiAgXQp9"
   */
  bom: string;
  /**
   * Optional `boolean` value serialized in the `isActive` wire field.
   */
  isActive?: boolean;
  /**
   * Optional `boolean` value serialized in the `isLatest` wire field.
   */
  isLatest?: boolean;
  /**
   * Optional `string` value serialized in the `parentName` wire field.

   * @example "Example Application Parent"
   */
  parentName?: string;
  /**
   * Optional `string` value serialized in the `parentUUID` wire field.

   * @example "5341f53c-611b-4388-9d9c-731026dc5eec"
   */
  parentUuid?: string;
  /**
   * Optional `string` value serialized in the `parentVersion` wire field.

   * @example "1.0.0"
   */
  parentVersion?: string;
  /**
   * Required `string` value serialized in the `project` wire field.

   * @example "38640b33-4ba9-4733-bdab-cbfc40c6f8aa"
   */
  project: string;
  /**
   * Required `string` value serialized in the `projectName` wire field.

   * @example "Example Application"
   */
  projectName: string;
  /**
   * Optional array value serialized in the `projectTags` wire field.

   * @example "tag1, tag2"
   */
  projectTags?: Tag[];
  /**
   * Required `string` value serialized in the `projectVersion` wire field.

   * @example "1.0.0"
   */
  projectVersion: string;
}
