// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ComponentPropertyResponse` API schema.
 */
export interface ComponentPropertyResponse {
  /**
   * Description of the property
   */
  description?: string;
  /**
   * Group the property belongs to
   */
  groupName?: string;
  /**
   * Name of the property
   */
  propertyName: string;
  /**
   * Type of the property
   */
  propertyType:
    | "BOOLEAN"
    | "INTEGER"
    | "NUMBER"
    | "STRING"
    | "TIMESTAMP"
    | "URL"
    | "UUID"
    | (string & {});
  /**
   * Value of the property
   */
  propertyValue?: string;
  /**
   * UUID of the property
   */
  uuid: string;
}

/**
 * Typed representation of the `CreateComponentPropertyRequest` API schema.
 */
export interface CreateComponentPropertyRequest {
  /**
   * Description of the property
   */
  description?: string;
  /**
   * Group the property belongs to
   */
  groupName?: string;
  /**
   * Name of the property
   */
  propertyName: string;
  /**
   * Type of the property
   */
  propertyType:
    | "BOOLEAN"
    | "INTEGER"
    | "NUMBER"
    | "STRING"
    | "TIMESTAMP"
    | "URL"
    | "UUID"
    | (string & {});
  /**
   * Value of the property
   */
  propertyValue?: string;
}
