// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `Finding` API schema.
 */
export interface Finding {
  /**
   * Optional object value serialized in the `analysis` wire field.
   */
  analysis?: { [key: string]: { [key: string]: unknown } };
  /**
   * Optional object value serialized in the `attribution` wire field.
   */
  attribution?: { [key: string]: { [key: string]: unknown } };
  /**
   * Optional object value serialized in the `component` wire field.
   */
  component?: { [key: string]: { [key: string]: unknown } };
  /**
   * Optional `string` value serialized in the `matrix` wire field.
   */
  matrix?: string;
  /**
   * Optional object value serialized in the `vulnerability` wire field.
   */
  vulnerability?: { [key: string]: { [key: string]: unknown } };
}
