// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `MappedLdapGroupRequest` API schema.
 */
export interface MappedLdapGroupRequest {
  /**
   * Required `string` value serialized in the `dn` wire field.
   */
  dn: string;
  /**
   * Required `string` value serialized in the `team` wire field.
   */
  team: string;
}

/**
 * Typed representation of the `MappedLdapGroupResponse` API schema.
 */
export interface MappedLdapGroupResponse {
  /**
   * Distinguished name of the mapped LDAP group
   */
  dn: string;
  /**
   * UUID of the mapping
   */
  uuid: string;
}
