// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { LicenseGroup } from "./shared-license";

/**
 * Typed representation of the `ConciseLicenseResponse` API schema.
 */
export interface ConciseLicenseResponse {
  /**
   * Whether the license is a custom license created by a user
   */
  isCustomLicense: boolean;
  /**
   * Whether the licenseId has been deprecated by SPDX
   */
  isDeprecatedLicenseId: boolean;
  /**
   * Whether the license is FSF libre
   */
  isFsfLibre: boolean;
  /**
   * Whether the license is approved by the OSI
   */
  isOsiApproved: boolean;
  /**
   * Identifier of the license
   */
  licenseId: string;
  /**
   * Display name of the license
   */
  name: string;
  /**
   * UUID of the license
   */
  uuid: string;
}

/**
 * Typed representation of the `CreateLicenseRequest` API schema.
 */
export interface CreateLicenseRequest {
  /**
   * Whether the licenseId has been deprecated by SPDX
   */
  isDeprecatedLicenseId?: boolean;
  /**
   * Whether the license is FSF libre
   */
  isFsfLibre?: boolean;
  /**
   * Whether the license is approved by the OSI
   */
  isOsiApproved?: boolean;
  /**
   * Comments about the license
   */
  licenseComments?: string;
  /**
   * Identifier of the license
   */
  licenseId: string;
  /**
   * Full license text
   */
  licenseText?: string;
  /**
   * Display name of the license
   */
  name: string;
  /**
   * Additional URLs with information about the license
   */
  seeAlso?: string[];
  /**
   * Standard license header typically added to the top of source code
   */
  standardLicenseHeader?: string;
  /**
   * Standard license template used to derive the license text
   */
  standardLicenseTemplate?: string;
}

/**
 * Typed representation of the `LicenseResponse` API schema.
 */
export interface LicenseResponse {
  /**
   * Whether the license is a custom license created by a user
   */
  isCustomLicense: boolean;
  /**
   * Whether the licenseId has been deprecated by SPDX
   */
  isDeprecatedLicenseId: boolean;
  /**
   * Whether the license is FSF libre
   */
  isFsfLibre: boolean;
  /**
   * Whether the license is approved by the OSI
   */
  isOsiApproved: boolean;
  /**
   * Comments about the license
   */
  licenseComments?: string;
  /**
   * License groups the license belongs to
   */
  licenseGroups: LicenseGroup[];
  /**
   * Identifier of the license
   */
  licenseId: string;
  /**
   * Full license text
   */
  licenseText?: string;
  /**
   * Display name of the license
   */
  name: string;
  /**
   * Additional URLs with information about the license
   */
  seeAlso?: string[];
  /**
   * Standard license header typically added to the top of source code
   */
  standardLicenseHeader?: string;
  /**
   * Standard license template used to derive the license text
   */
  standardLicenseTemplate?: string;
  /**
   * UUID of the license
   */
  uuid: string;
}
