// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ProblemDetails, Project, Tag } from "./shared.part002";

import type { Team } from "./shared.part003";

/**
 * Errors identified during CEL expression compilation
 */
export interface CelExpressionError {
  /**
   * Optional `int32`-formatted value serialized in the `column` wire field.
   */
  column?: number;
  /**
   * Optional `int32`-formatted value serialized in the `line` wire field.
   */
  line?: number;
  /**
   * Optional `string` value serialized in the `message` wire field.
   */
  message?: string;
}

/**
 * Typed representation of the `CreateNotificationPublisherRequest` API schema.
 */
export interface CreateNotificationPublisherRequest {
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Required `string` value serialized in the `extensionName` wire field.
   */
  extensionName: string;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `string` value serialized in the `template` wire field.
   */
  template?: string;
  /**
   * Optional `string` value serialized in the `templateMimeType` wire field.
   */
  templateMimeType?: string;
}

/**
 * Typed representation of the `CreateNotificationRuleRequest` API schema.
 */
export interface CreateNotificationRuleRequest {
  /**
   * Required enumerated value serialized in the `level` wire field.
   */
  level: "INFORMATIONAL" | "WARNING" | "ERROR" | (string & {});
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Required object value serialized in the `publisher` wire field.
   */
  publisher: Publisher;
  /**
   * Required enumerated value serialized in the `scope` wire field.
   */
  scope: "SYSTEM" | "PORTFOLIO" | (string & {});
}

/**
 * Typed representation of the `CreateScheduledNotificationRuleRequest` API schema.
 */
export interface CreateScheduledNotificationRuleRequest {
  /**
   * Required enumerated value serialized in the `level` wire field.
   */
  level: "INFORMATIONAL" | "WARNING" | "ERROR" | (string & {});
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Required object value serialized in the `publisher` wire field.
   */
  publisher: Publisher;
  /**
   * Required enumerated value serialized in the `scope` wire field.
   */
  scope: "SYSTEM" | "PORTFOLIO" | (string & {});
}

/**
 * Typed representation of the `DeleteNotificationRuleRequest` API schema.
 */
export interface DeleteNotificationRuleRequest {
  /**
   * UUID of the notification rule to delete
   */
  uuid: string;
}

export type InvalidNotificationFilterExpressionProblemDetails = ProblemDetails & {
  /**
   * Errors identified during CEL expression compilation
   */
  errors?: CelExpressionError[];
};

/**
 * Typed representation of the `NotificationPublisher` API schema.
 */
export interface NotificationPublisher {
  /**
   * Optional `boolean` value serialized in the `defaultPublisher` wire field.
   */
  defaultPublisher?: boolean;
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Required `string` value serialized in the `extensionName` wire field.
   */
  extensionName: string;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `string` value serialized in the `template` wire field.
   */
  template?: string;
  /**
   * Required `string` value serialized in the `templateMimeType` wire field.
   */
  templateMimeType: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}

/**
 * Typed representation of the `NotificationPublisherResponse` API schema.
 */
export interface NotificationPublisherResponse {
  /**
   * Whether the publisher is one of the built-in defaults
   */
  defaultPublisher: boolean;
  /**
   * Description of the notification publisher
   */
  description?: string;
  /**
   * Name of the publisher extension that handles delivery
   */
  extensionName: string;
  /**
   * Name of the notification publisher
   */
  name: string;
  /**
   * Template used to render the notification payload
   */
  template?: string;
  /**
   * MIME type of the rendered template
   */
  templateMimeType: string;
  /**
   * UUID of the notification publisher
   */
  uuid: string;
}

/**
 * Typed representation of the `NotificationRule` API schema.
 */
export interface NotificationRule {
  /**
   * Optional `boolean` value serialized in the `enabled` wire field.
   */
  enabled?: boolean;
  /**
   * Optional `string` value serialized in the `filterExpression` wire field.
   */
  filterExpression?: string;
  /**
   * Optional `boolean` value serialized in the `logSuccessfulPublish` wire field.
   */
  logSuccessfulPublish?: boolean;
  /**
   * Optional `string` value serialized in the `message` wire field.
   */
  message?: string;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional enumerated value serialized in the `notificationLevel` wire field.
   */
  notificationLevel?: "INFORMATIONAL" | "WARNING" | "ERROR" | (string & {});
  /**
   * Optional `boolean` value serialized in the `notifyChildren` wire field.
   */
  notifyChildren?: boolean;
  /**
   * Optional array value serialized in the `notifyOn` wire field.
   */
  notifyOn?: (
    | "CONFIGURATION"
    | "DATASOURCE_MIRRORING"
    | "REPOSITORY"
    | "INTEGRATION"
    | "FILE_SYSTEM"
    | "ANALYZER"
    | "NEW_VULNERABILITY"
    | "NEW_VULNERABLE_DEPENDENCY"
    | "VULNERABILITY_RETRACTED"
    | "PROJECT_AUDIT_CHANGE"
    | "BOM_CONSUMED"
    | "BOM_PROCESSED"
    | "BOM_PROCESSING_FAILED"
    | "BOM_VALIDATION_FAILED"
    | "VEX_CONSUMED"
    | "VEX_PROCESSED"
    | "POLICY_VIOLATION"
    | "PROJECT_CREATED"
    | "USER_CREATED"
    | "USER_DELETED"
    | "NEW_VULNERABILITIES_SUMMARY"
    | "NEW_POLICY_VIOLATIONS_SUMMARY"
    | (string & {})
  )[];
  /**
   * Optional array value serialized in the `projects` wire field.
   */
  projects?: Project[];
  /**
   * Optional object value serialized in the `publisher` wire field.
   */
  publisher?: NotificationPublisher;
  /**
   * Optional `string` value serialized in the `publisherConfig` wire field.
   */
  publisherConfig?: string;
  /**
   * Schedule of this rule as cron expression. Must not be set for rules with trigger type EVENT.
   */
  scheduleCron?: string;
  /**
   * When the schedule last triggered, as UNIX epoch timestamp in milliseconds
   */
  scheduleLastTriggeredAt?: number;
  /**
   * When the schedule triggers next, as UNIX epoch timestamp in milliseconds
   */
  scheduleNextTriggerAt?: number;
  /**
   * Whether to skip emitting a scheduled notification if it doesn't contain any changes since its last emission. Must not be set for rules with trigger type EVENT.
   */
  scheduleSkipUnchanged?: boolean;
  /**
   * Required enumerated value serialized in the `scope` wire field.
   */
  scope: "SYSTEM" | "PORTFOLIO" | (string & {});
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: Tag[];
  /**
   * Optional array value serialized in the `teams` wire field.
   */
  teams?: Team[];
  /**
   * Required enumerated value serialized in the `triggerType` wire field.
   */
  triggerType: "EVENT" | "SCHEDULE" | (string & {});
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}

/**
 * Typed representation of the `Publisher` API schema.
 */
export interface Publisher {
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}

/**
 * Typed representation of the `UpdateNotificationPublisherRequest` API schema.
 */
export interface UpdateNotificationPublisherRequest {
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Required `string` value serialized in the `extensionName` wire field.
   */
  extensionName: string;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `string` value serialized in the `template` wire field.
   */
  template?: string;
  /**
   * Optional `string` value serialized in the `templateMimeType` wire field.
   */
  templateMimeType?: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}

/**
 * Typed representation of the `UpdateNotificationRuleRequest` API schema.
 */
export interface UpdateNotificationRuleRequest {
  /**
   * Optional `boolean` value serialized in the `enabled` wire field.
   */
  enabled?: boolean;
  /**
   * Optional `string` value serialized in the `filterExpression` wire field.
   */
  filterExpression?: string;
  /**
   * Required enumerated value serialized in the `level` wire field.
   */
  level: "INFORMATIONAL" | "WARNING" | "ERROR" | (string & {});
  /**
   * Optional `boolean` value serialized in the `logSuccessfulPublish` wire field.
   */
  logSuccessfulPublish?: boolean;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `boolean` value serialized in the `notifyChildren` wire field.
   */
  notifyChildren?: boolean;
  /**
   * Optional array value serialized in the `notifyOn` wire field.
   */
  notifyOn?: (
    | "CONFIGURATION"
    | "DATASOURCE_MIRRORING"
    | "REPOSITORY"
    | "INTEGRATION"
    | "FILE_SYSTEM"
    | "ANALYZER"
    | "NEW_VULNERABILITY"
    | "NEW_VULNERABLE_DEPENDENCY"
    | "VULNERABILITY_RETRACTED"
    | "PROJECT_AUDIT_CHANGE"
    | "BOM_CONSUMED"
    | "BOM_PROCESSED"
    | "BOM_PROCESSING_FAILED"
    | "BOM_VALIDATION_FAILED"
    | "VEX_CONSUMED"
    | "VEX_PROCESSED"
    | "POLICY_VIOLATION"
    | "PROJECT_CREATED"
    | "USER_CREATED"
    | "USER_DELETED"
    | "NEW_VULNERABILITIES_SUMMARY"
    | "NEW_POLICY_VIOLATIONS_SUMMARY"
    | (string & {})
  )[];
  /**
   * Optional `string` value serialized in the `publisherConfig` wire field.
   */
  publisherConfig?: string;
  /**
   * Optional `string` value serialized in the `scheduleCron` wire field.
   */
  scheduleCron?: string;
  /**
   * Optional `boolean` value serialized in the `scheduleSkipUnchanged` wire field.
   */
  scheduleSkipUnchanged?: boolean;
  /**
   * Required enumerated value serialized in the `scope` wire field.
   */
  scope: "SYSTEM" | "PORTFOLIO" | (string & {});
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: Tag[];
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}
