// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `CreatePolicyConditionRequest` API schema.
 */
export interface CreatePolicyConditionRequest {
  /**
   * Operator used to compare the subject to the value
   */
  operator:
    | "IS"
    | "IS_NOT"
    | "MATCHES"
    | "NO_MATCH"
    | "NUMERIC_GREATER_THAN"
    | "NUMERIC_LESS_THAN"
    | "NUMERIC_EQUAL"
    | "NUMERIC_NOT_EQUAL"
    | "NUMERIC_GREATER_THAN_OR_EQUAL"
    | "NUMERIC_LESSER_THAN_OR_EQUAL"
    | "CONTAINS_ALL"
    | "CONTAINS_ANY"
    | (string & {});
  /**
   * Subject the condition evaluates
   */
  subject:
    | "AGE"
    | "COORDINATES"
    | "CPE"
    | "EXPRESSION"
    | "LICENSE"
    | "LICENSE_GROUP"
    | "PACKAGE_URL"
    | "SEVERITY"
    | "SWID_TAGID"
    | "VERSION"
    | "COMPONENT_HASH"
    | "IS_INTERNAL"
    | "CWE"
    | "VULNERABILITY_ID"
    | "VERSION_DISTANCE"
    | "EPSS"
    | (string & {});
  /**
   * Value the subject is compared to
   */
  value: string;
  /**
   * Violation type produced when the condition matches. Required for `EXPRESSION` subjects
   */
  violationType?: "LICENSE" | "SECURITY" | "OPERATIONAL" | (string & {});
}

/**
 * Typed representation of the `PolicyConditionResponse` API schema.
 */
export interface PolicyConditionResponse {
  /**
   * Operator used to compare the subject to the value
   */
  operator:
    | "IS"
    | "IS_NOT"
    | "MATCHES"
    | "NO_MATCH"
    | "NUMERIC_GREATER_THAN"
    | "NUMERIC_LESS_THAN"
    | "NUMERIC_EQUAL"
    | "NUMERIC_NOT_EQUAL"
    | "NUMERIC_GREATER_THAN_OR_EQUAL"
    | "NUMERIC_LESSER_THAN_OR_EQUAL"
    | "CONTAINS_ALL"
    | "CONTAINS_ANY"
    | (string & {});
  /**
   * Subject the condition evaluates
   */
  subject:
    | "AGE"
    | "COORDINATES"
    | "CPE"
    | "EXPRESSION"
    | "LICENSE"
    | "LICENSE_GROUP"
    | "PACKAGE_URL"
    | "SEVERITY"
    | "SWID_TAGID"
    | "VERSION"
    | "COMPONENT_HASH"
    | "IS_INTERNAL"
    | "CWE"
    | "VULNERABILITY_ID"
    | "VERSION_DISTANCE"
    | "EPSS"
    | (string & {});
  /**
   * UUID of the policy condition
   */
  uuid: string;
  /**
   * Value the subject is compared to
   */
  value: string;
  /**
   * Violation type produced when the condition matches
   */
  violationType?: "LICENSE" | "SECURITY" | "OPERATIONAL" | (string & {});
}

/**
 * Typed representation of the `UpdatePolicyConditionRequest` API schema.
 */
export interface UpdatePolicyConditionRequest {
  /**
   * Operator used to compare the subject to the value
   */
  operator:
    | "IS"
    | "IS_NOT"
    | "MATCHES"
    | "NO_MATCH"
    | "NUMERIC_GREATER_THAN"
    | "NUMERIC_LESS_THAN"
    | "NUMERIC_EQUAL"
    | "NUMERIC_NOT_EQUAL"
    | "NUMERIC_GREATER_THAN_OR_EQUAL"
    | "NUMERIC_LESSER_THAN_OR_EQUAL"
    | "CONTAINS_ALL"
    | "CONTAINS_ANY"
    | (string & {});
  /**
   * Subject the condition evaluates
   */
  subject:
    | "AGE"
    | "COORDINATES"
    | "CPE"
    | "EXPRESSION"
    | "LICENSE"
    | "LICENSE_GROUP"
    | "PACKAGE_URL"
    | "SEVERITY"
    | "SWID_TAGID"
    | "VERSION"
    | "COMPONENT_HASH"
    | "IS_INTERNAL"
    | "CWE"
    | "VULNERABILITY_ID"
    | "VERSION_DISTANCE"
    | "EPSS"
    | (string & {});
  /**
   * UUID of the policy condition to update
   */
  uuid: string;
  /**
   * Value the subject is compared to
   */
  value: string;
  /**
   * Violation type produced when the condition matches. Required for `EXPRESSION` subjects
   */
  violationType?: "LICENSE" | "SECURITY" | "OPERATIONAL" | (string & {});
}
