// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `CreateRepositoryRequest` API schema.
 */
export interface CreateRepositoryRequest {
  /**
   * Whether the repository requires authentication
   */
  authenticationRequired: boolean;
  /**
   * Whether the repository is enabled
   */
  enabled: boolean;
  /**
   * Unique identifier of the repository within its type
   */
  identifier: string;
  /**
   * Whether the repository is internal to the organization
   */
  internal?: boolean;
  /**
   * Name of the secret holding the password or token
   */
  password?: string;
  /**
   * Type of the repository
   */
  type:
    | "MAVEN"
    | "NPM"
    | "GEM"
    | "PYPI"
    | "NUGET"
    | "HEX"
    | "COMPOSER"
    | "CARGO"
    | "GO_MODULES"
    | "CPAN"
    | "GITHUB"
    | "HACKAGE"
    | "NIXPKGS"
    | "UNSUPPORTED"
    | (string & {});
  /**
   * URL of the repository
   */
  url: string;
  /**
   * Username to authenticate with
   */
  username?: string;
}

/**
 * Typed representation of the `RepositoryResponse` API schema.
 */
export interface RepositoryResponse {
  /**
   * Whether the repository requires authentication
   */
  authenticationRequired: boolean;
  /**
   * Whether the repository is enabled
   */
  enabled: boolean;
  /**
   * Unique identifier of the repository within its type
   */
  identifier: string;
  /**
   * Whether the repository is internal to the organization
   */
  internal?: boolean;
  /**
   * Name of the secret holding the password or token
   */
  password?: string;
  /**
   * Order in which the repository is queried during version resolution
   */
  resolutionOrder: number;
  /**
   * Type of the repository
   */
  type:
    | "MAVEN"
    | "NPM"
    | "GEM"
    | "PYPI"
    | "NUGET"
    | "HEX"
    | "COMPOSER"
    | "CARGO"
    | "GO_MODULES"
    | "CPAN"
    | "GITHUB"
    | "HACKAGE"
    | "NIXPKGS"
    | "UNSUPPORTED"
    | (string & {});
  /**
   * URL of the repository
   */
  url: string;
  /**
   * Username to authenticate with
   */
  username?: string;
  /**
   * UUID of the repository
   */
  uuid: string;
}

/**
 * Typed representation of the `UpdateRepositoryRequest` API schema.
 */
export interface UpdateRepositoryRequest {
  /**
   * Whether the repository requires authentication
   */
  authenticationRequired: boolean;
  /**
   * Whether the repository is enabled
   */
  enabled: boolean;
  /**
   * Whether the repository is internal to the organization
   */
  internal?: boolean;
  /**
   * Name of the secret holding the password or token
   */
  password?: string;
  /**
   * URL of the repository
   */
  url: string;
  /**
   * Username to authenticate with
   */
  username?: string;
  /**
   * UUID of the repository to update
   */
  uuid: string;
}
