// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { OidcGroup } from "./shared-oidc";

/**
 * Typed representation of the `MappedLdapGroup` API schema.
 */
export interface MappedLdapGroup {
  /**
   * Required `string` value serialized in the `dn` wire field.
   */
  dn: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}

/**
 * Typed representation of the `MappedOidcGroup` API schema.
 */
export interface MappedOidcGroup {
  /**
   * Optional object value serialized in the `group` wire field.
   */
  group?: OidcGroup;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}
