// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ComponentProperty } from "./shared-component";

import type { License } from "./shared-license";

import type { OrganizationalContact, OrganizationalEntity } from "./shared-organizational";

import type { Permission, Project, RepositoryMetaComponent } from "./shared.part002";

import type { Team, Vulnerability } from "./shared.part003";

/**
 * Typed representation of the `ApiKey` API schema.
 */
export interface ApiKey {
  /**
   * Optional `string` value serialized in the `comment` wire field.
   */
  comment?: string;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  created?: number;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  expiresAt?: number;
  /**
   * Optional `string` value serialized in the `key` wire field.
   */
  key?: string;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastUsed?: number;
  /**
   * Optional `boolean` value serialized in the `legacy` wire field.
   */
  legacy?: boolean;
  /**
   * Optional `string` value serialized in the `maskedKey` wire field.
   */
  maskedKey?: string;
  /**
   * Optional `string` value serialized in the `publicId` wire field.
   */
  publicId?: string;
}

/**
 * Typed representation of the `BomUploadResponse` API schema.
 */
export interface BomUploadResponse {
  /**
   * UUID of the project the BOM was uploaded for
   */
  projectUuid: string;
  /**
   * Token used to check task progress
   */
  token: string;
}

/**
 * Audit trail of analysis comments
 */
export interface Comment {
  /**
   * The comment text
   */
  comment: string;
  /**
   * Identifier of the user who wrote the comment
   */
  commenter?: string;
  /**
   * Timestamp the comment was recorded at
   */
  timestamp: number;
}

/**
 * Typed representation of the `Component` API schema.
 */
export interface Component {
  /**
   * Optional `string` value serialized in the `author` wire field.
   */
  author?: string;
  /**
   * Optional array value serialized in the `authors` wire field.
   */
  authors?: OrganizationalContact[];
  /**
   * Optional `string` value serialized in the `blake2b_256` wire field.
   */
  blake2b256?: string;
  /**
   * Optional `string` value serialized in the `blake2b_384` wire field.
   */
  blake2b384?: string;
  /**
   * Optional `string` value serialized in the `blake2b_512` wire field.
   */
  blake2b512?: string;
  /**
   * Optional `string` value serialized in the `blake3` wire field.
   */
  blake3?: string;
  /**
   * Optional array value serialized in the `children` wire field.
   */
  children?: Component[];
  /**
   * Required enumerated value serialized in the `classifier` wire field.
   */
  classifier:
    | "APPLICATION"
    | "FRAMEWORK"
    | "LIBRARY"
    | "CONTAINER"
    | "OPERATING_SYSTEM"
    | "DEVICE"
    | "FIRMWARE"
    | "FILE"
    | "PLATFORM"
    | "DEVICE_DRIVER"
    | "MACHINE_LEARNING_MODEL"
    | "DATA"
    | "CRYPTOGRAPHIC_ASSET"
    | (string & {});
  /**
   * Optional `string` value serialized in the `copyright` wire field.
   */
  copyright?: string;
  /**
   * Optional `string` value serialized in the `cpe` wire field.
   */
  cpe?: string;
  /**
   * Optional array value serialized in the `dependencyGraph` wire field.
   */
  dependencyGraph?: string[];
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional `string` value serialized in the `directDependencies` wire field.
   */
  directDependencies?: string;
  /**
   * Optional `boolean` value serialized in the `expandDependencyGraph` wire field.
   */
  expandDependencyGraph?: boolean;
  /**
   * Optional `string` value serialized in the `extension` wire field.
   */
  extension?: string;
  /**
   * Optional array value serialized in the `externalReferences` wire field.
   */
  externalReferences?: ExternalReference[];
  /**
   * Optional `string` value serialized in the `filename` wire field.
   */
  filename?: string;
  /**
   * Optional `string` value serialized in the `group` wire field.
   */
  group?: string;
  /**
   * Optional `boolean` value serialized in the `isInternal` wire field.
   */
  isInternal?: boolean;
  /**
   * Optional `double`-formatted value serialized in the `lastInheritedRiskScore` wire field.
   */
  lastInheritedRiskScore?: number;
  /**
   * Optional `string` value serialized in the `license` wire field.
   */
  license?: string;
  /**
   * Optional `string` value serialized in the `licenseExpression` wire field.
   */
  licenseExpression?: string;
  /**
   * Optional `string` value serialized in the `licenseUrl` wire field.
   */
  licenseUrl?: string;
  /**
   * Optional `string` value serialized in the `md5` wire field.
   */
  md5?: string;
  /**
   * Optional object value serialized in the `metrics` wire field.
   */
  metrics?: DependencyMetrics;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `string` value serialized in the `notes` wire field.
   */
  notes?: string;
  /**
   * Optional `int64`-formatted value serialized in the `occurrenceCount` wire field.
   */
  occurrenceCount?: number;
  /**
   * Optional object value serialized in the `parent` wire field.
   */
  parent?: Component;
  /**
   * Required object value serialized in the `project` wire field.
   */
  project: Project;
  /**
   * Optional array value serialized in the `properties` wire field.
   */
  properties?: ComponentProperty[];
  /**
   * Optional `string` value serialized in the `publisher` wire field.
   */
  publisher?: string;
  /**
   * Optional `string` value serialized in the `purl` wire field.
   */
  purl?: string;
  /**
   * Optional `string` value serialized in the `purlCoordinates` wire field.
   */
  purlCoordinates?: string;
  /**
   * Optional object value serialized in the `repositoryMeta` wire field.
   */
  repositoryMeta?: RepositoryMetaComponent;
  /**
   * Optional object value serialized in the `resolvedLicense` wire field.
   */
  resolvedLicense?: License;
  /**
   * Optional enumerated value serialized in the `scope` wire field.
   */
  scope?: "REQUIRED" | "OPTIONAL" | "EXCLUDED" | (string & {});
  /**
   * Optional `string` value serialized in the `sha1` wire field.
   */
  sha1?: string;
  /**
   * Optional `string` value serialized in the `sha256` wire field.
   */
  sha256?: string;
  /**
   * Optional `string` value serialized in the `sha384` wire field.
   */
  sha384?: string;
  /**
   * Optional `string` value serialized in the `sha3_256` wire field.
   */
  sha3256?: string;
  /**
   * Optional `string` value serialized in the `sha3_384` wire field.
   */
  sha3384?: string;
  /**
   * Optional `string` value serialized in the `sha3_512` wire field.
   */
  sha3512?: string;
  /**
   * Optional `string` value serialized in the `sha512` wire field.
   */
  sha512?: string;
  /**
   * Optional `string` value serialized in the `streebog_256` wire field.
   */
  streebog256?: string;
  /**
   * Optional `string` value serialized in the `streebog_512` wire field.
   */
  streebog512?: string;
  /**
   * Optional object value serialized in the `supplier` wire field.
   */
  supplier?: OrganizationalEntity;
  /**
   * Optional `string` value serialized in the `swidTagId` wire field.
   */
  swidTagId?: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Optional `string` value serialized in the `version` wire field.
   */
  version?: string;
  /**
   * Optional array value serialized in the `vulnerabilities` wire field.
   */
  vulnerabilities?: Vulnerability[];
}

/**
 * Typed representation of the `Cwe` API schema.
 */
export interface Cwe {
  /**
   * Optional `int32`-formatted value serialized in the `cweId` wire field.
   */
  cweId?: number;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
}

/**
 * Typed representation of the `DataClassification` API schema.
 */
export interface DataClassification {
  /**
   * Optional enumerated value serialized in the `direction` wire field.
   */
  direction?: "INBOUND" | "OUTBOUND" | "BI_DIRECTIONAL" | "UNKNOWN" | (string & {});
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
}

/**
 * Typed representation of the `DependencyMetrics` API schema.
 */
export interface DependencyMetrics {
  /**
   * Optional `int32`-formatted value serialized in the `critical` wire field.
   */
  critical?: number;
  /**
   * Optional `int32`-formatted value serialized in the `findingsAudited` wire field.
   */
  findingsAudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `findingsTotal` wire field.
   */
  findingsTotal?: number;
  /**
   * Optional `int32`-formatted value serialized in the `findingsUnaudited` wire field.
   */
  findingsUnaudited?: number;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  firstOccurrence: number;
  /**
   * Optional `int32`-formatted value serialized in the `high` wire field.
   */
  high?: number;
  /**
   * Optional `double`-formatted value serialized in the `inheritedRiskScore` wire field.
   */
  inheritedRiskScore?: number;
  /**
   * Optional `int32`-formatted value serialized in the `kev` wire field.
   */
  kev?: number;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastOccurrence: number;
  /**
   * Optional `int32`-formatted value serialized in the `low` wire field.
   */
  low?: number;
  /**
   * Optional `int32`-formatted value serialized in the `medium` wire field.
   */
  medium?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsAudited` wire field.
   */
  policyViolationsAudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsFail` wire field.
   */
  policyViolationsFail?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsInfo` wire field.
   */
  policyViolationsInfo?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsLicenseAudited` wire field.
   */
  policyViolationsLicenseAudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsLicenseTotal` wire field.
   */
  policyViolationsLicenseTotal?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsLicenseUnaudited` wire field.
   */
  policyViolationsLicenseUnaudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsOperationalAudited` wire field.
   */
  policyViolationsOperationalAudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsOperationalTotal` wire field.
   */
  policyViolationsOperationalTotal?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsOperationalUnaudited` wire field.
   */
  policyViolationsOperationalUnaudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsSecurityAudited` wire field.
   */
  policyViolationsSecurityAudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsSecurityTotal` wire field.
   */
  policyViolationsSecurityTotal?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsSecurityUnaudited` wire field.
   */
  policyViolationsSecurityUnaudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsTotal` wire field.
   */
  policyViolationsTotal?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsUnaudited` wire field.
   */
  policyViolationsUnaudited?: number;
  /**
   * Optional `int32`-formatted value serialized in the `policyViolationsWarn` wire field.
   */
  policyViolationsWarn?: number;
  /**
   * Optional `int32`-formatted value serialized in the `suppressed` wire field.
   */
  suppressed?: number;
  /**
   * Optional `int32`-formatted value serialized in the `unassigned` wire field.
   */
  unassigned?: number;
  /**
   * Optional `int32`-formatted value serialized in the `vulnerabilities` wire field.
   */
  vulnerabilities?: number;
}

/**
 * Typed representation of the `Epss` API schema.
 */
export interface Epss {
  /**
   * Optional `string` value serialized in the `cve` wire field.
   */
  cve?: string;
  /**
   * Optional `number` value serialized in the `percentile` wire field.
   */
  percentile?: number;
  /**
   * Optional `number` value serialized in the `score` wire field.
   */
  score?: number;
}

/**
 * Typed representation of the `ExternalReference` API schema.
 */
export interface ExternalReference {
  /**
   * Optional `string` value serialized in the `comment` wire field.
   */
  comment?: string;
  /**
   * Optional enumerated value serialized in the `type` wire field.
   */
  type?:
    | "vcs"
    | "issue-tracker"
    | "website"
    | "advisories"
    | "bom"
    | "mailing-list"
    | "social"
    | "chat"
    | "documentation"
    | "support"
    | "source-distribution"
    | "distribution"
    | "distribution-intake"
    | "license"
    | "build-meta"
    | "build-system"
    | "release-notes"
    | "security-contact"
    | "model-card"
    | "attestation"
    | "threat-model"
    | "adversary-model"
    | "risk-assessment"
    | "vulnerability-assertion"
    | "exploitability-statement"
    | "pentest-report"
    | "static-analysis-report"
    | "dynamic-analysis-report"
    | "runtime-analysis-report"
    | "component-analysis-report"
    | "maturity-report"
    | "certification-report"
    | "codified-infrastructure"
    | "quality-metrics"
    | "log"
    | "configuration"
    | "evidence"
    | "formulation"
    | "rfc-9116"
    | "electronic-signature"
    | "digital-signature"
    | "patent"
    | "patent-family"
    | "patent-assertion"
    | "citation"
    | "poam"
    | "other"
    | (string & {});
  /**
   * Required `string` value serialized in the `url` wire field.
   */
  url: string;
}

/**
 * Typed representation of the `IsTokenBeingProcessedResponse` API schema.
 */
export interface IsTokenBeingProcessedResponse {
  /**
   * Required `boolean` value serialized in the `processing` wire field.
   */
  processing: boolean;
  /**
   * The processing status associated with the token. Null when no processing is associated with the token.
   */
  status?: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | (string & {}) | null;
}

/**
 * Typed representation of the `LdapUser` API schema.
 */
export interface LdapUser {
  /**
   * Optional `string` value serialized in the `dn` wire field.
   */
  dn?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional array value serialized in the `teams` wire field.
   */
  teams?: Team[];
  /**
   * Required `string` value serialized in the `username` wire field.
   */
  username: string;
}
