// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ComponentProperty` API schema.
 */
export interface ComponentProperty {
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional `string` value serialized in the `groupName` wire field.
   */
  groupName?: string;
  /**
   * Required `string` value serialized in the `propertyName` wire field.
   */
  propertyName: string;
  /**
   * Required enumerated value serialized in the `propertyType` wire field.
   */
  propertyType:
    | "BOOLEAN"
    | "INTEGER"
    | "NUMBER"
    | "STRING"
    | "TIMESTAMP"
    | "URL"
    | "UUID"
    | (string & {});
  /**
   * Optional `string` value serialized in the `propertyValue` wire field.
   */
  propertyValue?: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}
