// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Project, Tag } from "./shared.part002";

/**
 * Typed representation of the `Policy` API schema.
 */
export interface Policy {
  /**
   * Optional `boolean` value serialized in the `global` wire field.
   */
  global?: boolean;
  /**
   * Optional `boolean` value serialized in the `includeChildren` wire field.
   */
  includeChildren?: boolean;
  /**
   * Optional `boolean` value serialized in the `invertTagMatch` wire field.
   */
  invertTagMatch?: boolean;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `boolean` value serialized in the `onlyLatestProjectVersion` wire field.
   */
  onlyLatestProjectVersion?: boolean;
  /**
   * Required enumerated value serialized in the `operator` wire field.
   */
  operator: "ALL" | "ANY" | (string & {});
  /**
   * Optional array value serialized in the `policyConditions` wire field.
   */
  policyConditions?: PolicyCondition[];
  /**
   * Optional array value serialized in the `projects` wire field.
   */
  projects?: Project[];
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: Tag[];
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Required enumerated value serialized in the `violationState` wire field.
   */
  violationState: "INFO" | "WARN" | "FAIL" | (string & {});
}

/**
 * Typed representation of the `PolicyCondition` API schema.
 */
export interface PolicyCondition {
  /**
   * Required enumerated value serialized in the `operator` wire field.
   */
  operator:
    | "IS"
    | "IS_NOT"
    | "MATCHES"
    | "NO_MATCH"
    | "NUMERIC_GREATER_THAN"
    | "NUMERIC_LESS_THAN"
    | "NUMERIC_EQUAL"
    | "NUMERIC_NOT_EQUAL"
    | "NUMERIC_GREATER_THAN_OR_EQUAL"
    | "NUMERIC_LESSER_THAN_OR_EQUAL"
    | "CONTAINS_ALL"
    | "CONTAINS_ANY"
    | (string & {});
  /**
   * Optional object value serialized in the `policy` wire field.
   */
  policy?: Policy;
  /**
   * Required enumerated value serialized in the `subject` wire field.
   */
  subject:
    | "AGE"
    | "COORDINATES"
    | "CPE"
    | "EXPRESSION"
    | "LICENSE"
    | "LICENSE_GROUP"
    | "PACKAGE_URL"
    | "SEVERITY"
    | "SWID_TAGID"
    | "VERSION"
    | "COMPONENT_HASH"
    | "IS_INTERNAL"
    | "CWE"
    | "VULNERABILITY_ID"
    | "VERSION_DISTANCE"
    | "EPSS"
    | (string & {});
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Required `string` value serialized in the `value` wire field.
   */
  value: string;
  /**
   * Optional enumerated value serialized in the `violationType` wire field.
   */
  violationType?: "LICENSE" | "SECURITY" | "OPERATIONAL" | (string & {});
}
