// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { AffectedComponent } from "./shared-affected";

import type { MappedLdapGroup, MappedOidcGroup } from "./shared-mapped";

import type { VulnerabilityAlias } from "./shared-vulnerability";

import type { ApiKey, Component, Cwe, Epss, LdapUser } from "./shared.part001";

import type {
  ManagedUser,
  OidcUser,
  Permission,
  ServiceAccount,
  ServiceComponent,
  Tag,
} from "./shared.part002";

/**
 * Typed representation of the `Team` API schema.
 */
export interface Team {
  /**
   * Optional array value serialized in the `apiKeys` wire field.
   */
  apiKeys?: ApiKey[];
  /**
   * Optional array value serialized in the `ldapUsers` wire field.
   */
  ldapUsers?: LdapUser[];
  /**
   * Optional array value serialized in the `managedUsers` wire field.
   */
  managedUsers?: ManagedUser[];
  /**
   * Optional array value serialized in the `mappedLdapGroups` wire field.
   */
  mappedLdapGroups?: MappedLdapGroup[];
  /**
   * Optional array value serialized in the `mappedOidcGroups` wire field.
   */
  mappedOidcGroups?: MappedOidcGroup[];
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional array value serialized in the `oidcUsers` wire field.
   */
  oidcUsers?: OidcUser[];
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional array value serialized in the `serviceAccounts` wire field.
   */
  serviceAccounts?: ServiceAccount[];
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
}

/**
 * Typed representation of the `Tools` API schema.
 */
export interface Tools {
  /**
   * Optional array value serialized in the `components` wire field.
   */
  components?: Component[];
  /**
   * Optional array value serialized in the `services` wire field.
   */
  services?: ServiceComponent[];
}

/**
 * Typed representation of the `User` API schema.
 */
export interface User {
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional array value serialized in the `teams` wire field.
   */
  teams?: Team[];
  /**
   * Required `string` value serialized in the `username` wire field.
   */
  username: string;
}

/**
 * Typed representation of the `Vulnerability` API schema.
 */
export interface Vulnerability {
  /**
   * Optional `int32`-formatted value serialized in the `affectedActiveProjectCount` wire field.
   */
  affectedActiveProjectCount?: number;
  /**
   * Optional array value serialized in the `affectedComponents` wire field.
   */
  affectedComponents?: AffectedComponent[];
  /**
   * Optional `int32`-formatted value serialized in the `affectedInactiveProjectCount` wire field.
   */
  affectedInactiveProjectCount?: number;
  /**
   * Optional `int32`-formatted value serialized in the `affectedProjectCount` wire field.
   */
  affectedProjectCount?: number;
  /**
   * Optional array value serialized in the `aliases` wire field.
   */
  aliases?: VulnerabilityAlias[];
  /**
   * Optional array value serialized in the `components` wire field.
   */
  components?: Component[];
  /**
   * Optional `date-time`-formatted value serialized in the `created` wire field.
   */
  created?: string;
  /**
   * Optional `string` value serialized in the `credits` wire field.
   */
  credits?: string;
  /**
   * Optional `number` value serialized in the `cvssV2BaseScore` wire field.
   */
  cvssV2BaseScore?: number;
  /**
   * Optional `number` value serialized in the `cvssV2ExploitabilitySubScore` wire field.
   */
  cvssV2ExploitabilitySubScore?: number;
  /**
   * Optional `number` value serialized in the `cvssV2ImpactSubScore` wire field.
   */
  cvssV2ImpactSubScore?: number;
  /**
   * Optional `string` value serialized in the `cvssV2Vector` wire field.
   */
  cvssV2Vector?: string;
  /**
   * Optional `number` value serialized in the `cvssV3BaseScore` wire field.
   */
  cvssV3BaseScore?: number;
  /**
   * Optional `number` value serialized in the `cvssV3ExploitabilitySubScore` wire field.
   */
  cvssV3ExploitabilitySubScore?: number;
  /**
   * Optional `number` value serialized in the `cvssV3ImpactSubScore` wire field.
   */
  cvssV3ImpactSubScore?: number;
  /**
   * Optional `string` value serialized in the `cvssV3Vector` wire field.
   */
  cvssV3Vector?: string;
  /**
   * Optional `number` value serialized in the `cvssV4Score` wire field.
   */
  cvssV4Score?: number;
  /**
   * Optional `string` value serialized in the `cvssV4Vector` wire field.
   */
  cvssV4Vector?: string;
  /**
   * Optional array value serialized in the `cwes` wire field.
   */
  cwes?: Cwe[];
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional `string` value serialized in the `detail` wire field.
   */
  detail?: string;
  /**
   * Optional object value serialized in the `epss` wire field.
   */
  epss?: Epss;
  /**
   * Optional `number` value serialized in the `epssPercentile` wire field.
   */
  epssPercentile?: number;
  /**
   * Optional `number` value serialized in the `epssScore` wire field.
   */
  epssScore?: number;
  /**
   * Required `string` value serialized in the `friendlyVulnId` wire field.
   */
  friendlyVulnId: string;
  /**
   * Optional `boolean` value serialized in the `isKev` wire field.
   */
  isKev?: boolean;
  /**
   * Optional `number` value serialized in the `owaspRRBusinessImpactScore` wire field.
   */
  owaspRrBusinessImpactScore?: number;
  /**
   * Optional `number` value serialized in the `owaspRRLikelihoodScore` wire field.
   */
  owaspRrLikelihoodScore?: number;
  /**
   * Optional `number` value serialized in the `owaspRRTechnicalImpactScore` wire field.
   */
  owaspRrTechnicalImpactScore?: number;
  /**
   * Optional `string` value serialized in the `owaspRRVector` wire field.
   */
  owaspRrVector?: string;
  /**
   * Optional `string` value serialized in the `patchedVersions` wire field.
   */
  patchedVersions?: string;
  /**
   * Optional `date-time`-formatted value serialized in the `published` wire field.
   */
  published?: string;
  /**
   * Optional `string` value serialized in the `recommendation` wire field.
   */
  recommendation?: string;
  /**
   * Optional `string` value serialized in the `references` wire field.
   */
  references?: string;
  /**
   * Optional `date-time`-formatted value serialized in the `rejected` wire field.
   */
  rejected?: string;
  /**
   * Optional array value serialized in the `serviceComponents` wire field.
   */
  serviceComponents?: ServiceComponent[];
  /**
   * Optional enumerated value serialized in the `severity` wire field.
   */
  severity?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO" | "UNASSIGNED" | (string & {});
  /**
   * Required `string` value serialized in the `source` wire field.
   */
  source: string;
  /**
   * Optional `string` value serialized in the `subTitle` wire field.
   */
  subTitle?: string;
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: Tag[];
  /**
   * Optional `string` value serialized in the `title` wire field.
   */
  title?: string;
  /**
   * Optional `date-time`-formatted value serialized in the `updated` wire field.
   */
  updated?: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Required `string` value serialized in the `vulnId` wire field.
   */
  vulnId: string;
  /**
   * Optional `string` value serialized in the `vulnerableVersions` wire field.
   */
  vulnerableVersions?: string;
}
