// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { OrganizationalContact, OrganizationalEntity } from "./shared-organizational";

import type { ProjectMetrics, ProjectVersion } from "./shared-project";

import type { DataClassification, ExternalReference, LdapUser } from "./shared.part001";

import type { Team, Tools, Vulnerability } from "./shared.part003";

/**
 * Typed representation of the `ListProjectsResponseItem` API schema.
 */
export interface ListProjectsResponseItem {
  /**
   * Optional `boolean` value serialized in the `active` wire field.
   */
  active?: boolean;
  /**
   * Optional array value serialized in the `authors` wire field.
   */
  authors?: OrganizationalContact[];
  /**
   * Optional enumerated value serialized in the `classifier` wire field.
   */
  classifier?:
    | "APPLICATION"
    | "FRAMEWORK"
    | "LIBRARY"
    | "CONTAINER"
    | "OPERATING_SYSTEM"
    | "DEVICE"
    | "FIRMWARE"
    | "FILE"
    | "PLATFORM"
    | "DEVICE_DRIVER"
    | "MACHINE_LEARNING_MODEL"
    | "DATA"
    | "CRYPTOGRAPHIC_ASSET"
    | (string & {});
  /**
   * Optional enumerated value serialized in the `collectionLogic` wire field.
   */
  collectionLogic?:
    | "AGGREGATE_DIRECT_CHILDREN"
    | "AGGREGATE_DIRECT_CHILDREN_WITH_TAG"
    | "AGGREGATE_LATEST_VERSION_CHILDREN"
    | (string & {});
  /**
   * Optional object value serialized in the `collectionTag` wire field.
   */
  collectionTag?: Tag;
  /**
   * Optional `string` value serialized in the `cpe` wire field.
   */
  cpe?: string;
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional `string` value serialized in the `directDependencies` wire field.
   */
  directDependencies?: string;
  /**
   * Optional array value serialized in the `externalReferences` wire field.
   */
  externalReferences?: ExternalReference[];
  /**
   * Optional `string` value serialized in the `group` wire field.
   */
  group?: string;
  /**
   * Whether the project has child projects
   */
  hasChildren: boolean;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  inactiveSince?: number;
  /**
   * Optional `boolean` value serialized in the `isLatest` wire field.
   */
  isLatest?: boolean;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastBomImport: number;
  /**
   * Optional `string` value serialized in the `lastBomImportFormat` wire field.
   */
  lastBomImportFormat?: string;
  /**
   * Optional `double`-formatted value serialized in the `lastInheritedRiskScore` wire field.
   */
  lastInheritedRiskScore?: number;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastVulnerabilityAnalysis?: number;
  /**
   * Optional object value serialized in the `manufacturer` wire field.
   */
  manufacturer?: OrganizationalEntity;
  /**
   * Optional object value serialized in the `metadata` wire field.
   */
  metadata?: ProjectMetadata;
  /**
   * Optional object value serialized in the `metrics` wire field.
   */
  metrics?: ProjectMetrics;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional object value serialized in the `parent` wire field.
   */
  parent?: Parent;
  /**
   * Optional `string` value serialized in the `publisher` wire field.
   */
  publisher?: string;
  /**
   * Optional `string` value serialized in the `purl` wire field.
   */
  purl?: string;
  /**
   * Optional object value serialized in the `supplier` wire field.
   */
  supplier?: OrganizationalEntity;
  /**
   * Optional `string` value serialized in the `swidTagId` wire field.
   */
  swidTagId?: string;
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: Tag[];
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Optional `string` value serialized in the `version` wire field.
   */
  version?: string;
}

/**
 * Typed representation of the `ManagedUser` API schema.
 */
export interface ManagedUser {
  /**
   * Optional `string` value serialized in the `confirmPassword` wire field.
   */
  confirmPassword?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `boolean` value serialized in the `forcePasswordChange` wire field.
   */
  forcePasswordChange?: boolean;
  /**
   * Optional `string` value serialized in the `fullname` wire field.
   */
  fullname?: string;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastPasswordChange: number;
  /**
   * Optional `string` value serialized in the `newPassword` wire field.
   */
  newPassword?: string;
  /**
   * Optional `boolean` value serialized in the `nonExpiryPassword` wire field.
   */
  nonExpiryPassword?: boolean;
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional `boolean` value serialized in the `suspended` wire field.
   */
  suspended?: boolean;
  /**
   * Optional array value serialized in the `teams` wire field.
   */
  teams?: Team[];
  /**
   * Required `string` value serialized in the `username` wire field.
   */
  username: string;
}

/**
 * Typed representation of the `OidcUser` API schema.
 */
export interface OidcUser {
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional `string` value serialized in the `subjectIdentifier` wire field.
   */
  subjectIdentifier?: string;
  /**
   * Optional array value serialized in the `teams` wire field.
   */
  teams?: Team[];
  /**
   * Required `string` value serialized in the `username` wire field.
   */
  username: string;
}

/**
 * Typed representation of the `Parent` API schema.
 */
export interface Parent {
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Optional `string` value serialized in the `version` wire field.
   */
  version?: string;
}

/**
 * Typed representation of the `Permission` API schema.
 */
export interface Permission {
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional array value serialized in the `ldapUsers` wire field.
   */
  ldapUsers?: LdapUser[];
  /**
   * Optional array value serialized in the `managedUsers` wire field.
   */
  managedUsers?: ManagedUser[];
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional array value serialized in the `oidcUsers` wire field.
   */
  oidcUsers?: OidcUser[];
}

/**
 * An RFC 9457 problem object
 */
export interface ProblemDetails {
  /**
   * Human-readable explanation specific to this occurrence of the problem

   * @example "Example detail"
   */
  detail: string;
  /**
   * Reference URI that identifies the specific occurrence of the problem

   * @example "https://api.example.org/foo/bar/example-instance"
   */
  instance?: string;
  /**
   * HTTP status code generated by the origin server for this occurrence of the problem

   * @example 400
   */
  status: number;
  /**
   * Short, human-readable summary of the problem type

   * @example "Example title"
   */
  title: string;
  /**
   * A URI reference that identifies the problem type

   * @example "https://api.example.org/foo/bar/example-problem"
   */
  type?: string;
}

/**
 * Typed representation of the `Project` API schema.
 */
export interface Project {
  /**
   * Optional array value serialized in the `accessTeams` wire field.
   */
  accessTeams?: Team[];
  /**
   * Optional `boolean` value serialized in the `active` wire field.
   */
  active?: boolean;
  /**
   * Optional `string` value serialized in the `author` wire field.
   */
  author?: string;
  /**
   * Optional array value serialized in the `authors` wire field.
   */
  authors?: OrganizationalContact[];
  /**
   * Optional `string` value serialized in the `bomRef` wire field.
   */
  bomRef?: string;
  /**
   * Optional array value serialized in the `children` wire field.
   */
  children?: Project[];
  /**
   * Optional enumerated value serialized in the `classifier` wire field.
   */
  classifier?:
    | "APPLICATION"
    | "FRAMEWORK"
    | "LIBRARY"
    | "CONTAINER"
    | "OPERATING_SYSTEM"
    | "DEVICE"
    | "FIRMWARE"
    | "FILE"
    | "PLATFORM"
    | "DEVICE_DRIVER"
    | "MACHINE_LEARNING_MODEL"
    | "DATA"
    | "CRYPTOGRAPHIC_ASSET"
    | (string & {});
  /**
   * Optional enumerated value serialized in the `collectionLogic` wire field.
   */
  collectionLogic?:
    | "AGGREGATE_DIRECT_CHILDREN"
    | "AGGREGATE_DIRECT_CHILDREN_WITH_TAG"
    | "AGGREGATE_LATEST_VERSION_CHILDREN"
    | (string & {});
  /**
   * Optional object value serialized in the `collectionTag` wire field.
   */
  collectionTag?: Tag;
  /**
   * Optional `string` value serialized in the `cpe` wire field.
   */
  cpe?: string;
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional `string` value serialized in the `directDependencies` wire field.
   */
  directDependencies?: string;
  /**
   * Optional array value serialized in the `externalReferences` wire field.
   */
  externalReferences?: ExternalReference[];
  /**
   * Optional `string` value serialized in the `group` wire field.
   */
  group?: string;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  inactiveSince?: number;
  /**
   * Optional `boolean` value serialized in the `isLatest` wire field.
   */
  isLatest?: boolean;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastBomImport: number;
  /**
   * Optional `string` value serialized in the `lastBomImportFormat` wire field.
   */
  lastBomImportFormat?: string;
  /**
   * Optional `double`-formatted value serialized in the `lastInheritedRiskScore` wire field.
   */
  lastInheritedRiskScore?: number;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastVulnerabilityAnalysis?: number;
  /**
   * Optional object value serialized in the `manufacturer` wire field.
   */
  manufacturer?: OrganizationalEntity;
  /**
   * Optional object value serialized in the `metadata` wire field.
   */
  metadata?: ProjectMetadata;
  /**
   * Optional object value serialized in the `metrics` wire field.
   */
  metrics?: ProjectMetrics;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional object value serialized in the `parent` wire field.
   */
  parent?: Project;
  /**
   * Optional `string` value serialized in the `publisher` wire field.
   */
  publisher?: string;
  /**
   * Optional `string` value serialized in the `purl` wire field.
   */
  purl?: string;
  /**
   * Optional object value serialized in the `supplier` wire field.
   */
  supplier?: OrganizationalEntity;
  /**
   * Optional `string` value serialized in the `swidTagId` wire field.
   */
  swidTagId?: string;
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: Tag[];
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Optional `string` value serialized in the `version` wire field.
   */
  version?: string;
  /**
   * Optional array value serialized in the `versions` wire field.
   */
  versions?: ProjectVersion[];
}

/**
 * Typed representation of the `ProjectMetadata` API schema.
 */
export interface ProjectMetadata {
  /**
   * Optional array value serialized in the `authors` wire field.
   */
  authors?: OrganizationalContact[];
  /**
   * Optional object value serialized in the `supplier` wire field.
   */
  supplier?: OrganizationalEntity;
  /**
   * Optional object value serialized in the `tools` wire field.
   */
  tools?: Tools;
}

/**
 * Typed representation of the `RepositoryMetaComponent` API schema.
 */
export interface RepositoryMetaComponent {
  /**
   * UNIX epoch timestamp in milliseconds
   */
  lastCheck?: number;
  /**
   * Optional `string` value serialized in the `latestVersion` wire field.
   */
  latestVersion?: string;
  /**
   * UNIX epoch timestamp in milliseconds
   */
  latestVersionPublishedAt?: number;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `namespace` wire field.
   */
  namespace?: string;
  /**
   * Optional enumerated value serialized in the `repositoryType` wire field.
   */
  repositoryType?:
    | "MAVEN"
    | "NPM"
    | "GEM"
    | "PYPI"
    | "NUGET"
    | "HEX"
    | "COMPOSER"
    | "CARGO"
    | "GO_MODULES"
    | "CPAN"
    | "GITHUB"
    | "HACKAGE"
    | "NIXPKGS"
    | "UNSUPPORTED"
    | (string & {});
}

/**
 * Typed representation of the `ServiceAccount` API schema.
 */
export interface ServiceAccount {
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional `boolean` value serialized in the `suspended` wire field.
   */
  suspended?: boolean;
  /**
   * Optional array value serialized in the `teams` wire field.
   */
  teams?: Team[];
  /**
   * Required `string` value serialized in the `username` wire field.
   */
  username: string;
}

/**
 * Typed representation of the `ServiceComponent` API schema.
 */
export interface ServiceComponent {
  /**
   * Optional `boolean` value serialized in the `authenticated` wire field.
   */
  authenticated?: boolean;
  /**
   * Optional `string` value serialized in the `bomRef` wire field.
   */
  bomRef?: string;
  /**
   * Optional array value serialized in the `children` wire field.
   */
  children?: ServiceComponent[];
  /**
   * Optional `boolean` value serialized in the `crossesTrustBoundary` wire field.
   */
  crossesTrustBoundary?: boolean;
  /**
   * Optional array value serialized in the `data` wire field.
   */
  data?: DataClassification[];
  /**
   * Optional `string` value serialized in the `description` wire field.
   */
  description?: string;
  /**
   * Optional array value serialized in the `endpoints` wire field.
   */
  endpoints?: string[];
  /**
   * Optional array value serialized in the `externalReferences` wire field.
   */
  externalReferences?: ExternalReference[];
  /**
   * Optional `string` value serialized in the `group` wire field.
   */
  group?: string;
  /**
   * Optional `double`-formatted value serialized in the `lastInheritedRiskScore` wire field.
   */
  lastInheritedRiskScore?: number;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Optional `string` value serialized in the `notes` wire field.
   */
  notes?: string;
  /**
   * Optional object value serialized in the `parent` wire field.
   */
  parent?: ServiceComponent;
  /**
   * Required object value serialized in the `project` wire field.
   */
  project: Project;
  /**
   * Optional object value serialized in the `provider` wire field.
   */
  provider?: OrganizationalEntity;
  /**
   * Required `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid: string;
  /**
   * Optional `string` value serialized in the `version` wire field.
   */
  version?: string;
  /**
   * Optional array value serialized in the `vulnerabilities` wire field.
   */
  vulnerabilities?: Vulnerability[];
}

/**
 * Typed representation of the `Tag` API schema.
 */
export interface Tag {
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
}
