// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Permission } from "./shared.part002";

/**
 * Typed representation of the `DeleteTeamRequest` API schema.
 */
export interface DeleteTeamRequest {
  /**
   * UUID of the team to delete
   */
  uuid: string;
}

/**
 * Typed representation of the `TeamAlreadyExistsProblemDetails` API schema.
 */
export interface TeamAlreadyExistsProblemDetails {
  /**
   * Human-readable explanation specific to this occurrence of the problem

   * @example "Example detail"
   */
  detail: string;
  /**
   * Reference URI that identifies the specific occurrence of the problem

   * @example "https://api.example.org/foo/bar/example-instance"
   */
  instance?: string;
  /**
   * HTTP status code generated by the origin server for this occurrence of the problem

   * @example 400
   */
  status: number;
  /**
   * Name of the existing team
   */
  teamName?: string;
  /**
   * UUID of the existing team
   */
  teamUuid?: string;
  /**
   * Short, human-readable summary of the problem type

   * @example "Example title"
   */
  title: string;
  /**
   * A URI reference that identifies the problem type

   * @example "https://api.example.org/foo/bar/example-problem"
   */
  type?: string;
}

/**
 * Typed representation of the `TeamSelfResponse` API schema.
 */
export interface TeamSelfResponse {
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional array value serialized in the `permissions` wire field.
   */
  permissions?: Permission[];
  /**
   * Optional `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid?: string;
}

/**
 * Typed representation of the `VisibleTeams` API schema.
 */
export interface VisibleTeams {
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `uuid`-formatted value serialized in the `uuid` wire field.
   */
  uuid?: string;
}
