// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `DeleteUserRequest` API schema.
 */
export interface DeleteUserRequest {
  /**
   * Username of the user to delete
   */
  username: string;
}

/**
 * Typed representation of the `IdentifiableObject` API schema.
 */
export interface IdentifiableObject {
  /**
   * Optional `string` value serialized in the `uuid` wire field.
   */
  uuid?: string;
}

/**
 * Typed representation of the `TeamsSetRequest` API schema.
 */
export interface TeamsSetRequest {
  /**
   * Required array value serialized in the `teams` wire field.
   */
  teams: string[];
  /**
   * Required `string` value serialized in the `username` wire field.
   */
  username: string;
}
