// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ProblemDetails } from "./shared.part002";

export type InvalidBomProblemDetails = ProblemDetails & {
  /**
   * Errors identified during schema validation
   */
  errors?: string[];
};

/**
 * Typed representation of the `VexSubmitRequest` API schema.
 */
export interface VexSubmitRequest {
  /**
   * Required `string` value serialized in the `project` wire field.
   */
  project: string;
  /**
   * Required `string` value serialized in the `projectName` wire field.
   */
  projectName: string;
  /**
   * Required `string` value serialized in the `projectVersion` wire field.
   */
  projectVersion: string;
  /**
   * Required `string` value serialized in the `vex` wire field.
   */
  vex: string;
}
