// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Comment } from "./shared.part001";

/**
 * Typed representation of the `ViolationAnalysisRequest` API schema.
 */
export interface ViolationAnalysisRequest {
  /**
   * Optional enumerated value serialized in the `analysisState` wire field.
   */
  analysisState?: "APPROVED" | "REJECTED" | "NOT_SET" | (string & {});
  /**
   * Optional `string` value serialized in the `comment` wire field.
   */
  comment?: string;
  /**
   * Required `string` value serialized in the `component` wire field.
   */
  component: string;
  /**
   * Optional `boolean` value serialized in the `isSuppressed` wire field.
   */
  isSuppressed?: boolean;
  /**
   * Required `string` value serialized in the `policyViolation` wire field.
   */
  policyViolation: string;
  /**
   * Optional `boolean` value serialized in the `suppressed` wire field.
   */
  suppressed?: boolean;
}

/**
 * Typed representation of the `ViolationAnalysisResponse` API schema.
 */
export interface ViolationAnalysisResponse {
  /**
   * Audit trail of analysis comments
   */
  analysisComments: Comment[];
  /**
   * The state of the analysis decision
   */
  analysisState: "APPROVED" | "REJECTED" | "NOT_SET" | (string & {});
  /**
   * Whether the policy violation is suppressed
   */
  isSuppressed: boolean;
}
