// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../../helpers/mock-sdk.mjs";
import { configureClient } from "../../../dist/client.js";
import { SdkHttpError } from "../../../dist/errors.js";
import {
  getProjects,
  updateProject,
  createProject,
  deleteProjects,
  getProjectsByClassifier,
  cloneProject,
  getProjectsConcise,
  getProjectChildrenConcise,
  getLatestProjectByName,
} from "../../../dist/methods/project/part1.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getProjects: {
    route: "getProjects",
    mediaType: null,
    invoke: (bag) =>
      getProjects(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        name: bag["name"],
        excludeInactive: bag["excludeInactive"],
        onlyRoot: bag["onlyRoot"],
        notAssignedToTeamWithUuid: bag["notAssignedToTeamWithUuid"],
      }),
  },
  updateProject: {
    route: "updateProject",
    mediaType: "application/json",
    invoke: (bag) =>
      updateProject(config, {
        lastBomImport: bag.__body?.["lastBomImport"],
        name: bag.__body?.["name"],
        uuid: bag.__body?.["uuid"],
        accessTeams: bag.__body?.["accessTeams"],
        active: bag.__body?.["active"],
        author: bag.__body?.["author"],
        authors: bag.__body?.["authors"],
        bomRef: bag.__body?.["bomRef"],
        children: bag.__body?.["children"],
        classifier: bag.__body?.["classifier"],
        collectionLogic: bag.__body?.["collectionLogic"],
        collectionTag: bag.__body?.["collectionTag"],
        cpe: bag.__body?.["cpe"],
        description: bag.__body?.["description"],
        directDependencies: bag.__body?.["directDependencies"],
        externalReferences: bag.__body?.["externalReferences"],
        group: bag.__body?.["group"],
        inactiveSince: bag.__body?.["inactiveSince"],
        isLatest: bag.__body?.["isLatest"],
        lastBomImportFormat: bag.__body?.["lastBomImportFormat"],
        lastInheritedRiskScore: bag.__body?.["lastInheritedRiskScore"],
        lastVulnerabilityAnalysis: bag.__body?.["lastVulnerabilityAnalysis"],
        manufacturer: bag.__body?.["manufacturer"],
        metadata: bag.__body?.["metadata"],
        metrics: bag.__body?.["metrics"],
        parent: bag.__body?.["parent"],
        publisher: bag.__body?.["publisher"],
        purl: bag.__body?.["purl"],
        supplier: bag.__body?.["supplier"],
        swidTagId: bag.__body?.["swidTagId"],
        tags: bag.__body?.["tags"],
        version: bag.__body?.["version"],
        versions: bag.__body?.["versions"],
      }),
  },
  createProject: {
    route: "createProject",
    mediaType: "application/json",
    invoke: (bag) =>
      createProject(config, {
        lastBomImport: bag.__body?.["lastBomImport"],
        name: bag.__body?.["name"],
        uuid: bag.__body?.["uuid"],
        accessTeams: bag.__body?.["accessTeams"],
        active: bag.__body?.["active"],
        author: bag.__body?.["author"],
        authors: bag.__body?.["authors"],
        bomRef: bag.__body?.["bomRef"],
        children: bag.__body?.["children"],
        classifier: bag.__body?.["classifier"],
        collectionLogic: bag.__body?.["collectionLogic"],
        collectionTag: bag.__body?.["collectionTag"],
        cpe: bag.__body?.["cpe"],
        description: bag.__body?.["description"],
        directDependencies: bag.__body?.["directDependencies"],
        externalReferences: bag.__body?.["externalReferences"],
        group: bag.__body?.["group"],
        inactiveSince: bag.__body?.["inactiveSince"],
        isLatest: bag.__body?.["isLatest"],
        lastBomImportFormat: bag.__body?.["lastBomImportFormat"],
        lastInheritedRiskScore: bag.__body?.["lastInheritedRiskScore"],
        lastVulnerabilityAnalysis: bag.__body?.["lastVulnerabilityAnalysis"],
        manufacturer: bag.__body?.["manufacturer"],
        metadata: bag.__body?.["metadata"],
        metrics: bag.__body?.["metrics"],
        parent: bag.__body?.["parent"],
        publisher: bag.__body?.["publisher"],
        purl: bag.__body?.["purl"],
        supplier: bag.__body?.["supplier"],
        swidTagId: bag.__body?.["swidTagId"],
        tags: bag.__body?.["tags"],
        version: bag.__body?.["version"],
        versions: bag.__body?.["versions"],
      }),
  },
  deleteProjects: {
    route: "deleteProjects",
    mediaType: "application/json",
    invoke: (bag) => deleteProjects(config, bag.__body),
  },
  getProjectsByClassifier: {
    route: "getProjectsByClassifier",
    mediaType: null,
    invoke: (bag) =>
      getProjectsByClassifier(config, {
        classifier: bag["classifier"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        excludeInactive: bag["excludeInactive"],
        onlyRoot: bag["onlyRoot"],
      }),
  },
  cloneProject: {
    route: "cloneProject",
    mediaType: "application/json",
    invoke: (bag) =>
      cloneProject(config, {
        project: bag.__body?.["project"],
        version: bag.__body?.["version"],
        includeAcl: bag.__body?.["includeACL"],
        includeAuditHistory: bag.__body?.["includeAuditHistory"],
        includeComponents: bag.__body?.["includeComponents"],
        includeDependencies: bag.__body?.["includeDependencies"],
        includePolicyViolations: bag.__body?.["includePolicyViolations"],
        includeProperties: bag.__body?.["includeProperties"],
        includeServices: bag.__body?.["includeServices"],
        includeTags: bag.__body?.["includeTags"],
        makeCloneLatest: bag.__body?.["makeCloneLatest"],
      }),
  },
  getProjectsConcise: {
    route: "getProjectsConcise",
    mediaType: null,
    invoke: (bag) =>
      getProjectsConcise(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        name: bag["name"],
        version: bag["version"],
        classifier: bag["classifier"],
        tag: bag["tag"],
        team: bag["team"],
        active: bag["active"],
        onlyRoot: bag["onlyRoot"],
        includeMetrics: bag["includeMetrics"],
      }),
  },
  getProjectChildrenConcise: {
    route: "getProjectChildrenConcise",
    mediaType: null,
    invoke: (bag) =>
      getProjectChildrenConcise(config, {
        uuid: bag["uuid"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        name: bag["name"],
        version: bag["version"],
        classifier: bag["classifier"],
        tag: bag["tag"],
        team: bag["team"],
        active: bag["active"],
        includeMetrics: bag["includeMetrics"],
      }),
  },
  getLatestProjectByName: {
    route: "getLatestProjectByName",
    mediaType: null,
    invoke: (bag) => getLatestProjectByName(config, { name: bag["name"] }),
  },
};

test("project/part1 methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
