// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getAllFindings1,
  getAllFindings,
  getFindingsByProject,
  analyzeProject,
  exportFindingsByProject,
} from "../../dist/methods/finding.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getAllFindings1: {
    route: "getAllFindings_1",
    mediaType: null,
    invoke: (bag) =>
      getAllFindings1(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        showInactive: bag["showInactive"],
        showSuppressed: bag["showSuppressed"],
        severity: bag["severity"],
        analysisStatus: bag["analysisStatus"],
        vendorResponse: bag["vendorResponse"],
        publishDateFrom: bag["publishDateFrom"],
        publishDateTo: bag["publishDateTo"],
        attributedOnDateFrom: bag["attributedOnDateFrom"],
        attributedOnDateTo: bag["attributedOnDateTo"],
        textSearchField: bag["textSearchField"],
        textSearchInput: bag["textSearchInput"],
        cvssv2From: bag["cvssv2From"],
        cvssv2To: bag["cvssv2To"],
        cvssv3From: bag["cvssv3From"],
        cvssv3To: bag["cvssv3To"],
        cvssv4From: bag["cvssv4From"],
        cvssv4To: bag["cvssv4To"],
        epssFrom: bag["epssFrom"],
        epssTo: bag["epssTo"],
        epssPercentileFrom: bag["epssPercentileFrom"],
        epssPercentileTo: bag["epssPercentileTo"],
        isKev: bag["isKev"],
        totalCount: bag["totalCount"],
      }),
  },
  getAllFindings: {
    route: "getAllFindings",
    mediaType: null,
    invoke: (bag) =>
      getAllFindings(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        showInactive: bag["showInactive"],
        severity: bag["severity"],
        publishDateFrom: bag["publishDateFrom"],
        publishDateTo: bag["publishDateTo"],
        textSearchField: bag["textSearchField"],
        textSearchInput: bag["textSearchInput"],
        cvssv2From: bag["cvssv2From"],
        cvssv2To: bag["cvssv2To"],
        cvssv3From: bag["cvssv3From"],
        cvssv3To: bag["cvssv3To"],
        cvssv4From: bag["cvssv4From"],
        cvssv4To: bag["cvssv4To"],
        epssFrom: bag["epssFrom"],
        epssTo: bag["epssTo"],
        epssPercentileFrom: bag["epssPercentileFrom"],
        epssPercentileTo: bag["epssPercentileTo"],
        occurrencesFrom: bag["occurrencesFrom"],
        occurrencesTo: bag["occurrencesTo"],
        isKev: bag["isKev"],
        totalCount: bag["totalCount"],
      }),
  },
  getFindingsByProject: {
    route: "getFindingsByProject",
    mediaType: null,
    invoke: (bag) =>
      getFindingsByProject(config, {
        uuid: bag["uuid"],
        searchText: bag["searchText"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        suppressed: bag["suppressed"],
        source: bag["source"],
        accept: bag["accept"],
        hasAnalysis: bag["hasAnalysis"],
        epssFrom: bag["epssFrom"],
        epssTo: bag["epssTo"],
        isKev: bag["isKev"],
        totalCount: bag["totalCount"],
      }),
  },
  analyzeProject: {
    route: "analyzeProject",
    mediaType: null,
    invoke: (bag) => analyzeProject(config, { uuid: bag["uuid"] }),
  },
  exportFindingsByProject: {
    route: "exportFindingsByProject",
    mediaType: null,
    invoke: (bag) => exportFindingsByProject(config, { uuid: bag["uuid"] }),
  },
};

test("finding methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
