// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getAllNotificationPublishers,
  updateNotificationPublisher,
  createNotificationPublisher,
  testNotificationRule,
  deleteNotificationPublisher,
  getNotificationPublisherConfigSchema,
  deleteNotificationRule,
  getAllNotificationRules,
  updateNotificationRule,
  createNotificationRule,
  createScheduledNotificationRule,
  removeProjectFromRule,
  addProjectToRule,
  removeTeamFromRule,
  addTeamToRule,
} from "../../dist/methods/notification.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getAllNotificationPublishers: {
    route: "getAllNotificationPublishers",
    mediaType: null,
    invoke: () => getAllNotificationPublishers(config, {}),
  },
  updateNotificationPublisher: {
    route: "updateNotificationPublisher",
    mediaType: "application/json",
    invoke: (bag) =>
      updateNotificationPublisher(config, {
        extensionName: bag.__body?.["extensionName"],
        name: bag.__body?.["name"],
        uuid: bag.__body?.["uuid"],
        description: bag.__body?.["description"],
        template: bag.__body?.["template"],
        templateMimeType: bag.__body?.["templateMimeType"],
      }),
  },
  createNotificationPublisher: {
    route: "createNotificationPublisher",
    mediaType: "application/json",
    invoke: (bag) =>
      createNotificationPublisher(config, {
        extensionName: bag.__body?.["extensionName"],
        name: bag.__body?.["name"],
        description: bag.__body?.["description"],
        template: bag.__body?.["template"],
        templateMimeType: bag.__body?.["templateMimeType"],
      }),
  },
  testNotificationRule: {
    route: "testNotificationRule",
    mediaType: null,
    invoke: (bag) => testNotificationRule(config, { uuid: bag["uuid"] }),
  },
  deleteNotificationPublisher: {
    route: "deleteNotificationPublisher",
    mediaType: null,
    invoke: (bag) =>
      deleteNotificationPublisher(config, {
        notificationPublisherUuid: bag["notificationPublisherUuid"],
      }),
  },
  getNotificationPublisherConfigSchema: {
    route: "getNotificationPublisherConfigSchema",
    mediaType: null,
    invoke: (bag) => getNotificationPublisherConfigSchema(config, { uuid: bag["uuid"] }),
  },
  deleteNotificationRule: {
    route: "deleteNotificationRule",
    mediaType: "application/json",
    invoke: (bag) => deleteNotificationRule(config, { uuid: bag.__body?.["uuid"] }),
  },
  getAllNotificationRules: {
    route: "getAllNotificationRules",
    mediaType: null,
    invoke: (bag) =>
      getAllNotificationRules(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
        triggerType: bag["triggerType"],
      }),
  },
  updateNotificationRule: {
    route: "updateNotificationRule",
    mediaType: "application/json",
    invoke: (bag) =>
      updateNotificationRule(config, {
        level: bag.__body?.["level"],
        name: bag.__body?.["name"],
        scope: bag.__body?.["scope"],
        uuid: bag.__body?.["uuid"],
        enabled: bag.__body?.["enabled"],
        filterExpression: bag.__body?.["filterExpression"],
        logSuccessfulPublish: bag.__body?.["logSuccessfulPublish"],
        notifyChildren: bag.__body?.["notifyChildren"],
        notifyOn: bag.__body?.["notifyOn"],
        publisherConfig: bag.__body?.["publisherConfig"],
        scheduleCron: bag.__body?.["scheduleCron"],
        scheduleSkipUnchanged: bag.__body?.["scheduleSkipUnchanged"],
        tags: bag.__body?.["tags"],
      }),
  },
  createNotificationRule: {
    route: "createNotificationRule",
    mediaType: "application/json",
    invoke: (bag) =>
      createNotificationRule(config, {
        level: bag.__body?.["level"],
        name: bag.__body?.["name"],
        publisher: bag.__body?.["publisher"],
        scope: bag.__body?.["scope"],
      }),
  },
  createScheduledNotificationRule: {
    route: "createScheduledNotificationRule",
    mediaType: "application/json",
    invoke: (bag) =>
      createScheduledNotificationRule(config, {
        level: bag.__body?.["level"],
        name: bag.__body?.["name"],
        publisher: bag.__body?.["publisher"],
        scope: bag.__body?.["scope"],
      }),
  },
  removeProjectFromRule: {
    route: "removeProjectFromRule",
    mediaType: null,
    invoke: (bag) =>
      removeProjectFromRule(config, { ruleUuid: bag["ruleUuid"], projectUuid: bag["projectUuid"] }),
  },
  addProjectToRule: {
    route: "addProjectToRule",
    mediaType: null,
    invoke: (bag) =>
      addProjectToRule(config, { ruleUuid: bag["ruleUuid"], projectUuid: bag["projectUuid"] }),
  },
  removeTeamFromRule: {
    route: "removeTeamFromRule",
    mediaType: null,
    invoke: (bag) =>
      removeTeamFromRule(config, { ruleUuid: bag["ruleUuid"], teamUuid: bag["teamUuid"] }),
  },
  addTeamToRule: {
    route: "addTeamToRule",
    mediaType: null,
    invoke: (bag) =>
      addTeamToRule(config, { ruleUuid: bag["ruleUuid"], teamUuid: bag["teamUuid"] }),
  },
};

test("notification methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
