// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  getRepositories,
  updateRepository,
  createRepository,
  getRepositoryMetaComponent,
  getRepositoriesByType,
  deleteRepository,
} from "../../dist/methods/repository.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  getRepositories: {
    route: "getRepositories",
    mediaType: null,
    invoke: (bag) =>
      getRepositories(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  updateRepository: {
    route: "updateRepository",
    mediaType: "application/json",
    invoke: (bag) =>
      updateRepository(config, {
        authenticationRequired: bag.__body?.["authenticationRequired"],
        enabled: bag.__body?.["enabled"],
        url: bag.__body?.["url"],
        uuid: bag.__body?.["uuid"],
        internal: bag.__body?.["internal"],
        password: bag.__body?.["password"],
        username: bag.__body?.["username"],
      }),
  },
  createRepository: {
    route: "createRepository",
    mediaType: "application/json",
    invoke: (bag) =>
      createRepository(config, {
        authenticationRequired: bag.__body?.["authenticationRequired"],
        enabled: bag.__body?.["enabled"],
        identifier: bag.__body?.["identifier"],
        ["type"]: bag.__body?.["type"],
        url: bag.__body?.["url"],
        internal: bag.__body?.["internal"],
        password: bag.__body?.["password"],
        username: bag.__body?.["username"],
      }),
  },
  getRepositoryMetaComponent: {
    route: "getRepositoryMetaComponent",
    mediaType: null,
    invoke: (bag) => getRepositoryMetaComponent(config, { purl: bag["purl"] }),
  },
  getRepositoriesByType: {
    route: "getRepositoriesByType",
    mediaType: null,
    invoke: (bag) =>
      getRepositoriesByType(config, {
        ["type"]: bag["type"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  deleteRepository: {
    route: "deleteRepository",
    mediaType: null,
    invoke: (bag) => deleteRepository(config, { uuid: bag["uuid"] }),
  },
};

test("repository methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
