// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  deleteTags,
  getAllTags,
  createTags,
  getTagsForPolicy,
  getTaggedCollectionProjects,
  untagNotificationRules,
  getTaggedNotificationRules,
  tagNotificationRules,
  untagPolicies,
  getTaggedPolicies,
  tagPolicies,
  untagProjects,
  getTaggedProjects,
  tagProjects,
  untagVulnerabilities,
  getTaggedVulnerabilities,
} from "../../dist/methods/tag.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  deleteTags: {
    route: "deleteTags",
    mediaType: "application/json",
    invoke: (bag) => deleteTags(config, bag.__body),
  },
  getAllTags: {
    route: "getAllTags",
    mediaType: null,
    invoke: (bag) =>
      getAllTags(config, {
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  createTags: {
    route: "createTags",
    mediaType: "application/json",
    invoke: (bag) => createTags(config, bag.__body),
  },
  getTagsForPolicy: {
    route: "getTagsForPolicy",
    mediaType: null,
    invoke: (bag) => getTagsForPolicy(config, { uuid: bag["uuid"] }),
  },
  getTaggedCollectionProjects: {
    route: "getTaggedCollectionProjects",
    mediaType: null,
    invoke: (bag) =>
      getTaggedCollectionProjects(config, {
        name: bag["name"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  untagNotificationRules: {
    route: "untagNotificationRules",
    mediaType: "application/json",
    invoke: (bag) => untagNotificationRules(config, { body: bag.__body, name: bag["name"] }),
  },
  getTaggedNotificationRules: {
    route: "getTaggedNotificationRules",
    mediaType: null,
    invoke: (bag) =>
      getTaggedNotificationRules(config, {
        name: bag["name"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  tagNotificationRules: {
    route: "tagNotificationRules",
    mediaType: "application/json",
    invoke: (bag) => tagNotificationRules(config, { body: bag.__body, name: bag["name"] }),
  },
  untagPolicies: {
    route: "untagPolicies",
    mediaType: "application/json",
    invoke: (bag) => untagPolicies(config, { body: bag.__body, name: bag["name"] }),
  },
  getTaggedPolicies: {
    route: "getTaggedPolicies",
    mediaType: null,
    invoke: (bag) =>
      getTaggedPolicies(config, {
        name: bag["name"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  tagPolicies: {
    route: "tagPolicies",
    mediaType: "application/json",
    invoke: (bag) => tagPolicies(config, { body: bag.__body, name: bag["name"] }),
  },
  untagProjects: {
    route: "untagProjects",
    mediaType: "application/json",
    invoke: (bag) => untagProjects(config, { body: bag.__body, name: bag["name"] }),
  },
  getTaggedProjects: {
    route: "getTaggedProjects",
    mediaType: null,
    invoke: (bag) =>
      getTaggedProjects(config, {
        name: bag["name"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
  tagProjects: {
    route: "tagProjects",
    mediaType: "application/json",
    invoke: (bag) => tagProjects(config, { body: bag.__body, name: bag["name"] }),
  },
  untagVulnerabilities: {
    route: "untagVulnerabilities",
    mediaType: "application/json",
    invoke: (bag) => untagVulnerabilities(config, { body: bag.__body, name: bag["name"] }),
  },
  getTaggedVulnerabilities: {
    route: "getTaggedVulnerabilities",
    mediaType: null,
    invoke: (bag) =>
      getTaggedVulnerabilities(config, {
        name: bag["name"],
        pageNumber: bag["pageNumber"],
        pageSize: bag["pageSize"],
        offset: bag["offset"],
        limit: bag["limit"],
        sortName: bag["sortName"],
        sortOrder: bag["sortOrder"],
      }),
  },
};

test("tag methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
