// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { AclNamespace } from "./methods/acl";
import { AnalysisNamespace } from "./methods/analysis";
import { BadgeNamespace } from "./methods/badge";
import { BomNamespace } from "./methods/bom";
import { CalculatorNamespace } from "./methods/calculator";
import { ComponentNamespace } from "./methods/component";
import { ComponentPropertyNamespace } from "./methods/componentProperty";
import { ConfigPropertyNamespace } from "./methods/configProperty";
import { CweNamespace } from "./methods/cwe";
import { DependencyGraphNamespace } from "./methods/dependencyGraph";
import { EventNamespace } from "./methods/event";
import { FindingNamespace } from "./methods/finding";
import { LdapNamespace } from "./methods/ldap";
import { LicenseNamespace } from "./methods/license";
import { LicenseGroupNamespace } from "./methods/licenseGroup";
import { MetricsNamespace } from "./methods/metrics";
import { NotificationNamespace } from "./methods/notification";
import { OidcNamespace } from "./methods/oidc";
import { PermissionNamespace } from "./methods/permission";
import { PolicyNamespace } from "./methods/policy";
import { PolicyConditionNamespace } from "./methods/policyCondition";
import { ProjectNamespace } from "./methods/project";
import { ProjectPropertyNamespace } from "./methods/projectProperty";
import { RepositoryNamespace } from "./methods/repository";
import { ServiceNamespace } from "./methods/service";
import { TagNamespace } from "./methods/tag";
import { TeamNamespace } from "./methods/team";
import { UserNamespace } from "./methods/user";
import { VexNamespace } from "./methods/vex";
import { ViolationNamespace } from "./methods/violation";
import { ViolationanalysisNamespace } from "./methods/violationanalysis";
import { VulnerabilityNamespace } from "./methods/vulnerability";
import { VersionNamespace } from "./methods/version";

export class OWASPDependencyTrack {
  private readonly _config: ClientConfig;
  readonly acl: AclNamespace;
  readonly analysis: AnalysisNamespace;
  readonly badge: BadgeNamespace;
  readonly bom: BomNamespace;
  readonly calculator: CalculatorNamespace;
  readonly component: ComponentNamespace;
  readonly componentProperty: ComponentPropertyNamespace;
  readonly configProperty: ConfigPropertyNamespace;
  readonly cwe: CweNamespace;
  readonly dependencyGraph: DependencyGraphNamespace;
  readonly event: EventNamespace;
  readonly finding: FindingNamespace;
  readonly ldap: LdapNamespace;
  readonly license: LicenseNamespace;
  readonly licenseGroup: LicenseGroupNamespace;
  readonly metrics: MetricsNamespace;
  readonly notification: NotificationNamespace;
  readonly oidc: OidcNamespace;
  readonly permission: PermissionNamespace;
  readonly policy: PolicyNamespace;
  readonly policyCondition: PolicyConditionNamespace;
  readonly project: ProjectNamespace;
  readonly projectProperty: ProjectPropertyNamespace;
  readonly repository: RepositoryNamespace;
  readonly service: ServiceNamespace;
  readonly tag: TagNamespace;
  readonly team: TeamNamespace;
  readonly user: UserNamespace;
  readonly vex: VexNamespace;
  readonly violation: ViolationNamespace;
  readonly violationanalysis: ViolationanalysisNamespace;
  readonly vulnerability: VulnerabilityNamespace;
  readonly version: VersionNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.acl = new AclNamespace(config);
    this.analysis = new AnalysisNamespace(config);
    this.badge = new BadgeNamespace(config);
    this.bom = new BomNamespace(config);
    this.calculator = new CalculatorNamespace(config);
    this.component = new ComponentNamespace(config);
    this.componentProperty = new ComponentPropertyNamespace(config);
    this.configProperty = new ConfigPropertyNamespace(config);
    this.cwe = new CweNamespace(config);
    this.dependencyGraph = new DependencyGraphNamespace(config);
    this.event = new EventNamespace(config);
    this.finding = new FindingNamespace(config);
    this.ldap = new LdapNamespace(config);
    this.license = new LicenseNamespace(config);
    this.licenseGroup = new LicenseGroupNamespace(config);
    this.metrics = new MetricsNamespace(config);
    this.notification = new NotificationNamespace(config);
    this.oidc = new OidcNamespace(config);
    this.permission = new PermissionNamespace(config);
    this.policy = new PolicyNamespace(config);
    this.policyCondition = new PolicyConditionNamespace(config);
    this.project = new ProjectNamespace(config);
    this.projectProperty = new ProjectPropertyNamespace(config);
    this.repository = new RepositoryNamespace(config);
    this.service = new ServiceNamespace(config);
    this.tag = new TagNamespace(config);
    this.team = new TeamNamespace(config);
    this.user = new UserNamespace(config);
    this.vex = new VexNamespace(config);
    this.violation = new ViolationNamespace(config);
    this.violationanalysis = new ViolationanalysisNamespace(config);
    this.vulnerability = new VulnerabilityNamespace(config);
    this.version = new VersionNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
