// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { Component, ProblemDetails } from "../../types/shared";
import type { ClientConfig, RequestOptions } from "../../client";
import { encodePathSegment, fromWire, queryValue, sdkRequest, toWire } from "../../client";
import { validateLength, validatePattern, validateUuid } from "../../validation";

export type UpdateComponentError = ProblemDetails;

export type UpdateComponentParams = Component;

/**
 * Updates an existing component using the supplied component properties. When you provide a body, include `classifier`, `name`, `project`, and `uuid`; the authenticated user also needs PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE permission. The response contains the updated component.
 *
 * Requires permission PORTFOLIO_MANAGEMENT or PORTFOLIO_MANAGEMENT_UPDATE
 *
 * @param classifier - Required enumerated value serialized in the `classifier`
 *   wire field.
 * @param name - Required `string` value serialized in the `name` wire field.
 * @param project - Required object value serialized in the `project` wire field.
 * @param uuid - Required `uuid`-formatted value serialized in the `uuid` wire
 *   field.
 * @param author - Optional `string` value serialized in the `author` wire field.
 * @param authors - Optional array value serialized in the `authors` wire field.
 * @param blake2b256 - Optional `string` value serialized in the `blake2b_256`
 *   wire field.
 * @param blake2b384 - Optional `string` value serialized in the `blake2b_384`
 *   wire field.
 * @param blake2b512 - Optional `string` value serialized in the `blake2b_512`
 *   wire field.
 * @param blake3 - Optional `string` value serialized in the `blake3` wire field.
 * @param children - Optional array value serialized in the `children` wire
 *   field.
 * @param copyright - Optional `string` value serialized in the `copyright` wire
 *   field.
 * @param cpe - Optional `string` value serialized in the `cpe` wire field.
 * @param dependencyGraph - Optional array value serialized in the
 *   `dependencyGraph` wire field.
 * @param description - Optional `string` value serialized in the `description`
 *   wire field.
 * @param directDependencies - Optional `string` value serialized in the
 *   `directDependencies` wire field.
 * @param expandDependencyGraph - Optional `boolean` value serialized in the
 *   `expandDependencyGraph` wire field.
 * @param extension - Optional `string` value serialized in the `extension` wire
 *   field.
 * @param externalReferences - Optional array value serialized in the
 *   `externalReferences` wire field.
 * @param filename - Optional `string` value serialized in the `filename` wire
 *   field.
 * @param group - Optional `string` value serialized in the `group` wire field.
 * @param isInternal - Optional `boolean` value serialized in the `isInternal`
 *   wire field.
 * @param lastInheritedRiskScore - Optional `double`-formatted value serialized
 *   in the `lastInheritedRiskScore` wire field.
 * @param license - Optional `string` value serialized in the `license` wire
 *   field.
 * @param licenseExpression - Optional `string` value serialized in the
 *   `licenseExpression` wire field.
 * @param licenseUrl - Optional `string` value serialized in the `licenseUrl`
 *   wire field.
 * @param md5 - Optional `string` value serialized in the `md5` wire field.
 * @param metrics - Optional object value serialized in the `metrics` wire field.
 * @param notes - Optional `string` value serialized in the `notes` wire field.
 * @param occurrenceCount - Optional `int64`-formatted value serialized in the
 *   `occurrenceCount` wire field.
 * @param parent - Optional object value serialized in the `parent` wire field.
 * @param properties - Optional array value serialized in the `properties` wire
 *   field.
 * @param publisher - Optional `string` value serialized in the `publisher` wire
 *   field.
 * @param purl - Optional `string` value serialized in the `purl` wire field.
 * @param purlCoordinates - Optional `string` value serialized in the
 *   `purlCoordinates` wire field.
 * @param repositoryMeta - Optional object value serialized in the
 *   `repositoryMeta` wire field.
 * @param resolvedLicense - Optional object value serialized in the
 *   `resolvedLicense` wire field.
 * @param scope - Optional enumerated value serialized in the `scope` wire field.
 * @param sha1 - Optional `string` value serialized in the `sha1` wire field.
 * @param sha256 - Optional `string` value serialized in the `sha256` wire field.
 * @param sha384 - Optional `string` value serialized in the `sha384` wire field.
 * @param sha3256 - Optional `string` value serialized in the `sha3_256` wire
 *   field.
 * @param sha3384 - Optional `string` value serialized in the `sha3_384` wire
 *   field.
 * @param sha3512 - Optional `string` value serialized in the `sha3_512` wire
 *   field.
 * @param sha512 - Optional `string` value serialized in the `sha512` wire field.
 * @param streebog256 - Optional `string` value serialized in the `streebog_256`
 *   wire field.
 * @param streebog512 - Optional `string` value serialized in the `streebog_512`
 *   wire field.
 * @param supplier - Optional object value serialized in the `supplier` wire
 *   field.
 * @param swidTagId - Optional `string` value serialized in the `swidTagId` wire
 *   field.
 * @param version - Optional `string` value serialized in the `version` wire
 *   field.
 * @param vulnerabilities - Optional array value serialized in the
 *   `vulnerabilities` wire field.
 */
export async function updateComponent(
  config: ClientConfig,
  {
    classifier,
    name,
    project,
    uuid,
    author,
    authors,
    blake2b256,
    blake2b384,
    blake2b512,
    blake3,
    children,
    copyright,
    cpe,
    dependencyGraph,
    description,
    directDependencies,
    expandDependencyGraph,
    extension,
    externalReferences,
    filename,
    group,
    isInternal,
    lastInheritedRiskScore,
    license,
    licenseExpression,
    licenseUrl,
    md5,
    metrics,
    notes,
    occurrenceCount,
    parent,
    properties,
    publisher,
    purl,
    purlCoordinates,
    repositoryMeta,
    resolvedLicense,
    scope,
    sha1,
    sha256,
    sha384,
    sha3256,
    sha3384,
    sha3512,
    sha512,
    streebog256,
    streebog512,
    supplier,
    swidTagId,
    version,
    vulnerabilities,
  }: UpdateComponentParams,
  requestOptions?: RequestOptions,
): Promise<Component> {
  validateLength("name", name, { min: 1, max: 255 });

  validateUuid("uuid", uuid);

  if (blake2b256 != null) {
    validatePattern("blake2b_256", blake2b256, "^[0-9a-f]{64}$");
  }

  if (blake2b384 != null) {
    validatePattern("blake2b_384", blake2b384, "^[0-9a-f]{96}$");
  }

  if (blake2b512 != null) {
    validatePattern("blake2b_512", blake2b512, "^[0-9a-f]{128}$");
  }

  if (blake3 != null) {
    validatePattern("blake3", blake3, "^[A-Fa-f0-9]*$");
  }

  if (copyright != null) {
    validateLength("copyright", copyright, { min: 0, max: 1024 });
  }

  if (cpe != null) {
    validateLength("cpe", cpe, { min: 0, max: 255 });
    validatePattern(
      "cpe",
      cpe,
      "(cpe:2\\.3:[aho\\*\\-](:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){5}(:(([a-zA-Z]{2,3}(-([a-zA-Z]{2}|[0-9]{3}))?)|[\\*\\-]))(:(((\\?*|\\*?)([a-zA-Z0-9\\-\\._]|(\\\\[\\\\\\*\\?!\"#$$%&'\\(\\)\\+,/:;<=>@\\[\\]\\^`\\{\\|}~]))+(\\?*|\\*?))|[\\*\\-])){4})|([c][pP][eE]:/[AHOaho]?(:[A-Za-z0-9\\._\\-~%]*){0,6})",
    );
  }

  if (description != null) {
    validateLength("description", description, { min: 0, max: 1024 });
  }

  if (extension != null) {
    validateLength("extension", extension, { min: 0, max: 255 });
  }

  if (filename != null) {
    validateLength("filename", filename, { min: 0, max: 255 });
  }

  if (group != null) {
    validateLength("group", group, { min: 0, max: 255 });
  }

  if (license != null) {
    validateLength("license", license, { min: 0, max: 255 });
  }

  if (licenseUrl != null) {
    validateLength("licenseUrl", licenseUrl, { min: 0, max: 255 });
    validatePattern(
      "licenseUrl",
      licenseUrl,
      "^((((https?|ftps?|sftp|imap|rtsp|rtmp|sip|sips|git|ssh|telnet|nntp|file)://)|(mailto:|news:))(%[0-9A-Fa-f]{2}|[-()_.!~*';/?:@&=+$,A-Za-z0-9])+)([).!';/?:,][[:blank:]])?$",
    );
  }

  if (md5 != null) {
    validatePattern("md5", md5, "^[0-9a-fA-F]{32}$");
  }

  if (publisher != null) {
    validateLength("publisher", publisher, { min: 0, max: 255 });
  }

  if (purl != null) {
    validateLength("purl", purl, { min: 0, max: 1024 });
  }

  if (purlCoordinates != null) {
    validateLength("purlCoordinates", purlCoordinates, { min: 0, max: 1024 });
  }

  if (scope != null) {
    validateLength("scope", scope, { min: 0, max: 255 });
  }

  if (sha1 != null) {
    validatePattern("sha1", sha1, "^[0-9a-fA-F]{40}$");
  }

  if (sha256 != null) {
    validatePattern("sha256", sha256, "^[0-9a-fA-F]{64}$");
  }

  if (sha384 != null) {
    validatePattern("sha384", sha384, "^[0-9a-fA-F]{96}$");
  }

  if (sha3256 != null) {
    validatePattern("sha3_256", sha3256, "^[0-9a-fA-F]{64}$");
  }

  if (sha3384 != null) {
    validatePattern("sha3_384", sha3384, "^[0-9a-fA-F]{96}$");
  }

  if (sha3512 != null) {
    validatePattern("sha3_512", sha3512, "^[0-9a-fA-F]{128}$");
  }

  if (sha512 != null) {
    validatePattern("sha512", sha512, "^[0-9a-fA-F]{128}$");
  }

  if (streebog256 != null) {
    validatePattern("streebog_256", streebog256, "^[0-9a-fA-F]{64}$");
  }

  if (streebog512 != null) {
    validatePattern("streebog_512", streebog512, "^[0-9a-fA-F]{128}$");
  }

  if (swidTagId != null) {
    validateLength("swidTagId", swidTagId, { min: 0, max: 255 });
  }

  if (version != null) {
    validateLength("version", version, { min: 0, max: 255 });
  }

  const _resp = await sdkRequest<Component>({
    method: "POST",
    path: `/v1/component`,
    operationId: "updateComponent",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      classifier,
      name,
      project: toWire(project, "Project"),
      uuid,
      author,
      authors,
      blake2b_256: blake2b256,
      blake2b_384: blake2b384,
      blake2b_512: blake2b512,
      blake3,
      children: toWire(children, "Component"),
      copyright,
      cpe,
      dependencyGraph,
      description,
      directDependencies,
      expandDependencyGraph,
      extension,
      externalReferences,
      filename,
      group,
      isInternal,
      lastInheritedRiskScore,
      license,
      licenseExpression,
      licenseUrl,
      md5,
      metrics,
      notes,
      occurrenceCount,
      parent: toWire(parent, "Component"),
      properties,
      publisher,
      purl,
      purlCoordinates,
      repositoryMeta,
      resolvedLicense,
      scope,
      sha1,
      sha256,
      sha384,
      sha3_256: sha3256,
      sha3_384: sha3384,
      sha3_512: sha3512,
      sha512,
      streebog_256: streebog256,
      streebog_512: streebog512,
      supplier,
      swidTagId,
      version,
      vulnerabilities: toWire(vulnerabilities, "Vulnerability"),
    },
    config,
  });
  return fromWire(_resp.data, "Component") as Component;
}

export interface GetComponentByHashParams {
  hash: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
}

/**
 * Requires permission VIEW_PORTFOLIO Deprecated ! Use /api/v2/components instead.
 *
 * @param hash - The MD5, SHA-1, SHA-256, SHA-384, SHA-512, SHA3-256, SHA3-384,
 *   SHA3-512, BLAKE2b-256, BLAKE2b-384, BLAKE2b-512, BLAKE3, Streebog-256, or
 *   Streebog-512 hash of the component to retrieve
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @deprecated This operation is deprecated and may be removed in a future
 *   release.
 */
export async function getComponentByHash(
  config: ClientConfig,
  { hash, pageNumber, pageSize, offset, limit, sortName, sortOrder }: GetComponentByHashParams,
  requestOptions?: RequestOptions,
): Promise<Component[]> {
  const _resp = await sdkRequest<Component[]>({
    method: "GET",
    path: `/v1/component/hash/${encodePathSegment(hash)}`,
    operationId: "getComponentByHash",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "Component") as Component[];
}

export type GetComponentByIdentityError = ProblemDetails;

export interface GetComponentByIdentityParams {
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  group?: string;
  name?: string;
  version?: string;
  purl?: string;
  cpe?: string;
  swidTagId?: string;
  project?: string;
  excludeInactiveProjects?: boolean;
  onlyLatestProjectVersions?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO Deprecated ! Use /api/v2/components instead.
 *
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param group - The group of the component
 * @param name - The name of the component
 * @param version - The version of the component
 * @param purl - The purl of the component
 * @param cpe - The cpe of the component
 * @param swidTagId - The swidTagId of the component
 * @param project - The project the component belongs to
 * @param excludeInactiveProjects - When true, only return components from active
 *   projects
 * @param onlyLatestProjectVersions - When true, only return components from
 *   projects flagged as the latest version
 * @deprecated This operation is deprecated and may be removed in a future
 *   release.
 */
export async function getComponentByIdentity(
  config: ClientConfig,
  {
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    group,
    name,
    version,
    purl,
    cpe,
    swidTagId,
    project,
    excludeInactiveProjects,
    onlyLatestProjectVersions,
  }: GetComponentByIdentityParams = {},
  requestOptions?: RequestOptions,
): Promise<Component[]> {
  if (project != null) {
    validateUuid("project", project);
  }

  const _resp = await sdkRequest<Component[]>({
    method: "GET",
    path: `/v1/component/identity`,
    operationId: "getComponentByIdentity",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      group: queryValue(group, "form", true),
      name: queryValue(name, "form", true),
      version: queryValue(version, "form", true),
      purl: queryValue(purl, "form", true),
      cpe: queryValue(cpe, "form", true),
      swidTagId: queryValue(swidTagId, "form", true),
      project: queryValue(project, "form", true),
      excludeInactiveProjects: queryValue(excludeInactiveProjects, "form", true),
      onlyLatestProjectVersions: queryValue(onlyLatestProjectVersions, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "Component") as Component[];
}

/**
 * Requires permission SYSTEM_CONFIGURATION or SYSTEM_CONFIGURATION_READ
 */
export async function identifyInternalComponents(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<void> {
  const _resp = await sdkRequest<void>({
    method: "GET",
    path: `/v1/component/internal/identify`,
    operationId: "identifyInternalComponents",
    responseDecoder: "empty",
    ...requestOptions,
    config,
  });
  void _resp.data;
  return;
}

export type GetDependencyGraphForComponentError = ProblemDetails;

export interface GetDependencyGraphForComponentParams {
  projectUuid: string;
  componentUuids: string;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param projectUuid - The UUID of the project to get the expanded dependency
 *   graph for
 * @param componentUuids - List of UUIDs of the components (separated by |) to
 *   get the expanded dependency graph for
 */
export async function getDependencyGraphForComponent(
  config: ClientConfig,
  { projectUuid, componentUuids }: GetDependencyGraphForComponentParams,
  requestOptions?: RequestOptions,
): Promise<{ [key: string]: unknown }> {
  validateUuid("projectUuid", projectUuid);

  const _resp = await sdkRequest<{ [key: string]: unknown }>({
    method: "GET",
    path: `/v1/component/project/${encodePathSegment(projectUuid)}/dependencyGraph/${encodePathSegment(componentUuids)}`,
    operationId: "getDependencyGraphForComponent",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type GetAllComponentsError = ProblemDetails;

export interface GetAllComponentsParams {
  uuid: string;
  pageNumber?: string;
  pageSize?: string;
  offset?: string;
  limit?: string;
  sortName?: string;
  sortOrder?: "asc, desc" | (string & {});
  onlyOutdated?: boolean;
  onlyDirect?: boolean;
}

/**
 * Requires permission VIEW_PORTFOLIO
 *
 * @param uuid - The UUID of the project to retrieve components for
 * @param pageNumber - The page to return. To be used in conjunction with
 *   pageSize .
 * @param pageSize - Number of elements to return per page. To be used in
 *   conjunction with pageNumber .
 * @param offset - Offset to start returning elements from. To be used in
 *   conjunction with limit .
 * @param limit - Number of elements to return per page. To be used in
 *   conjunction with offset .
 * @param sortName - Name of the resource field to sort on.
 * @param sortOrder - Ordering of items when sorting with sortName .
 * @param onlyOutdated - Optionally exclude recent components so only outdated
 *   components are returned
 * @param onlyDirect - Optionally exclude transitive dependencies so only direct
 *   dependencies are returned
 */
export async function getAllComponents(
  config: ClientConfig,
  {
    uuid,
    pageNumber,
    pageSize,
    offset,
    limit,
    sortName,
    sortOrder,
    onlyOutdated,
    onlyDirect,
  }: GetAllComponentsParams,
  requestOptions?: RequestOptions,
): Promise<Component[]> {
  validateUuid("uuid", uuid);

  const _resp = await sdkRequest<Component[]>({
    method: "GET",
    path: `/v1/component/project/${encodePathSegment(uuid)}`,
    operationId: "getAllComponents",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      pageNumber: queryValue(pageNumber, "form", true),
      pageSize: queryValue(pageSize, "form", true),
      offset: queryValue(offset, "form", true),
      limit: queryValue(limit, "form", true),
      sortName: queryValue(sortName, "form", true),
      sortOrder: queryValue(sortOrder, "form", true),
      onlyOutdated: queryValue(onlyOutdated, "form", true),
      onlyDirect: queryValue(onlyDirect, "form", true),
    },
    config,
  });
  return fromWire(_resp.data, "Component") as Component[];
}
